Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2020-09, with the labels that each got.

#1566 chore(charts): upgrade carbon charts to get the latest version
  package.json
  yarn.lock
Labels: status: one more review 👀

#1553 feat(hierarchylist) allow list items to be expanded by default #1545
  src/components/List/HierarchyList/HierarchyList.jsx
  src/components/List/HierarchyList/HierarchyList.story.jsx
  src/components/List/HierarchyList/HierarchyList.test.jsx
  src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1517 fix(cardrenderer): allow passed available actions
  src/components/Dashboard/CardRenderer.jsx
  src/components/Dashboard/Dashboard.story.jsx
  src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
Labels: status: ready to merge :tada:

#1558 fix(button): proper icon placement in RTL
  src/components/Button/_button.scss
Labels: status: ready to merge :tada:

#1591 fix(timeseries): the iseditable state was allowing interaction and not showing sampledata
  src/components/BarChartCard/_bar-chart-card.scss
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.test.jsx
  src/components/TimeSeriesCard/_time-series-card.scss
Labels: status: ready to merge :tada:

#1595 fix(modal): overflow menu and tooltip contents hidden in modal
  src/components/ComposedModal/ComposedModal.jsx
  src/components/ComposedModal/ComposedModal.story.jsx
  src/components/ComposedModal/__snapshots__/ComposedModal.story.storyshot
  src/components/ComposedModal/_composed-modal.scss
  src/components/Table/TableManageViewsModal/__snapshots__/TableManageViewsModal.story.storyshot
  src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
Labels: status: one more review 👀

#1590 fix(timeseries): handle tooltip errors caused by the latest carbon charts update
  package.json
  rollup.config.js
  src/components/BarChartCard/barChartUtils.js
  src/components/BarChartCard/barChartUtils.test.js
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.test.jsx
  src/components/TimeSeriesCard/timeSeriesUtils.js
  yarn.lock
Labels: status: ready to merge :tada:

#1605 feat(list-item): add disabled prop and functionality
  src/components/List/List.jsx
  src/components/List/ListItem/ListItem.jsx
  src/components/List/ListItem/ListItem.story.jsx
  src/components/List/ListItem/_list-item.scss
Labels: status: one more review 👀

#1564 feat(list): added reordering
  src/components/List/HierarchyList/BulkActionHeader.jsx
  src/components/List/HierarchyList/HierarchyList.jsx
  src/components/List/HierarchyList/HierarchyList.story.jsx
  src/components/List/HierarchyList/HierarchyList.test.jsx
  src/components/List/HierarchyList/HierarchyListReorderModal.test.jsx
  src/components/List/HierarchyList/HierarchyListReorderModal/HierarchyListReorderModal.jsx
  src/components/List/HierarchyList/HierarchyListReorderModal/HierarchyReorderModalRadioGroup.jsx
  src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  src/components/List/HierarchyList/_hierarchy-list.scss
  src/components/List/List.jsx
  src/components/List/List.story.jsx
  src/components/List/List.test.jsx
  src/components/List/ListHeader/_list-header.scss
  src/components/List/ListItem/ListItem.jsx
  src/components/List/ListItem/ListItem.test.jsx
  src/components/List/ListItem/ListItemWrapper.jsx
  src/components/List/ListItem/ListTarget.jsx
  src/components/List/ListItem/_list-item.scss
  src/components/List/SimpleList/SimpleList.jsx
  src/components/List/SimpleList/SimpleList.story.jsx
  src/components/List/SimpleList/SimpleList.test.jsx
  src/components/List/__snapshots__/List.story.storyshot
  src/components/List/_list.scss
  src/styles.scss
  src/utils/DragAndDropUtils.jsx
  src/utils/__tests__/DragAndDropUtils.test.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1586 chore(card): added gauge and value card expand stories
  src/components/Card/Card.jsx
  src/components/Card/Card.story.jsx
  src/components/Card/Card.test.jsx
  src/components/Card/CardToolbar.jsx
  src/components/Card/__snapshots__/Card.story.storyshot
  src/components/GaugeCard/GaugeCard.story.jsx
  src/components/GaugeCard/__snapshots__/GaugeCard.story.storyshot
  src/components/ValueCard/ValueCard.story.jsx
  src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
  src/constants/CardPropTypes.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1612 feat(suiteheader): add survey notification
  jest.config.js
  src/components/SuiteHeader/SuiteHeader.jsx
  src/components/SuiteHeader/SuiteHeader.story.jsx
  src/components/SuiteHeader/SuiteHeader.test.jsx
  src/components/SuiteHeader/SuiteHeaderLogoutModal/__snapshots__/SuiteHeaderLogoutModal.story.storyshot
  src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
  src/components/SuiteHeader/_suite-header.scss
  src/components/SuiteHeader/hooks/suiteHeaderData.fixture.js
  src/components/SuiteHeader/hooks/useSuiteHeaderData.js
  src/components/SuiteHeader/i18n/index.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1604 fix(chartcards): show actual colors in editable state
  src/components/BarChartCard/barChartUtils.js
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.test.jsx
  src/constants/LayoutConstants.js
Labels: status: ready to merge :tada:

#1619 fix(table): checkbox alignment when expandable rows
  src/components/Table/TableHead/_table-head.scss
Labels: status: ready for review 👀

#1622 feat(suiteheader): Implementation of i18n support and fixing of a redirect issue
  src/components/SuiteHeader/SuiteHeader.jsx
  src/components/SuiteHeader/SuiteHeader.story.jsx
  src/components/SuiteHeader/hooks/suiteHeaderData.fixture.js
  src/components/SuiteHeader/hooks/useSuiteHeaderData.js
Labels: status: ready to merge :tada:

#1608 chore(codeowners): notify core admins of changes to build/test/deploy
  .github/CODEOWNERS
  Staticfile
  manifest.yml
Labels: status: ready to merge :tada:

#1623 chore(repo): enable kodiak
  .kodiak.toml
Labels: status: one more review 👀, status: ready to merge :tada:

#1611 fix(wizardmodal): progessindicator not changing content
  src/components/WizardModal/WizardModal.jsx
  src/components/WizardModal/WizardModal.test.jsx
Labels: status: one more review 👀

#1620 feat(cardeditor): implementation of the card code editor
  .gitignore
  package.json
  src/components/CardCodeEditor/CardCodeEditor.jsx
  src/components/CardCodeEditor/CardCodeEditor.story.jsx
  src/components/CardCodeEditor/CardCodeEditor.test.jsx
  src/components/CardCodeEditor/__snapshots__/CardCodeEditor.story.storyshot
  src/components/CardCodeEditor/_card-code-editor.scss
  src/styles.scss
  yarn.lock
Labels: status: ready to merge 🎉

#1630 fix(table): fixed late loading
  src/components/Table/StatefulTable.jsx
  src/components/Table/StatefulTable.test.jsx
  src/components/Table/Table.story.jsx
  src/components/Table/tableReducer.test.jsx
Labels: status: ready to merge 🎉
