Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2020-07, with the labels that each got.

#1361 fix(TimeSeriesCard): removed rounding and separator in formatter function
  src/components/BarChartCard/BarChartCard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
  src/utils/__tests__/cardUtilityFunctions.test.js
  src/utils/cardUtilityFunctions.js
Labels: status: one more review 👀

#1316 1130 combobox
  .gitignore
  package.json
  src/components/ComboBox/CarbonComboBox.jsx
  src/components/ComboBox/ComboBox.jsx
  src/components/ComboBox/ComboBox.story.jsx
  src/components/ComboBox/ComboBox.test.jsx
  src/components/ComboBox/_combo-box.scss
  src/components/ComboBox/index.js
  src/components/Tag/_tag.scss
  src/index.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge :tada:

#1353 fix(composedmodal): removed double scrollbars
  src/components/ComposedModal/ComposedModal.jsx
  src/components/ComposedModal/ComposedModal.story.jsx
  src/components/ComposedModal/ComposedModal.test.jsx
  src/components/ComposedModal/_composed-modal.scss
  src/styles.scss
Labels: status: ready to merge :tada:

#1368 refactor(styles): removed redundant font-face declarations
  src/styles.scss
Labels: status: ready to merge :tada:

#1365 feat(yarn): changed yarn install to no longer build
  .travis.yml
  package.json
Labels: status: ready to merge :tada:

#1341 chore(testing): eslint rules to improve consistency in testing-library
  .eslintrc
  .github/CONTRIBUTING.MD
  package.json
  src/components/Accordion/AccordionItemDefer.test.jsx
  src/components/BarChartCard/BarChartCard.test.jsx
  src/components/Card/Card.test.jsx
  src/components/Card/CardRangePicker.test.jsx
  src/components/Dashboard/CardRenderer.test.jsx
  src/components/Header/Header.test.jsx
  src/components/Header/HeaderAction/HeaderActionMenu.test.jsx
  src/components/ImageCard/HotspotContent.test.jsx
  src/components/ImageCard/ImageHotspotsRender.test.jsx
  src/components/List/HierarchyList/HierarchyList.test.jsx
  src/components/List/List.test.jsx
  src/components/List/ListHeader/ListHeader.test.jsx
  src/components/List/SimpleList/SimpleList.test.jsx
  src/components/PageWizard/PageWizard.test.jsx
  src/components/PageWizard/StatefulPageWizard.test.jsx
  src/components/Table/Pagination.test.jsx
  src/components/Table/Table.test.jsx
  src/components/Table/TableHead/ColumnHeaderRow/ColumnHeaderRow.test.jsx
  src/components/Table/TableSaveViewModal/TableSaveViewModal.test.jsx
  src/components/TableCard/TableCard.test.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.test.jsx
  yarn.lock
Labels: status: failing CI :no_good_man:, status: ready to merge :tada:, type: enhancement :bulb:

#1389 fix(table): TableToolbarSearch rerenders when defaultValue is modified
  src/components/Table/Table.test.jsx
  src/components/Table/TableToolbar/TableToolbar.jsx
Labels: status: ready for review 👀

#1387 Table filter numbers and booleans
  src/components/Table/tableReducer.js
Labels: status: one more review 👀

#1399 fix(proptypes): relax proptypes errors on pagewizard
  src/components/List/ListItem/ListItem.jsx
  src/components/PageWizard/PageWizardStep/PageWizardStep.jsx
  src/components/PageWizard/StatefulPageWizard.jsx
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: one more review 👀

#1359 feat(linting): Improve sass linting using stylelint and a custom formatter
  config/stylelint/sassMsgFormatter.js
  config/stylelint/sassMsgFormatter.test.js
  package.json
  src/components/GaugeCard/_gauge-card.scss
  src/components/Header/_header.scss
  src/components/SideNav/SideNav.story.scss
  src/components/SideNav/_side-nav.scss
  src/components/TableCard/_table-card.scss
  src/components/TileCatalog/_catalog-content.scss
  src/components/TileCatalog/_tile-group.scss
  src/components/TileCatalogNew/_tile-catalog.scss
  src/components/TileGallery/_tile-gallery.scss
  src/components/WizardModal/_wizard-modal.scss
  yarn.lock
Labels: status: ready to merge :tada:

#1384 Create SECURITY.md
  SECURITY.md
Labels: status: one more review 👀

#1367 TileCatalog and Pagination RTL fixes
  src/components/SimplePagination/SimplePagination.jsx
  src/components/SimplePagination/__snapshots__/SimplePagination.story.storyshot
  src/components/SimplePagination/_simple-pagination.scss
  src/components/TileCatalog/__snapshots__/TileCatalog.story.storyshot
  src/components/TileCatalog/_tile-catalog.scss
Labels: status: ready to merge :tada:

#1394 [Combobox]: add default props for onChange and onInputChange
  SECURITY.md
  src/components/ComboBox/ComboBox.jsx
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1396 fix(tests): defer loading acessibility-checker package
  config/jest/setupTest.js
  package.json
  yarn.lock
Labels: severity: 1 :rotating_light:, status: ready to merge :tada:, type: bug :bug:

#1357 [Table] Fix RTL issues with row action overflow menu
  package.json
  src/components/Table/Table.jsx
  src/components/Table/Table.test.jsx
  src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
  src/components/Table/TableBody/TableBody.jsx
  src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge :tada:

#1402 fix(dashboardgrid): upgrade react-grid-layout, fix card proptypes
  package.json
  src/components/Dashboard/DashboardGrid.jsx
  src/components/Dashboard/DashboardGrid.story.jsx
  src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  src/constants/CardPropTypes.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: one more review 👀, status: ready for review 👀

#1405 fix(timeseriescard): use data label in table headers
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.test.jsx
  src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready for code owner's review, status: ready for review 👀

#1415 fix(sassformatter): title was undefined
  config/stylelint/sassMsgFormatter.js
Labels: severity: 3, status: ready for review 👀, type: bug :bug:

#1310 fix(deps): updated use-resize-observer dependency
  package.json
  src/components/Breadcrumb/Breadcrumb.jsx
  src/internal/UseResizeObserver.jsx
  yarn.lock
Labels: dependencies

#1427 update links to new github organization
  .github/CONTRIBUTING.MD
  README.MD
  config/jest/setupTest.js
  docs/guides/testing.md
  docs/guides/versioning.md
  package.json
Labels: status: ready to merge :tada:

#1418 Single import of @testing-library/jest-dom
  .eslintrc
  config/jest/setupTest.js
  src/components/ComposedModal/ComposedModal.test.jsx
  src/components/Header/Header.test.jsx
  src/components/Header/HeaderAction/HeaderActionMenu.test.jsx
  src/components/List/HierarchyList/HierarchyList.test.jsx
  src/components/List/ListItem/ListItem.test.jsx
  src/components/List/SimpleList/SimpleList.test.jsx
  src/components/Table/StatefulTable.test.jsx
  src/components/Table/TableSaveViewModal/TableSaveViewModal.test.jsx
  src/components/Table/TableViewDropdown/TableViewDropdown.test.jsx
  src/components/TableCard/TableCard.test.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.test.jsx
Labels: status: ready to merge :tada:

#1369 Iot progress indicator
  src/components/PageWizard/PageWizard.jsx
  src/components/PageWizard/PageWizard.story.jsx
  src/components/PageWizard/PageWizard.test.jsx
  src/components/PageWizard/StatefulPageWizard.jsx
  src/components/PageWizard/StatefulPageWizard.test.jsx
  src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
  src/components/ProgressIndicator/ProgressIndicator.jsx
  src/components/ProgressIndicator/ProgressIndicator.story.jsx
  src/components/ProgressIndicator/ProgressIndicator.test.jsx
  src/components/ProgressIndicator/__snapshots__/ProgressIndicator.story.storyshot
  src/components/ProgressIndicator/_progress-indicator.scss
  src/components/ProgressIndicator/index.js
  src/components/Table/TableDetailWizard/StatefulTableDetailWizard.jsx
  src/components/Table/TableDetailWizard/StatefulTableDetailWizard.test.jsx
  src/components/Table/TableDetailWizard/TableDetailWizard.jsx
  src/components/Table/TableDetailWizard/TableDetailWizard.story.jsx
  src/components/Table/TableDetailWizard/TableDetailWizard.test.jsx
  src/components/Table/TableDetailWizard/TableDetailWizardSidebar/TableDetailWizardSidebar.jsx
  src/components/Table/TableDetailWizard/__snapshots__/TableDetailWizard.story.storyshot
  src/components/WizardInline/StatefulWizard.test.jsx
  src/components/WizardInline/WizardHeader/WizardHeader.jsx
  src/components/WizardInline/WizardInline.jsx
  src/components/WizardInline/WizardInline.story.jsx
  src/components/WizardInline/WizardInline.test.jsx
  src/components/WizardInline/__snapshots__/WizardInline.story.storyshot
  src/components/WizardModal/WizardModal.jsx
  src/components/WizardModal/WizardModal.story.jsx
  src/components/WizardModal/WizardModal.test.jsx
  src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1420 fix(table): column resize failing for initially hidden column with un…
  src/components/Table/TableHead/TableHead.test.jsx
  src/components/Table/TableHead/columnWidthUtilityFunctions.js
Labels: status: ready to merge :tada:

#1422 fix(bug): fixed duplicate error messages
  config/stylelint/sassMsgFormatter.js
  config/stylelint/sassMsgFormatter.test.js
Labels: status: ready to merge :tada:

#1411 StatefulTable find rowAction for nested rows
  config/jest/setup.js
  src/components/Table/StatefulTable.jsx
  src/components/Table/StatefulTable.test.jsx
  src/components/Table/Table.story.jsx
Labels: status: one more review 👀

#1439 TableDetailWizard RTL fix
  src/components/Table/TableDetailWizard/TableDetailWizardHeader/_table-detail-wizard-header.scss
  src/components/Table/TableDetailWizard/TableDetailWizardSidebar/_table-detail-wizard-sidebar.scss
  src/components/Table/TableDetailWizard/_table-detail-wizard.scss
Labels: status: one more review 👀

#1397 Add tests for i18n strings to ensure they appear on the DOM
  src/components/BarChartCard/BarChartCard.test.jsx
  src/components/DateTimePicker/DateTimePicker.test.jsx
  src/components/FlyoutMenu/FlyoutMenu.test.jsx
  src/components/ImageCard/ImageHotspots.test.jsx
  src/components/List/ListHeader/ListHeader.test.jsx
  src/components/List/ListItem/ListItem.test.jsx
  src/components/PageTitleBar/PageTitleBar.test.jsx
  src/components/PageWizard/PageWizard.test.jsx
  src/components/Table/Table.test.jsx
  src/components/Table/TableSaveViewModal/TableSaveViewModal.test.jsx
  src/components/Table/TableViewDropdown/TableViewDropdown.test.jsx
  src/components/TileCatalogNew/TileCatalogNew.test.jsx
Labels: status: ready to merge :tada:

#1425 Add priority label to issue templates
  .github/ISSUE_TEMPLATE/feature-request-or-enhancement.md
  .github/ISSUE_TEMPLATE/new-component-proposal.md
Labels: status: ready to merge :tada:, type: enhancement :bulb:, type: repo/dx :computer:

#1430 Update carbon charts
  package.json
  src/components/BarChartCard/BarChartCard.story.jsx
  src/components/BarChartCard/__snapshots__/BarChartCard.story.storyshot
  src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
  src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  yarn.lock
Labels: status: one more review 👀

#1449 fix(table): pass filteredData to onDownloadCsv
  src/components/BarChartCard/BarChartCard.jsx
  src/components/Table/Table.jsx
  src/components/Table/Table.story.jsx
  src/components/Table/TableToolbar/TableToolbar.jsx
  src/components/TableCard/TableCard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready for review 👀
