Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2020-11, with the labels that each got.

#1744 fix(DashboardEditor): selection styling and custom card rendering
  .storybook/__snapshots__/Welcome.story.storyshot
  src/components/Card/_card.scss
  src/components/CardEditor/CardEditForm/CardEditForm.jsx
  src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
  src/components/CardEditor/CardEditForm/CardEditFormContent.test.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.test.jsx
  src/components/CardEditor/CardEditForm/CardEditFormSettings.jsx
  src/components/CardEditor/CardEditForm/CardEditFormSettings.test.jsx
  src/components/CardEditor/CardEditor.jsx
  src/components/CardEditor/CardEditor.story.jsx
  src/components/CardEditor/CardEditor.test.jsx
  src/components/CardEditor/CardGalleryList/CardGalleryList.jsx
  src/components/DashboardEditor/DashboardEditor.jsx
  src/components/DashboardEditor/DashboardEditor.story.jsx
  src/components/DashboardEditor/DashboardEditor.test.jsx
  src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  src/components/DashboardEditor/_dashboard-editor.scss
  src/components/DashboardEditor/editorUtils.jsx
  src/icons/components/CustomCardIcon.jsx
  src/icons/components/index.jsx
  src/icons/svg/custom-card-icon.svg
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: one more review 👀

#1749 1621 card selection
  src/components/Card/Card.jsx
  src/components/Card/Card.story.jsx
  src/components/Card/__snapshots__/Card.story.storyshot
  src/components/Card/_card.scss
Labels: status: one more review 👀

#1751 feat(DashboardEditor): add breakpoint switcher
  src/components/Card/_card.scss
  src/components/Dashboard/DashboardGrid.jsx
  src/components/Dashboard/DashboardGrid.test.jsx
  src/components/DashboardEditor/DashboardEditor.jsx
  src/components/DashboardEditor/DashboardEditor.story.jsx
  src/components/DashboardEditor/DashboardEditor.test.jsx
  src/components/DashboardEditor/DashboardEditorHeader/DashboardEditorHeader.jsx
  src/components/DashboardEditor/DashboardEditorHeader/__snapshots__/DashboardEditorHeader.story.storyshot
  src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  src/components/DashboardEditor/_dashboard-editor.scss
  src/components/DashboardEditor/editorUtils.jsx
  src/components/DashboardEditor/editorUtils.test.jsx
  src/components/FileDrop/__snapshots__/FileDrop.story.storyshot
  src/components/IconSwitch/IconSwitch.jsx
  src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  src/components/ValueCard/ValueCard.jsx
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready for code owner's review

#1759 fix(card-editor): show ids in data series
  src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.test.jsx
Labels: status: one more review 👀

#1755 feat(header): added ability to update aria-labels via i18n props
  src/components/Header/Header.jsx
  src/components/Header/Header.story.jsx
  src/components/Header/__snapshots__/Header.story.storyshot
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1775 fix(dashboardeditor): create onLayoutChange callback and pass layouts to grid
  src/components/DashboardEditor/DashboardEditor.jsx
  src/components/DashboardEditor/DashboardEditor.story.jsx
  src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1776 fix(barchart): handle null data correctly when we do have series
  src/components/BarChartCard/BarChartCard.jsx
  src/components/BarChartCard/barChartUtils.js
  src/components/BarChartCard/barChartUtils.test.js
Labels: status: ready to merge 🎉

#1777 fix(dashboardeditor): add loading state
  src/components/DashboardEditor/DashboardEditor.jsx
  src/components/DashboardEditor/DashboardEditor.story.jsx
  src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1748 chore(charts): upgrade carbon charts to latest version and needs new color options
  .vscode/launch.json
  package.json
  src/components/BarChartCard/barChartUtils.js
  src/components/BarChartCard/barChartUtils.test.js
  src/components/PieChartCard/PieChartCard.jsx
  src/components/PieChartCard/PieChartCard.test.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.test.jsx
  src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  src/constants/CardPropTypes.js
  yarn.lock
Labels: status: ready to merge 🎉

#1780 feat(table-card): add multiselect filter to threshold columns
  src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  src/components/TableCard/TableCard.jsx
  src/components/TableCard/__snapshots__/TableCard.story.storyshot
Labels: status: ready to merge 🎉

#1789 fix(table): fixed left alignment of table headers
  src/components/DataTable/_data-table.scss
Labels: status: ready to merge 🎉

#1794 fix(hierarchylist): need to useDeepCompareEffect to stop infinite loop
  src/components/List/HierarchyList/HierarchyList.jsx
  src/components/List/List.jsx
Labels: status: ready to merge 🎉

#1798 Hotfix to Master -- fix(hierarchylist): need to useDeepCompareEffect to stop infinite loop
  src/components/List/HierarchyList/HierarchyList.jsx
  src/components/List/List.jsx
Labels: status: ready to merge 🎉

#1802 Hotfix to Master -- fix(table): fixed left alignment of table headers
  src/components/DataTable/_data-table.scss
Labels: status: ready to merge 🎉

#1788 chore(release): disable Travis CI, enable Publish GH action workflow
  .github/workflows/publish.yml
  .travis.yml
Labels: status: one more review 👀

#1790 Add translated strings for timerange labels
  src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.test.jsx
Labels: status: ready for code owner's review

#1805 Hotifix to Master -- chore(release): disable Travis CI, enable Publish GH action workflow
  .github/workflows/publish.yml
  .travis.yml
Labels: status: ready to merge 🎉

#1736 fix(basetablereducer): fix selecting unselectable items
  src/components/Table/StatefulTable.test.jsx
  src/components/Table/baseTableReducer.js
Labels: status: ready to merge 🎉

#1804 patch to master -- fix(listitem): need to support render function
  src/components/List/ListItem/ListItem.jsx
  src/components/List/ListItem/_list-item.scss
Labels: patch to master, status: waiting for author's response 💬

#1781 fix(dragndrop): fixed expand icon
  src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  src/components/List/ListItem/ListItem.jsx
  src/components/List/ListItem/ListItem.story.jsx
  src/components/List/ListItem/ListItem.test.jsx
  src/components/List/ListItem/ListItemWrapper.jsx
  src/components/List/ListItem/_list-item.scss
  src/components/List/SimpleList/SimpleList.test.jsx
  src/components/List/SimpleList/__snapshots__/SimpleList.story.storyshot
Labels: status: ready to merge 🎉

#1807 fix(listitem): rowActions should be null by default
  src/components/List/ListItem/ListItem.jsx
Labels: patch to master, status: one more review 👀

#1757 feat(suiteheader) Separating data fetching logic in a util function.
  .storybook/__snapshots__/Welcome.story.storyshot
  jest.config.js
  src/components/SuiteHeader/SuiteHeader.story.jsx
  src/components/SuiteHeader/hooks/useSuiteHeaderData.js
  src/components/SuiteHeader/util/suiteHeaderData.fixture.js
  src/components/SuiteHeader/util/suiteHeaderData.js
  src/index.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1809 chore(repo): clean up remaining references to Travis CI
  .github/CODEOWNERS
  README.MD
Labels: status: ready to merge 🎉

#1783 Support and test for SSR
  .vscode/launch.json
  config/jest/setup.js
  src/components/Header/HeaderAction/HeaderActionMenu.jsx
  src/components/Header/HeaderAction/HeaderActionPanel.jsx
  src/components/List/ListItem/ListItem.jsx
  src/utils/__tests__/ssr.test.js
Labels: status: ready to merge 🎉

#1814 fix(listitem): fix row actions issue
  src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.jsx
  src/components/List/ListItem/ListItem.jsx
  src/components/List/ListItem/ListItem.story.jsx
  src/components/List/ListItem/__snapshots__/ListItem.story.storyshot
  src/components/List/ListItem/_list-item.scss
Labels: status: ready to merge 🎉

#1816 fix(hierarchylist): selection is lost when rerender occurs
  src/components/List/HierarchyList/HierarchyList.jsx
  src/components/List/ListItem/ListItem.jsx
  src/components/List/ListItem/_list-item.scss
Labels: status: ready to merge 🎉

#1813 feat(imagehotspots): add selecting and creating hotspots
  src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  src/components/ImageCard/Hotspot.jsx
  src/components/ImageCard/ImageHotspots.jsx
  src/components/ImageCard/ImageHotspots.story.jsx
  src/components/ImageCard/ImageHotspots.test.jsx
  src/components/ImageCard/ImageHotspotsRender.test.jsx
  src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
  src/components/ImageCard/__snapshots__/ImageHotspots.story.storyshot
  src/components/ImageCard/_hotspot.scss
  src/styles.scss
Labels: status: ready to merge 🎉

#1796 [ImageCard] add upload capabilities
  jest.config.js
  src/components/CardEditor/CardEditForm/CardEditForm.jsx
  src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem/DataSeriesFormItem.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem/DataSeriesFormItem.test.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItem/ImageCardFormItem.jsx
  src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  src/components/DashboardEditor/DashboardEditor.jsx
  src/components/DashboardEditor/editorUtils.jsx
  src/components/ImageCard/ImageCard.jsx
  src/components/ImageCard/ImageCard.story.jsx
  src/components/ImageCard/ImageHotspots.jsx
  src/components/ImageCard/ImageUploader.jsx
  src/components/ImageCard/ImageUploader.test.jsx
  src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
  src/components/ImageCard/__snapshots__/ImageHotspots.story.storyshot
  src/components/ImageCard/_image-uploader.scss
  src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  src/constants/CardPropTypes.js
  src/constants/LayoutConstants.js
  src/styles.scss
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  src/utils/cardUtilityFunctions.js
Labels: status: ready to merge 🎉

#1820 Hotfix hierarchy list
  src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItem.jsx
  src/components/List/HierarchyList/HierarchyList.jsx
  src/components/List/ListItem/ListItem.jsx
  src/components/List/ListItem/ListItem.story.jsx
  src/components/List/ListItem/__snapshots__/ListItem.story.storyshot
  src/components/List/ListItem/_list-item.scss
Labels: patch to master, status: ready to merge 🎉

#1782 fix(table): prevent comparison of props of type element/node
  src/components/Table/StatefulTable.jsx
  src/components/Table/Table.jsx
Labels: severity: 2, status: one more review 👀, type: bug :bug:

#1832 fix(cardEditForm): not using passed timeRange prop in the form
  src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
  src/components/CardEditor/CardEditForm/CardEditFormContent.test.jsx
  src/components/CardEditor/CardEditForm/CardEditFormSettings.test.jsx
  src/components/DashboardEditor/editorUtils.jsx
Labels: status: ready to merge 🎉

#1833 fix(cardEditor): the showLegend was in the incorrect place for TimeSeriesCards
  src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormSettings.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormContent.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormSettings.jsx
  src/components/CardEditor/CardEditForm/CardEditFormSettings.jsx
  src/components/CardEditor/CardEditor.jsx
  src/components/DashboardEditor/editorUtils.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1835 Upgrade carbon charts
  __mocks__/@carbon/charts-react/bar-chart-grouped.js
  __mocks__/@carbon/charts-react/bar-chart-simple.js
  __mocks__/@carbon/charts-react/bar-chart-stacked.js
  __mocks__/@carbon/charts-react/line-chart.js
  __mocks__/@carbon/charts-react/pie-chart.js
  jest.config.js
  package.json
  src/components/BarChartCard/BarChartCard.test.jsx
  src/components/BarChartCard/__snapshots__/BarChartCard.story.storyshot
  src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  src/components/PieChartCard/PieChartCard.test.jsx
  src/components/PieChartCard/__snapshots__/PieChartCard.story.storyshot
  src/components/TimeSeriesCard/TimeSeriesCard.test.jsx
  src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  yarn.lock
Labels: status: one more review 👀, status: ready for code owner's review, status: ready for review 👀

#1836 feat(imagegallerymodal): new component created to select an image
  .storybook/__snapshots__/Welcome.story.storyshot
  src/components/IconSwitch/_icon-switch.scss
  src/components/ImageGalleryModal/ImageGalleryModal.jsx
  src/components/ImageGalleryModal/ImageGalleryModal.story.jsx
  src/components/ImageGalleryModal/ImageGalleryModal.test.jsx
  src/components/ImageGalleryModal/ImageTile.jsx
  src/components/ImageGalleryModal/__snapshots__/ImageGalleryModal.story.storyshot
  src/components/ImageGalleryModal/_image-gallery-modal.scss
  src/components/ImageGalleryModal/_image-tile.scss
  src/components/ImageGalleryModal/images/Manufacturing_plant.png
  src/components/ImageGalleryModal/images/assemblyline.jpg
  src/components/ImageGalleryModal/images/extra-wide-image.png
  src/components/ImageGalleryModal/images/floow_plan.png
  src/components/ImageGalleryModal/images/large.png
  src/components/ImageGalleryModal/images/large_portrait.png
  src/components/ImageGalleryModal/images/robot_arm.png
  src/components/ImageGalleryModal/images/tankmodal.png
  src/components/ImageGalleryModal/images/turbines.png
  src/index.js
  src/styles.scss
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1830 fix(TableCard): format timestamps in expanded rows
  .storybook/__snapshots__/Welcome.story.storyshot
  src/components/ImageCard/HotspotContent.jsx
  src/components/List/ListHeader/ListHeader.jsx
  src/components/TableCard/TableCard.jsx
  src/components/TableCard/TableCard.story.jsx
  src/components/TableCard/TableCard.test.jsx
  src/components/TableCard/__snapshots__/TableCard.story.storyshot
  src/components/TableCard/tableCardUtils.jsx
  src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
  src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  src/constants/CardPropTypes.js
  src/index.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  src/utils/__tests__/cardUtilityFunctions.test.jsx
  src/utils/cardUtilityFunctions.js
Labels: status: ready to merge 🎉
