Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2020-06, with the labels that each got.

#1237 feat(datetime picker): hide time inputs
  src/components/DateTimePicker/DateTimePicker.jsx
  src/components/DateTimePicker/DateTimePicker.story.jsx
  src/components/DateTimePicker/_date-time-picker.scss
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1256 fix(tilecatalognew): console warnings
  src/components/TileCatalogNew/TileCatalogNew.jsx
  src/components/TileCatalogNew/TilePagination/TilePagination.jsx
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1258 fix(issuetemplate): update labels
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request-or-enhancement.md
  .github/ISSUE_TEMPLATE/new-component-proposal.md
  .github/ISSUE_TEMPLATE/question.md
Labels: status: one more review 👀

#1270 fix(icons): proper import paths
  examples/codesandbox/package.json
  src/components/AddCard/AddCard.jsx
  src/components/Card/CardRangePicker.jsx
  src/components/ComposedStructuredList/ComposedStructuredList.jsx
  src/components/Header/Header.jsx
  src/components/Header/Header.test.jsx
  src/components/Header/HeaderAction/HeaderActionMenu.jsx
  src/components/Header/HeaderAction/__snapshots__/HeaderActionMenu.test.jsx.snap
  src/components/Header/__snapshots__/Header.test.jsx.snap
  src/components/Hero/Hero.jsx
  src/components/IconSwitch/IconSwitch.test.jsx
  src/components/ImageCard/ImageCard.jsx
  src/components/ResourceList/ResourceList.story.jsx
  src/components/ResourceList/ResourceList.test.jsx
  src/components/SideNav/SideNav.test.jsx
  src/components/SimplePagination/SimplePagination.jsx
  src/components/Table/EmptyTable/EmptyTable.jsx
  src/components/Table/TableBody/RowActionsCell/RowActionsError.jsx
  src/components/Table/TableDetailWizard/TableDetailWizardHeader/TableDetailWizardHeader.jsx
  src/components/Table/TableHead/ColumnHeaderSelect/ColumnHeaderSelect.jsx
  src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
  src/components/TableCard/TableCard.jsx
  src/components/TileCatalog/TileCatalog.jsx
  src/components/TileCatalogNew/TileCatalogNew.jsx
Labels: status: one more review 👀, type: bug :bug:

#1245 feat(button): add icon selection button
  src/components/Button/Button.jsx
  src/components/Button/Button.story.jsx
  src/components/Button/Button.test.jsx
  src/components/Button/__snapshots__/Button.story.storyshot
  src/components/Button/_button.scss
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: visual review 🔍

#1292 fix(node): specify correct version in engines, require 12 for local dev
  package.json
Labels: type: bug :bug:

#1293 feat(deps): added unicorn and no-abusive-eslint-disable rule
  .eslintrc
  package.json
  src/a11y/a11y-test-helper.jsx
  src/components/AddCard/AddCard.test.a11y.jsx
  src/components/Button/Button.jsx
  src/components/Button/Button.test.a11y.jsx
  src/components/Card/Card.jsx
  src/components/Card/Card.story.jsx
  src/components/Dashboard/CardRenderer.jsx
  src/components/Dashboard/Dashboard.jsx
  src/components/FileDrop/FileDrop.jsx
  src/components/GaugeCard/GaugeCard.jsx
  src/components/Header/Header.story.jsx
  src/components/Header/HeaderAction/HeaderAction.jsx
  src/components/Header/HeaderAction/HeaderActionMenu.jsx
  src/components/Header/HeaderAction/HeaderActionPanel.jsx
  src/components/ImageCard/ImageCard.jsx
  src/components/ImageCard/ImageHotspots.jsx
  src/components/List/HierarchyList/HierarchyList.jsx
  src/components/List/ListItem/ListItem.jsx
  src/components/ListCard/ListCard.story.jsx
  src/components/Page/PageHero.jsx
  src/components/ResourceList/ResourceList.jsx
  src/components/SideNav/SideNav.story.jsx
  src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
  src/components/Table/TableBody/RowActionsCell/RowActionsError.jsx
  src/components/Table/TableBody/TableBody.jsx
  src/components/Table/TableHead/ColumnHeaderSelect/ColumnHeaderSelect.jsx
  src/components/Table/TableHead/ColumnResize.jsx
  src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
  src/components/Table/TablePropTypes.js
  src/components/Table/TableSkeletonWithHeaders/TableSkeletonWithHeaders.jsx
  src/components/Table/TableToolbar/TableToolbar.jsx
  src/components/Table/tableReducer.js
  src/components/TableCard/TableCard.jsx
  src/components/TileCatalog/TileCatalog.story.jsx
  src/components/TileCatalogNew/TileCatalogNew.story.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/components/TimeSeriesCard/timeSeriesUtils.js
  src/components/ValueCard/Attribute.jsx
  src/components/ValueCard/UnitRenderer.jsx
  src/components/ValueCard/ValueRenderer.jsx
  src/components/WizardModal/WizardModal.jsx
  src/internal/FullWidthWrapper.jsx
  src/internal/deprecate.js
  src/utils/componentUtilityFunctions.js
  src/utils/sample.jsx
  yarn.lock
Labels: status: ready to merge :tada:

#1254 feat(datetime picker): new func prop for tooltip value
  src/components/DateTimePicker/DateTimePicker.jsx
  src/components/DateTimePicker/DateTimePicker.test.jsx
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1269 fix(card): ux show tooltips over the card actions and use carbon buttons
  src/components/BarChartCard/__snapshots__/BarChartCard.story.storyshot
  src/components/Card/Card.jsx
  src/components/Card/Card.story.jsx
  src/components/Card/CardRangePicker.jsx
  src/components/Card/CardRangePicker.test.jsx
  src/components/Card/CardToolbar.jsx
  src/components/Card/__snapshots__/Card.story.storyshot
  src/components/Card/_card-range-picker.scss
  src/components/Dashboard/Dashboard.jsx
  src/components/Dashboard/Dashboard.story.jsx
  src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
  src/components/List/ListItem/ListItem.story.jsx
  src/components/List/SimpleList/SimpleList.story.jsx
  src/components/TableCard/TableCard.jsx
  src/components/TableCard/__snapshots__/TableCard.story.storyshot
  src/components/TileGallery/TileGallery.story.jsx
  src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  src/constants/CardPropTypes.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1278 fix(card): avoid clipping data state renderer error tooltip
  src/components/Card/DataStateRenderer.jsx
  src/components/ValueCard/ValueCard.story.jsx
  src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
  src/constants/CardPropTypes.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready for code owner's review

#1281 feat(card): allow each card to have its own defaultLabel
  src/components/Card/CardRangePicker.jsx
  src/components/Dashboard/CardRenderer.jsx
  src/components/Dashboard/Dashboard.jsx
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1300 Fix(Header): appSwitcherLabel prop added
  src/components/Header/Header.jsx
  src/components/Header/Header.story.jsx
  src/components/Header/__snapshots__/Header.story.storyshot
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1305 Limit width on long ListItem values with rowActions
  src/components/List/ListItem/ListItem.jsx
  src/components/List/ListItem/ListItem.story.jsx
  src/components/List/ListItem/ListItem.test.jsx
  src/components/List/ListItem/_list-item.scss
Labels: status: ready to merge :tada:

#1289 feat(timeseries): allow timeseries to show times in GMT
  .github/CODEOWNERS
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.test.jsx
  src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  src/components/TimeSeriesCard/timeSeriesUtils.js
  src/constants/CardPropTypes.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1296 1282 table manage views dropdown
  .storybook/__snapshots__/Welcome.story.storyshot
  src/components/Table/TableViewDropdown/TableViewDropdown.jsx
  src/components/Table/TableViewDropdown/TableViewDropdown.story.jsx
  src/components/Table/TableViewDropdown/TableViewDropdown.test.jsx
  src/components/Table/TableViewDropdown/TableViewDropdownItem.jsx
  src/components/Table/TableViewDropdown/TableViewItemPropTypes.js
  src/components/Table/TableViewDropdown/__snapshots__/TableViewDropdown.story.storyshot
  src/components/Table/TableViewDropdown/_table-view-dropdown.scss
  src/index.js
  src/styles.scss
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: one more review 👀

#1290 feat(timeseriescard): allow custom tooltip date formats
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1311 fix(list): replaced filterdeep with somedeep
  package.json
  src/components/List/List.story.jsx
  yarn.lock
Labels: status: ready to merge :tada:

#1309 fix(image-hotspot): removed unused props
  src/components/ImageCard/Hotspot.jsx
  src/components/ImageCard/ImageHotspots.jsx
Labels: status: ready to merge :tada:

#1322 add 'needs triage' label to issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request-or-enhancement.md
  .github/ISSUE_TEMPLATE/new-component-proposal.md
  .github/ISSUE_TEMPLATE/question.md
Labels: status: ready to merge :tada:

#1334 fix(filterheaderrow): fix regression with clear filters
  src/components/Table/StatefulTable.test.jsx
  src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
  src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.test.jsx
Labels: status: WIP :woman_technologist:

#1326 feat(classnames): updated classnames import for a consistent import name
  src/components/AddCard/AddCard.jsx
  src/components/Button/Button.jsx
  src/components/Card/Card.jsx
  src/components/Card/CardRangePicker.jsx
  src/components/Card/CardToolbar.jsx
  src/components/ComposedModal/ComposedModal.jsx
  src/components/Header/HeaderAction/HeaderActionMenu.jsx
  src/components/Header/HeaderAction/HeaderActionPanel.jsx
  src/components/IconSwitch/IconSwitch.jsx
  src/components/ListCard/ListCard.jsx
  src/components/PageTitleBar/PageTitleBar.jsx
  src/components/PageWizard/PageWizard.jsx
  src/components/Table/Table.jsx
  src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
  src/components/Table/TableHead/ColumnHeaderSelect/ColumnHeaderSelect.jsx
  src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
  src/components/Table/TableHead/TableHeader.js
  src/components/Table/TableToolbar/TableToolbar.jsx
  src/components/Table/TableToolbar/TableToolbarSVGButton.jsx
  src/components/TileCatalog/TileCatalog.jsx
  src/components/TileCatalog/TileGroup.jsx
  src/components/ValueCard/Attribute.jsx
  src/components/ValueCard/UnitRenderer.jsx
  src/components/ValueCard/ValueRenderer.jsx
  src/components/WizardModal/WizardModal.jsx
Labels: status: waiting for author's response 💬

#1333 deprecate Dashboard, CardRenderer
  .storybook/__snapshots__/Welcome.story.storyshot
  src/components/Dashboard/CardRenderer.jsx
  src/components/Dashboard/Dashboard.jsx
  src/components/Dashboard/Dashboard.story.jsx
  src/components/Dashboard/DashboardHeader.story.jsx
  src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  src/components/Dashboard/__snapshots__/DashboardHeader.story.storyshot
  src/index.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: one more review 👀, status: ready for code owner's review

#1315 fix(rowactioncell): change action color
  src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
  src/components/Table/TableBody/RowActionsCell/_row-actions-cell.scss
  src/components/Table/TableBody/TableBodyRow/__snapshots__/TableBodyRow.story.storyshot
Labels: status: ready for code owner's review

#1339 (BarChartCard / TimeSeriesCard) domain range functionality
  package.json
  src/components/BarChartCard/BarChartCard.jsx
  src/components/BarChartCard/BarChartCard.story.jsx
  src/components/Dashboard/Dashboard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
  src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  src/constants/CardPropTypes.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  src/utils/sample.jsx
  yarn.lock
Labels: status: ready for review 👀

#1335 877 page wizard step validation
  src/components/PageWizard/PageWizard.story.jsx
  src/components/PageWizard/StatefulPageWizard.jsx
  src/components/PageWizard/StatefulPageWizard.test.jsx
Labels: status: ready to merge :tada:

#1336 fix(simplelist): SimpleList items are now deselectable
  src/components/List/SimpleList/SimpleList.jsx
  src/components/List/SimpleList/SimpleList.test.jsx
Labels: status: ready to merge :tada:

#1337 test(accessibility): migrate to new `accessibility-checker` package
  .eslintrc
  achecker.js
  config/jest/setupTest.js
  config/testHelpers.js
  package.json
  src/a11y/a11y-test-helper.jsx
  src/components/AddCard/AddCard.test.a11y.jsx
  src/components/Button/Button.test.a11y.jsx
  src/components/PageTitleBar/PageTitleBar.jsx
  src/components/PageTitleBar/PageTitleBar.story.jsx
  src/components/PageTitleBar/PageTitleBar.test.a11y.jsx
  src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
  src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge :tada:

#1348 feat(table): Save view modal
  .storybook/__snapshots__/Welcome.story.storyshot
  .storybook/story-styles.scss
  src/components/Accordion/__snapshots__/AccordionItemDefer.story.storyshot
  src/components/Table/TableSaveViewModal/TableSaveViewForm.jsx
  src/components/Table/TableSaveViewModal/TableSaveViewModal.jsx
  src/components/Table/TableSaveViewModal/TableSaveViewModal.story.jsx
  src/components/Table/TableSaveViewModal/TableSaveViewModal.test.jsx
  src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  src/components/Table/TableSaveViewModal/table-save-view-modal.scss
  src/components/Table/TableViewDropdown/TableViewDropdown.jsx
  src/constants/SharedPropTypes.js
  src/index.js
  src/styles.scss
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:, status: visual review 🔍
