Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2020-08, with the labels that each got.

#1454 feat(TimeSeriesCard/BarChartCard): add zoomBar functionality
  package.json
  src/components/BarChartCard/BarChartCard.jsx
  src/components/BarChartCard/BarChartCard.story.jsx
  src/components/BarChartCard/__snapshots__/BarChartCard.story.storyshot
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
  src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  src/constants/CardPropTypes.js
  src/constants/LayoutConstants.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge :tada:

#1467 fix(carbon-charts): update to get zoombar bug fix
  package.json
  yarn.lock
Labels: status: one more review 👀

#1468 fix(flyoutmenu): add export to index.js
  .storybook/__snapshots__/Welcome.story.storyshot
  src/components/FlyoutMenu/index.js
  src/index.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: severity: 1 :rotating_light:, status: one more review 👀, type: bug :bug:

#1472 fix(modal): prop types support to node #1471
  src/components/ComposedModal/ComposedModal.jsx
  src/components/ComposedModal/ComposedModal.story.jsx
  src/components/ComposedModal/__snapshots__/ComposedModal.story.storyshot
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready for review 👀

#1477 feat(catalogcontent): allow description to be node
  src/components/TileCatalog/CatalogContent.jsx
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: one more review 👀

#1474 fix(BarChartCard/TimeSeriesCard): enable zoomBar when isExpanded is true
  src/components/BarChartCard/BarChartCard.jsx
  src/components/BarChartCard/BarChartCard.story.jsx
  src/components/BarChartCard/__snapshots__/BarChartCard.story.storyshot
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
Labels: status: one more review 👀, status: visual review 🔍

#1486 feat(CardRangePicker): allow for custom time range options
  src/components/Card/Card.jsx
  src/components/Card/Card.story.jsx
  src/components/Card/CardRangePicker.jsx
  src/components/Card/CardRangePicker.test.jsx
  src/components/Card/CardToolbar.jsx
  src/components/Card/__snapshots__/Card.story.storyshot
  src/constants/CardPropTypes.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1490 feat(zoombar): enable simple slider view
  package.json
  src/components/BarChartCard/BarChartCard.jsx
  src/components/BarChartCard/BarChartCard.story.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
  src/constants/CardPropTypes.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: one more review 👀, status: ready for code owner's review

#1496 fix(hierarchy-list): add prop for hierarchy menus
  src/components/List/HierarchyList/HierarchyList.story.jsx
  src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  src/components/List/List.jsx
  src/components/List/ListItem/_list-item.scss
  src/components/List/__snapshots__/List.story.storyshot
Labels: status: one more review 👀

#1519 feat(listitem): add tags
  src/components/List/List.jsx
  src/components/List/List.story.jsx
  src/components/List/ListItem/ListItem.jsx
  src/components/List/ListItem/ListItem.story.jsx
  src/components/List/ListItem/ListItem.test.jsx
  src/components/List/__snapshots__/List.story.storyshot
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: one more review 👀

#1529 fix(TimeSeriesCard): don't filter null values
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
Labels: status: ready for review 👀

#1530 test(cardVariables): add unit tests
  src/utils/__tests__/cardUtilityFunctions.test.jsx
  src/utils/cardUtilityFunctions.js
Labels: status: ready to merge :tada:

#1532 feat(TimeSeriesCard): add addSpaceOnEdges prop
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
  src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1535 fix(BarChartCard): show actual timestamp in tooltip
  src/components/BarChartCard/BarChartCard.jsx
  src/components/BarChartCard/barChartUtils.js
  src/components/BarChartCard/barChartUtils.test.js
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/constants/CardPropTypes.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1497 fix(datetime picker): externally set range not selected in calendar
  src/components/DateTimePicker/DateTimePicker.jsx
  src/components/DateTimePicker/DateTimePicker.test.jsx
  src/components/DateTimePicker/__snapshots__/DateTimePicker.story.storyshot
Labels: severity: 1 :rotating_light:, status: ready to merge :tada:

#1537 feat(table): Manage view modal
  .storybook/__snapshots__/Welcome.story.storyshot
  src/components/List/List.jsx
  src/components/Table/TableManageViewsModal/SharedTableManageViewsModalPropTypes.js
  src/components/Table/TableManageViewsModal/TableManageViewsList.jsx
  src/components/Table/TableManageViewsModal/TableManageViewsModal.jsx
  src/components/Table/TableManageViewsModal/TableManageViewsModal.story.jsx
  src/components/Table/TableManageViewsModal/TableManageViewsModal.test.jsx
  src/components/Table/TableManageViewsModal/__snapshots__/TableManageViewsModal.story.storyshot
  src/components/Table/TableManageViewsModal/table-manage-views-list.scss
  src/components/Table/TableManageViewsModal/table-manage-views-modal.scss
  src/index.js
  src/styles.scss
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1521 Filter tags group initial implementation
  .storybook/__snapshots__/Welcome.story.storyshot
  src/components/FilterTags/FilterTags.jsx
  src/components/FilterTags/FilterTags.story.jsx
  src/components/FilterTags/FilterTags.test.jsx
  src/components/FilterTags/__snapshots__/FilterTags.story.storyshot
  src/components/FilterTags/_filter-tags.scss
  src/index.js
  src/styles.scss
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge :tada:

#1544 fix(table): added test to check for bug #1193
  src/components/Table/Table.test.jsx
Labels: status: ready to merge :tada:

#1549 fix(TimeSeriesCard): Migrate to SCSS, and force white theme bg in zoombar
  src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  src/components/TimeSeriesCard/_time-series-card.scss
Labels: status: one more review 👀, status: ready for code owner's review

#1552 fix(statefultable): customToolbarContent element props unaffected
  src/components/Table/StatefulTable.jsx
  src/components/Table/StatefulTable.test.jsx
Labels: status: ready to merge :tada:

#1547 repo - add new templates for the repo to allow for angular
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request-or-enhancement.md
  .github/ISSUE_TEMPLATE/new-component-proposal.md
  .github/ISSUE_TEMPLATE/question.md
Labels: status: ready to merge :tada:
