Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2020-10, with the labels that each got.

#1644 1023 error boundary
  .storybook/__snapshots__/Welcome.story.storyshot
  src/components/ErrorBoundry/ErrorBoundry.story.jsx
  src/index.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready for code owner's review, status: ready to merge 🎉

#1636 Some fixes and enhancements to `SuiteHeader` component
  src/components/SuiteHeader/SuiteHeader.jsx
  src/components/SuiteHeader/SuiteHeader.story.jsx
  src/components/SuiteHeader/SuiteHeader.test.jsx
  src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.jsx
  src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.test.jsx
  src/components/SuiteHeader/SuiteHeaderAppSwitcher/__snapshots__/SuiteHeaderAppSwitcher.story.storyshot
  src/components/SuiteHeader/SuiteHeaderLogoutModal/SuiteHeaderLogoutModal.jsx
  src/components/SuiteHeader/SuiteHeaderProfile/SuiteHeaderProfile.jsx
  src/components/SuiteHeader/SuiteHeaderProfile/SuiteHeaderProfile.story.jsx
  src/components/SuiteHeader/SuiteHeaderProfile/SuiteHeaderProfile.test.jsx
  src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
  src/components/SuiteHeader/_suite-header.scss
  src/components/SuiteHeader/hooks/suiteHeaderData.fixture.js
  src/components/SuiteHeader/hooks/useSuiteHeaderData.js
  src/components/SuiteHeader/i18n/index.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1651 feat(table): added option alwaysTruncate (no refactor)
  src/components/Table/Table.jsx
  src/components/Table/Table.story.jsx
  src/components/Table/Table.test.jsx
  src/components/Table/TableBody/TableBody.jsx
  src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
  src/components/Table/TableCellRenderer/TableCellRenderer.jsx
  src/components/Table/TableHead/TableHead.jsx
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1668 fix(datetimepicker): fix setting absolute value
  src/components/DateTimePicker/DateTimePicker.jsx
Labels: status: one more review 👀

#1665 fix(hierarchylist): search does not match catagories
  src/components/List/HierarchyList/HierarchyList.jsx
  src/components/List/HierarchyList/HierarchyList.test.jsx
Labels: status: ready to merge 🎉

#1669 fix(listitem): get stories to render and snapshot, fix proptype warnings
  src/components/Dashboard/CardRenderer.jsx
  src/components/List/ListItem/ListItem.story.jsx
  src/components/List/ListItem/ListItem.test.jsx
  src/components/List/ListItem/__snapshots__/ListItem.story.storyshot
  src/components/List/SimpleList/SimpleList.story.jsx
  src/components/List/SimpleList/__snapshots__/SimpleList.story.storyshot
  src/components/StorybookSnapshots.test.js
  src/components/TileCatalogNew/TilePagination/TilePagination.jsx
  src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
Labels: status: one more review 👀, status: ready to merge 🎉

#1582 feat(components):Light version IconSwitch and DateTimePicker
  src/components/DateTimePicker/DateTimePicker.jsx
  src/components/DateTimePicker/DateTimePicker.story.jsx
  src/components/DateTimePicker/DateTimePicker.test.jsx
  src/components/DateTimePicker/__snapshots__/DateTimePicker.story.storyshot
  src/components/DateTimePicker/_date-time-picker.scss
  src/components/IconSwitch/IconSwitch.jsx
  src/components/IconSwitch/IconSwitch.story.jsx
  src/components/IconSwitch/__snapshots__/IconSwitch.story.storyshot
  src/components/IconSwitch/_icon-switch.scss
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: one more review 👀

#1625 feat(wizardmodal): add onBack callback
  src/components/WizardModal/WizardModal.jsx
  src/components/WizardModal/WizardModal.story.jsx
  src/components/WizardModal/WizardModal.test.jsx
  src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: one more review 👀

#1667 [PageTitleBar] update style to match new spec
  src/components/NavigationBar/__snapshots__/NavigationBar.story.storyshot
  src/components/PageTitleBar/PageTitleBar.jsx
  src/components/PageTitleBar/PageTitleBar.story.jsx
  src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
  src/components/PageTitleBar/_page-title-bar.scss
  src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
  src/components/SideNav/__snapshots__/SideNav.story.storyshot
  src/components/TileGallery/TileGallery.story.jsx
  src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  src/components/WizardInline/__snapshots__/WizardInline.story.storyshot
Labels: status: ready to merge 🎉

#1679 Some minor fixes to the SuiteHeader component
  src/components/SuiteHeader/SuiteHeader.jsx
  src/components/SuiteHeader/_suite-header.scss
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: one more review 👀

#1654 feat(list): add emptyState
  src/components/List/List.jsx
  src/components/List/List.story.jsx
  src/components/List/List.test.jsx
  src/components/List/__snapshots__/List.story.storyshot
  src/components/List/_list.scss
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1682 fix(dashboardgrid): specify container padding for all breakpoints
  src/components/Dashboard/DashboardGrid.jsx
  src/constants/LayoutConstants.js
Labels: status: ready to merge 🎉

#1686 fix(barchartcard): add classname to top container, allow empty series prop
  src/components/BarChartCard/BarChartCard.jsx
  src/components/BarChartCard/barChartUtils.js
  src/components/BarChartCard/barChartUtils.test.js
  src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1692 [ListCard / SimpleList] bug fixes
  src/components/List/SimpleList/SimpleList.jsx
  src/components/List/SimpleList/SimpleList.story.jsx
  src/components/List/SimpleList/__snapshots__/SimpleList.story.storyshot
  src/components/ListCard/ListCard.jsx
  src/components/ListCard/ListCard.story.jsx
  src/components/ListCard/__snapshots__/ListCard.story.storyshot
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1688 feat(card): add onFocus, onBlur, tabIndex
  src/components/Card/Card.jsx
  src/components/Card/Card.story.jsx
  src/components/Card/__snapshots__/Card.story.storyshot
  src/constants/CardPropTypes.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1641 feat(valuecard): added ability to override custom formatting
  src/components/ValueCard/Attribute.jsx
  src/components/ValueCard/ValueCard.jsx
  src/components/ValueCard/ValueCard.story.jsx
  src/components/ValueCard/ValueCard.test.jsx
  src/components/ValueCard/ValueRenderer.jsx
  src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
  src/constants/CardPropTypes.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: one more review 👀

#1694 repo: add github actions for testing
  .github/workflows/build.yml
  .github/workflows/format.yml
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .travis.yml
  README.MD
Labels: status: ready for code owner's review, type: repo/dx :computer:

#1700 fix(tablehead): fixed crash after resize
  src/components/Table/TableHead/TableHead.jsx
  src/components/TableCard/TableCard.test.jsx
Labels: status: ready to merge 🎉

#1706 feat(exports): update exports to pass through carbon components
  .storybook/__snapshots__/Welcome.story.storyshot
  src/index.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1704 Next
  .travis.yml
  README.MD
  docs/guides/versioning.md
  package.json
  yarn.lock
Labels: status: one more review 👀

#1697 1584 sidenav
  src/components/Header/_header.scss
  src/components/SideNav/SideNav.jsx
  src/components/SideNav/SideNav.story.jsx
  src/components/SideNav/__snapshots__/SideNav.story.storyshot
  src/components/SideNav/_side-nav-carbon.scss
  src/components/SideNav/_side-nav-multi-tier.scss
  src/components/SideNav/_side-nav.scss
  src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
Labels: status: ready to merge 🎉

#1677 [DashboardEditor] base functionality
  .storybook/__snapshots__/Welcome.story.storyshot
  package.json
  rollup.config.js
  src/components/Card/Card.jsx
  src/components/Card/Card.test.jsx
  src/components/Card/CardToolbar.jsx
  src/components/CardCodeEditor/CardCodeEditor.jsx
  src/components/CardEditor/CardEditForm/CardEditForm.jsx
  src/components/CardEditor/CardEditForm/CardEditForm.test.jsx
  src/components/CardEditor/CardEditForm/_card-edit-form.scss
  src/components/CardEditor/CardEditor.jsx
  src/components/CardEditor/CardEditor.story.jsx
  src/components/CardEditor/CardEditor.test.jsx
  src/components/CardEditor/CardGalleryList/CardGalleryList.jsx
  src/components/CardEditor/CardGalleryList/alert-table.svg
  src/components/CardEditor/CardGalleryList/bar-grouped-graph.svg
  src/components/CardEditor/CardGalleryList/bar-stack-graph.svg
  src/components/CardEditor/CardGalleryList/data-table.svg
  src/components/CardEditor/CardGalleryList/image.svg
  src/components/CardEditor/CardGalleryList/line-graph.svg
  src/components/CardEditor/CardGalleryList/list.svg
  src/components/CardEditor/CardGalleryList/simple-bar-graph.svg
  src/components/CardEditor/CardGalleryList/value-kpi.svg
  src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  src/components/CardEditor/_card-editor.scss
  src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  src/components/DashboardEditor/DashboardEditor.jsx
  src/components/DashboardEditor/DashboardEditor.story.jsx
  src/components/DashboardEditor/DashboardEditor.test.jsx
  src/components/DashboardEditor/DashboardEditorHeader/DashboardEditorHeader.jsx
  src/components/DashboardEditor/DashboardEditorHeader/DashboardEditorHeader.story.jsx
  src/components/DashboardEditor/DashboardEditorHeader/__snapshots__/DashboardEditorHeader.story.storyshot
  src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  src/components/DashboardEditor/_dashboard-editor.scss
  src/components/DashboardEditor/editorUtils.jsx
  src/components/DashboardEditor/editorUtils.test.js
  src/components/FileDrop/__snapshots__/FileDrop.story.storyshot
  src/components/ImageCard/ImageCard.jsx
  src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
  src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  src/components/List/List.jsx
  src/components/List/SimpleList/__snapshots__/SimpleList.story.storyshot
  src/components/PageTitleBar/_page-title-bar.scss
  src/components/SuiteHeader/SuiteHeaderLogoutModal/__snapshots__/SuiteHeaderLogoutModal.story.storyshot
  src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
  src/components/TableCard/TableCard.jsx
  src/components/TableCard/__snapshots__/TableCard.story.storyshot
  src/components/ValueCard/ValueCard.jsx
  src/constants/LayoutConstants.js
  src/index.js
  src/styles.scss
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge 🎉

#1718 feat(pagewizard): afterFooterContent new prop
  src/components/PageWizard/PageWizard.jsx
  src/components/PageWizard/PageWizard.story.jsx
  src/components/PageWizard/PageWizardStep/PageWizardStep.jsx
  src/components/PageWizard/StatefulPageWizard.jsx
  src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
  src/components/PageWizard/_page-wizard.scss
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1716 docs(versioning): clarify distribution channels configuration
  .github/CONTRIBUTING.MD
  README.MD
  docs/guides/versioning.md
Labels: status: ready to merge 🎉

#1712 fix(header): make style changes to align with spec
  src/components/Header/Header.story.jsx
  src/components/Header/__snapshots__/Header.story.storyshot
  src/components/Header/_header.scss
Labels: status: ready to merge 🎉

#1726 fix(charts): remove cheerio, use native DOM methods for tooltip manipulation
  package.json
  rollup.config.js
  src/components/BarChartCard/barChartUtils.js
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/utils/__tests__/componentUtilityFunctions.test.js
  src/utils/componentUtilityFunctions.js
  yarn.lock
Labels: status: ready to merge 🎉

#1733 fix(svgs): convert to react components and update usage docs
  .eslintrc
  .github/CONTRIBUTING.MD
  .storybook/__snapshots__/Welcome.story.storyshot
  package.json
  rollup.config.js
  src/components/CardEditor/CardGalleryList/CardGalleryList.jsx
  src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  src/components/Dashboard/Dashboard.story.jsx
  src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  src/components/DashboardEditor/editorUtils.jsx
  src/icons/components/AlertTableIcon.jsx
  src/icons/components/BarGroupedGraphIcon.jsx
  src/icons/components/BarStackGraphIcon.jsx
  src/icons/components/ComputerChipIcon.jsx
  src/icons/components/DashboardIcon.jsx
  src/icons/components/DataScientistIcon.jsx
  src/icons/components/DataTableIcon.jsx
  src/icons/components/ImageIcon.jsx
  src/icons/components/LineGraphIcon.jsx
  src/icons/components/ListIcon.jsx
  src/icons/components/SimpleBarGraphIcon.jsx
  src/icons/components/ValueKpiIcon.jsx
  src/icons/components/index.jsx
  src/icons/svg/alert-table-icon.svg
  src/icons/svg/bar-grouped-graph-icon.svg
  src/icons/svg/bar-stack-graph-icon.svg
  src/icons/svg/computer-chip-icon.svg
  src/icons/svg/dashboard-icon.svg
  src/icons/svg/data-scientist-icon.svg
  src/icons/svg/data-table-icon.svg
  src/icons/svg/image-icon.svg
  src/icons/svg/line-graph-icon.svg
  src/icons/svg/list-icon.svg
  src/icons/svg/simple-bar-graph-icon.svg
  src/icons/svg/value-kpi-icon.svg
  src/index.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: one more review 👀, status: ready for code owner's review
