Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2021-08, with the labels that each got.

#2627 feat(card): add new datetimepicker to card as option
  packages/react/src/components/Card/Card.jsx
  packages/react/src/components/Card/Card.story.jsx
  packages/react/src/components/Card/Card.test.jsx
  packages/react/src/components/Card/CardToolbar.jsx
  packages/react/src/components/Card/__snapshots__/Card.story.storyshot
  packages/react/src/components/Card/_card-toolbar.scss
  packages/react/src/components/ComposedModal/__snapshots__/ComposedModal.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DateTimePicker/DateTimePickerV2.test.jsx
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/TableCard/TableCard.jsx
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/constants/DateConstants.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2622 feat(progressindicator): extend component features
  packages/react/src/components/PageWizard/PageWizard.jsx
  packages/react/src/components/PageWizard/PageWizard.story.jsx
  packages/react/src/components/PageWizard/StatefulPageWizard.jsx
  packages/react/src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
  packages/react/src/components/ProgressIndicator/ProgressIndicator.jsx
  packages/react/src/components/ProgressIndicator/ProgressIndicator.story.jsx
  packages/react/src/components/ProgressIndicator/ProgressIndicator.test.jsx
  packages/react/src/components/ProgressIndicator/__snapshots__/ProgressIndicator.story.storyshot
  packages/react/src/components/ProgressIndicator/_progress-indicator.scss
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: package: react, status: one more review 👀

#2386 feat(side-panel): initial
  .vscode/settings.json
  packages/angular/package.json
  packages/angular/src/side-panel/index.ts
  packages/angular/src/side-panel/package.json
  packages/angular/src/side-panel/side-panel-footer.directive.ts
  packages/angular/src/side-panel/side-panel-title.directive.ts
  packages/angular/src/side-panel/side-panel.component.ts
  packages/angular/src/side-panel/side-panel.module.ts
  packages/angular/src/side-panel/side-panel.scss
  packages/angular/src/side-panel/side-panel.stories.ts
  yarn.lock
Labels: status: ready for review 👀, status: visual review 🔍, package: angular

#2643 Empty state fix
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/config/jest/setupTest.js
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/EmptyState/EmptyState.jsx
  packages/react/src/components/EmptyState/EmptyState.story.jsx
  packages/react/src/components/EmptyState/EmptyState.test.jsx
  packages/react/src/components/EmptyState/__snapshots__/EmptyState.story.storyshot
  packages/react/src/components/MapCard/MapCard.story.jsx
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/hooks/useUniqueId.jsx
  packages/react/src/icons/components/index.jsx
  packages/react/src/icons/static/EmptyState404Icon.jsx
  packages/react/src/icons/static/EmptyStateDefaultIcon.jsx
  packages/react/src/icons/static/EmptyStateErrorIcon.jsx
  packages/react/src/icons/static/EmptyStateNoResultsIcon.jsx
  packages/react/src/icons/static/EmptyStateNotAuthorizedIcon.jsx
  packages/react/src/icons/static/EmptyStateSuccessIcon.jsx
  packages/react/src/icons/static/index.jsx
  packages/react/src/icons/svg/emptystate-404-icon.svg
  packages/react/src/icons/svg/emptystate-Default-icon.svg
  packages/react/src/icons/svg/emptystate-Error-icon.svg
  packages/react/src/icons/svg/emptystate-Noresults-icon.svg
  packages/react/src/icons/svg/emptystate-Notauthorized-icon.svg
  packages/react/src/icons/svg/emptystate-Success-icon.svg
  packages/react/src/index.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2636 Resolving flatpickr to 4.6.1 for consumers
  package.json
  packages/react/package.json
Labels: status: ready to merge 🎉, package: react

#2637 fix(timeseriescard): tooltip was not formatting in the correct locale
  packages/react/src/components/BarChartCard/BarChartCard.jsx
  packages/react/src/components/BarChartCard/barChartUtils.js
  packages/react/src/components/ComboChartCard/comboChartHelpers.js
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
  packages/react/src/utils/cardUtilityFunctions.js
Labels: status: ready to merge 🎉

#2624 Align card with updated spec
  packages/react/src/components/BarChartCard/__snapshots__/BarChartCard.story.storyshot
  packages/react/src/components/BarChartCard/_bar-chart-card.scss
  packages/react/src/components/Card/Card.jsx
  packages/react/src/components/Card/Card.mdx
  packages/react/src/components/Card/Card.story.jsx
  packages/react/src/components/Card/Card.test.jsx
  packages/react/src/components/Card/CardRangePicker.jsx
  packages/react/src/components/Card/CardRangePicker.test.jsx
  packages/react/src/components/Card/CardToolbar.jsx
  packages/react/src/components/Card/__snapshots__/Card.story.storyshot
  packages/react/src/components/Card/_card-range-picker.scss
  packages/react/src/components/Card/_card.scss
  packages/react/src/components/ComboChartCard/__snapshots__/ComboChartCard.story.storyshot
  packages/react/src/components/ComposedModal/__snapshots__/ComposedModal.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/DateTimePicker/_date-time-pickerv2.scss
  packages/react/src/components/GaugeCard/__snapshots__/GaugeCard.story.storyshot
  packages/react/src/components/GaugeCard/_gauge-card.scss
  packages/react/src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
  packages/react/src/components/ImageCard/_image-card.scss
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/components/MapCard/_map-card.scss
  packages/react/src/components/PieChartCard/__snapshots__/PieChartCard.story.storyshot
  packages/react/src/components/PieChartCard/_pie-chart-card.scss
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/TableCard/TableCard.jsx
  packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
  packages/react/src/components/TableCard/_table-card.scss
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  packages/react/src/components/TimeSeriesCard/_time-series-card.scss
  packages/react/src/components/ValueCard/_attribute.scss
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/hooks/useHasTextOverflow.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2655 fix(card): fix mixin import
  packages/react/src/components/Card/_card.scss
Labels: status: one more review 👀

#2651 fix(repo): pin @carbon/charts versions
  package.json
  packages/react/package.json
  yarn.lock
Labels: status: ready to merge 🎉

#2659 2460 table adding columns ignores the defined widths
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/Table.mdx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/TableHead/TableHead.jsx
  packages/react/src/components/Table/TableHead/TableHead.test.jsx
  packages/react/src/components/Table/TableHead/columnWidthUtilityFunctions.js
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: one more review 👀, status: ready to merge 🎉

#2638 fix(sc-table-model): fix sterling model throwing errors
  packages/angular/package.json
  packages/angular/src/toolkit/table/sterling-table-model.class.ts
  yarn.lock
Labels: status: ready to merge 🎉, package: angular

#2424 feat(list): Add angular list
  packages/angular/src/list/ai-list.component.ts
  packages/angular/src/list/index.ts
  packages/angular/src/list/list-header/ai-list-header.ts
  packages/angular/src/list/list-item/ai-list-item-wrapper.component.ts
  packages/angular/src/list/list-item/ai-list-item.class.ts
  packages/angular/src/list/list-item/ai-list-item.component.ts
  packages/angular/src/list/list-item/ai-list-target.directive.ts
  packages/angular/src/list/list.module.ts
  packages/angular/src/list/list.stories.ts
  packages/angular/src/list/package.json
  packages/angular/src/list/sample-data.ts
  packages/angular/src/list/stories/app-custom-list.component.ts
  packages/angular/src/list/stories/app-hierarchy-list.component.ts
  packages/angular/src/list/stories/index.ts
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/components/List/List.jsx
  packages/react/src/components/List/ListItem/ListItem.jsx
  packages/react/src/components/List/ListItem/_list-item.scss
  packages/react/src/components/List/__snapshots__/List.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/SelectUsersModal/__snapshots__/SelectUsersModal.story.storyshot
  packages/styles/src/components/BarChartCard/_bar-chart-card.scss
  packages/styles/src/components/Card/_card-range-picker.scss
  packages/styles/src/components/Card/_card-toolbar.scss
  packages/styles/src/components/Card/_card.scss
  packages/styles/src/components/DateTimePicker/_date-time-pickerv2.scss
  packages/styles/src/components/GaugeCard/_gauge-card.scss
  packages/styles/src/components/ImageCard/_image-card.scss
  packages/styles/src/components/List/ListItem/_list-item.scss
  packages/styles/src/components/MapCard/_map-card.scss
  packages/styles/src/components/NumberInput/_number-input.scss
  packages/styles/src/components/PieChartCard/_pie-chart-card.scss
  packages/styles/src/components/ProgressIndicator/_progress-indicator.scss
  packages/styles/src/components/Table/_table.scss
  packages/styles/src/components/TableCard/_table-card.scss
  packages/styles/src/components/TearSheet/tear-sheet-wrapper.scss
  packages/styles/src/components/TearSheet/tear-sheet.scss
  packages/styles/src/components/TimeSeriesCard/_time-series-card.scss
  packages/styles/src/components/ValueCard/_attribute.scss
  packages/styles/src/styles.scss
Labels: status: ready to merge 🎉, package: react, package: angular

#2664 Import list styles from Carbon
  packages/react/src/components/List/_carbon-list.scss
  packages/react/src/styles.scss
  packages/styles/src/components/List/_carbon-list.scss
Labels: status: ready to merge 🎉

#2663 fix(dashboard): fix small card sizes
  packages/react/src/constants/LayoutConstants.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2666 feat(table): preserve columns widths on resize
  packages/react/src/components/Table/Table.test.jsx
  packages/react/src/components/Table/TableHead/ColumnResize.jsx
  packages/react/src/components/Table/TableHead/ColumnResize.test.jsx
  packages/react/src/components/Table/TableHead/TableHead.jsx
Labels: status: ready to merge 🎉

#2662 fix(suite-header): truncate long menu item text
  packages/react/src/components/Header/HeaderAction/HeaderActionMenu.jsx
  packages/react/src/components/Header/HeaderAction/HeaderActionMenu.test.jsx
  packages/react/src/components/Header/HeaderAction/__snapshots__/HeaderActionMenu.test.jsx.snap
  packages/react/src/components/Header/_header.scss
  packages/react/src/components/SuiteHeader/SuiteHeader.story.jsx
  packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
Labels: status: ready to merge 🎉

#2668 feat(theshold-form-item): allow strings when equal comparison
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ThresholdsFormItem.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ThresholdsFormItem.test.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/__snapshots__/ThresholdsFormItem.story.storyshot
  packages/react/src/components/CardEditor/CardEditForm/_card-edit-form.scss
Labels: status: ready to merge 🎉

#2673 fix(repo): fix copy plugin to include css
  packages/react/rollup.config.js
Labels: status: ready to merge 🎉

#2654 feat(tablecardeditform): allow edit form to be better customized
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ContentFormItemTitle.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ContentFormItemTitle.test.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/_card-edit-form.scss
  packages/react/src/components/CardEditor/CardEditor.jsx
  packages/react/src/components/CardEditor/CardEditor.story.jsx
  packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  packages/react/src/components/ComboBox/__snapshots__/ComboBox.story.storyshot
  packages/react/src/components/ComposedModal/__snapshots__/ComposedModal.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/__snapshots__/HotspotEditorDataSourceTab.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2669 fix(table): prevent column widths below min width
  packages/react/src/components/ComboChartCard/__snapshots__/ComboChartCard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/Table/TableHead/TableHead.jsx
  packages/react/src/components/Table/TableHead/TableHead.test.jsx
  packages/react/src/components/Table/TableHead/columnWidthUtilityFunctions.js
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
  packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
Labels: status: ready to merge 🎉

#2667 fix(stateful-table): update pagination properly on deletes
  packages/react/src/components/Table/StatefulTable.jsx
  packages/react/src/components/Table/StatefulTable.story.jsx
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/tableReducer.js
Labels: status: ready to merge 🎉

#2676 chore(table): fix sticky header/tooltip story so tooltips appear
  packages/react/src/components/Table/Table.story.jsx
Labels: status: ready to merge 🎉

#2675 feat(dashboardeditor): send card select event
  packages/react/package.json
  packages/react/src/components/Card/_card.scss
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.test.jsx
  packages/react/src/components/DashboardEditor/_dashboard-editor.scss
  packages/react/src/components/TableCard/_table-card.scss
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge 🎉

#2685 Idle timer mobile support
  packages/react/src/components/SuiteHeader/util/IdleTimer.js
Labels: status: ready to merge 🎉

#2683 fix(icon-dropdown): fix <button> in <button> warnings
  packages/react/src/components/IconDropdown/IconDropdown.jsx
  packages/react/src/components/IconDropdown/IconDropdown.test.jsx
Labels: status: ready to merge 🎉

#2681 fix(header): fix header testing noise, onKeyDown handlers
  packages/react/src/components/Header/Header.story.jsx
  packages/react/src/components/Header/Header.test.jsx
  packages/react/src/components/Header/HeaderAction/HeaderActionMenu.jsx
  packages/react/src/components/Header/HeaderAction/__snapshots__/HeaderActionMenu.test.jsx.snap
  packages/react/src/components/Header/__snapshots__/Header.story.storyshot
  packages/react/src/components/Header/__snapshots__/Header.test.jsx.snap
  packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
Labels: status: ready to merge 🎉

#2677 chore(stateful-table): fix table story
  packages/react/src/components/Table/StatefulTable.story.jsx
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
Labels: status: ready to merge 🎉

#2647 fix(bar-chart-card): format x-axis labels to match TimeSeriesCard
  packages/react/src/components/BarChartCard/BarChartCard.jsx
  packages/react/src/components/BarChartCard/BarChartCard.story.jsx
  packages/react/src/components/BarChartCard/__snapshots__/BarChartCard.story.storyshot
  packages/react/src/components/ComposedModal/__snapshots__/ComposedModal.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
Labels: status: ready to merge 🎉

#2678 fix(time-series-card): fix refs in mocks for test output
  packages/react/__mocks__/@carbon/charts-react/bar-chart-grouped.js
  packages/react/__mocks__/@carbon/charts-react/bar-chart-simple.js
  packages/react/__mocks__/@carbon/charts-react/bar-chart-stacked.js
  packages/react/__mocks__/@carbon/charts-react/combo-chart.js
  packages/react/__mocks__/@carbon/charts-react/line-chart.js
  packages/react/__mocks__/@carbon/charts-react/pie-chart.js
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
Labels: status: ready to merge 🎉

#2674 fix(rule-builder): export RuleBuilder in index
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/src/index.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2670 feat(table): allow objects to be passed as data
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
  packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.jsx
  packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.test.jsx
  packages/react/src/components/Table/TablePropTypes.js
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
Labels: status: ready to merge 🎉, package: react

#2679 fix(suite-header): no javascript urls in links, fix testing output errors
  packages/react/src/components/Header/Header.test.jsx
  packages/react/src/components/Header/HeaderAction/HeaderActionMenu.jsx
  packages/react/src/components/Header/HeaderAction/__snapshots__/HeaderActionMenu.test.jsx.snap
  packages/react/src/components/Header/__snapshots__/Header.story.storyshot
  packages/react/src/components/Header/__snapshots__/Header.test.jsx.snap
  packages/react/src/components/SuiteHeader/SuiteHeader.jsx
  packages/react/src/components/SuiteHeader/SuiteHeader.story.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/__snapshots__/SuiteHeaderAppSwitcher.story.storyshot
  packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
Labels: version: 3, status: ready to merge 🎉

#2684 chore(table): remove exports for internal table components
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/src/index.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: version: 3, status: ready to merge 🎉

#2689 2317 table column resize fails after all columns have been hidden
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/TableHead/TableHead.jsx
  packages/react/src/components/Table/TableHead/TableHead.test.jsx
  packages/react/src/components/Table/TableHead/columnWidthUtilityFunctions.js
Labels: status: ready to merge 🎉

#2686 chore(testing): increase coverage on TableSaveViewModal
  packages/react/jest.config.js
  packages/react/src/components/Table/TableSaveViewModal/TableSaveViewModal.test.jsx
Labels: status: ready to merge 🎉

#2691 fix(date-time-picker): support i18n features
  packages/angular/src/date-time-picker/custom-date-time.component.ts
  packages/angular/src/date-time-picker/date-time-absolute.component.ts
  packages/angular/src/date-time-picker/date-time-picker.component.ts
  packages/angular/src/date-time-picker/date-time-picker.module.ts
  packages/angular/src/date-time-picker/date-time-picker.stories.ts
  packages/angular/src/date-time-picker/date-time-relative.component.ts
Labels: status: ready to merge 🎉, package: angular

#2687 chore(testing): increase coverage on PageTitleBar
  packages/react/src/components/PageTitleBar/PageTItleBar.test.e2e.jsx
  packages/react/src/components/PageTitleBar/PageTitleBar.jsx
  packages/react/src/components/PageTitleBar/PageTitleBar.test.jsx
Labels: status: ready to merge 🎉

#2697 fix(datetimepicker): handle null select
  packages/angular/src/date-time-picker/date-time-picker.component.ts
Labels: package: angular

#2665 test(list): add tests for angular list
  packages/angular/src/list/ai-list.spec.ts
  packages/angular/src/list/list-item/ai-list-item.class.ts
  packages/angular/src/list/list-item/ai-list-item.component.ts
  packages/angular/src/list/list-item/ai-list-item.spec.ts
Labels: status: ready to merge 🎉, package: angular

#2606 feat(table): add new table model and multi-line header implementation
  packages/angular/src/table/head/table-head-cell.component.ts
  packages/angular/src/table/head/table-head-cell.scss
  packages/angular/src/table/head/table-head.component.ts
  packages/angular/src/table/head/table-head.scss
  packages/angular/src/table/index.ts
  packages/angular/src/table/package.json
  packages/angular/src/table/table-model.class.spec.ts
  packages/angular/src/table/table-model.class.ts
  packages/angular/src/table/table.component.ts
  packages/angular/src/table/table.module.ts
  packages/angular/src/table/table.scss
  packages/angular/src/table/table.stories.ts
  packages/styles/src/globals/_vars.scss
Labels: package: angular

#2682 fix(filter-tags): force <a> tags in overflow menu
  packages/react/src/components/FilterTags/FilterTags.jsx
Labels: version: 3, status: ready to merge 🎉

#2723 chore(repo): exclude snapshot tests
  packages/react/jest.config.js
Labels: status: ready to merge 🎉

#2693 chore(testing): increase coverage on SuiteHeader
  packages/react/jest.config.js
  packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
Labels: status: ready to merge 🎉

#2703 test(listitemwrapper): improved unit test coverage
  packages/react/jest.config.js
  packages/react/src/components/List/ListItem/ListItem.test.jsx
Labels: status: ready to merge 🎉

#2714 chore(testing): increase coverage on DashboardEditor
  packages/react/cypress.json
  packages/react/cypress/fixtures/robot_arm.png
  packages/react/cypress/plugins/index.js
  packages/react/cypress/support/commands.js
  packages/react/package.json
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.test.e2e.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.test.jsx
  yarn.lock
Labels: status: ready to merge 🎉

#2694 chore(testing): increase coverage on SuiteHeaderAppSwitcher
  packages/react/jest.config.js
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.test.jsx
Labels: status: ready to merge 🎉

#2721 chore(testing): increase threshold on CatalogContent
  packages/react/jest.config.js
Labels: status: ready to merge 🎉

#2705 chore(testing): increase coverage on DashboardEditorCardRenderer
  packages/react/src/components/DashboardEditor/DashboardEditorCardRenderer.test.jsx
Labels: status: ready to merge 🎉

#2701 chore(testing): increase TableCard coverage, fix bugs found
  packages/react/src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
  packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.jsx
  packages/react/src/components/TableCard/TableCard.jsx
  packages/react/src/components/TableCard/TableCard.test.jsx
  packages/react/src/components/TableCard/tableCardUtils.jsx
Labels: status: ready to merge 🎉

#2700 2544 navigation bar improve unit test coverage
  packages/react/jest.config.js
  packages/react/src/components/NavigationBar/NavigationBar.test.jsx
Labels: status: ready to merge 🎉

#2719 chore(testing): increase coverage on ResourceList, remove enzyme
  packages/react/jest.config.js
  packages/react/src/components/ResourceList/ResourceList.test.jsx
Labels: status: ready to merge 🎉

#2696 chore(testing): increase coverage on Attribute
  packages/react/jest.config.js
  packages/react/src/components/ValueCard/Attribute.test.jsx
Labels: status: ready to merge 🎉

#2712 chore(testing): add TimeSeriesCard coverage
  packages/react/jest.config.js
  packages/react/package.json
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.test.e2e.jsx
  packages/react/src/components/TimeSeriesCard/timeSeriesUtils.test.js
Labels: status: ready to merge 🎉

#2695 chore(testing): increase coverage on ValueRenderer
  packages/react/jest.config.js
  packages/react/src/components/ValueCard/ValueRenderer.test.jsx
Labels: status: ready to merge 🎉

#2692 chore(testing): increase coverage on iconDropdown
  packages/react/jest.config.js
  packages/react/src/components/IconDropdown/IconDropdown.jsx
  packages/react/src/components/IconDropdown/IconDropdown.test.jsx
Labels: status: ready to merge 🎉

#2720 chore(testing): increase threshold on ComposedStructuredList
  packages/react/jest.config.js
Labels: status: ready to merge 🎉

#2711 test(dashboardheader): set individual thresholds to current coverage
  packages/react/jest.config.js
Labels: status: ready to merge 🎉

#2688 chore(testing): hierarchy list coverage
  packages/react/cypress/support/commands.js
  packages/react/jest.config.js
  packages/react/package.json
  packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/List/HierarchyList/HierarchyList.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.story.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.test.e2e.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.test.jsx
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/components/List/ListItem/ListItemWrapper.jsx
  packages/react/src/components/List/ListItem/__snapshots__/ListItem.story.storyshot
  packages/react/src/components/List/SimpleList/__snapshots__/SimpleList.story.storyshot
  packages/react/src/components/List/__snapshots__/List.story.storyshot
  yarn.lock
Labels: status: ready to merge 🎉

#2702 test(tablemanageviewsmodal): improved unit test coverage
  packages/react/jest.config.js
  packages/react/src/components/Table/TableManageViewsModal/TableManageViewsModal.test.jsx
Labels: status: ready to merge 🎉

#2690 chore(testing): increase coverage on TimePickerSpinner
  packages/react/jest.config.js
  packages/react/src/components/DateTimePicker/__snapshots__/DateTimePicker.story.storyshot
  packages/react/src/components/TimePickerSpinner/TimePickerSpinner.jsx
  packages/react/src/components/TimePickerSpinner/TimePickerSpinner.test.jsx
  packages/react/src/components/TimePickerSpinner/__snapshots__/TimePickerSpinner.story.storyshot
Labels: status: ready to merge 🎉

#2713 fix(datetimepicker): fix absolute date format
  packages/angular/src/date-time-picker/custom-date-time.component.ts
  packages/angular/src/date-time-picker/date-time-absolute.component.ts
  packages/angular/src/date-time-picker/date-time-picker.component.ts
  packages/angular/src/date-time-picker/date-time-picker.stories.ts
Labels: package: angular

#2778 fix(date-time-picker): wait until finished typing to parse dates
  packages/react/src/components/DateTimePicker/DateTimePicker.jsx
Labels: status: ready to merge 🎉
