Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2021-07, with the labels that each got.

#2406 fix(hotspoteditormodal): added readme files and small fixes
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/docs/guides/overrides-pattern.md
  packages/react/src/components/HotspotEditorModal/DynamicHotspotSourcePicker/DynamicHotspotSourcePicker.jsx
  packages/react/src/components/HotspotEditorModal/DynamicHotspotSourcePicker/DynamicHotspotSourcePicker.story.jsx
  packages/react/src/components/HotspotEditorModal/DynamicHotspotSourcePicker/DynamicHotspotSourcePickerREADME.mdx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.story.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.test.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTabREADME.mdx
  packages/react/src/components/HotspotEditorModal/HotspotEditorModal.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorModal.story.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorModalREADME.mdx
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/HotspotEditorTooltipTab.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/HotspotEditorTooltipTab.story.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/HotspotEditorTooltipTabREADME.mdx
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/__snapshots__/HotspotEditorTooltipTab.story.storyshot
  packages/react/src/components/HotspotEditorModal/HotspotTextStyleTab/HotspotTextStyleTab.jsx
  packages/react/src/components/HotspotEditorModal/HotspotTextStyleTab/HotspotTextStyleTab.story.jsx
  packages/react/src/components/HotspotEditorModal/HotspotTextStyleTab/HotspotTextStyleTabREADME.mdx
  packages/react/src/components/HotspotEditorModal/HotspotTextStyleTab/__snapshots__/HotspotTextStyleTab.story.storyshot
  packages/react/src/components/HotspotEditorModal/HotspotTextStyleTab/_hotspot-text-style-tab.scss
  packages/react/src/components/HotspotEditorModal/__snapshots__/HotspotEditorModal.story.storyshot
  packages/react/src/constants/SharedPropTypes.js
  packages/react/src/index.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2500 fix(card-variables): handle null values in handle-card-variables
  packages/react/src/utils/__tests__/cardUtilityFunctions.test.jsx
  packages/react/src/utils/cardUtilityFunctions.js
Labels: status: one more review 👀

#2489 fix(table): wrap the column selection text
  packages/react/src/components/Table/TableHead/ColumnHeaderRow/_column-header-row.scss
Labels: status: ready to merge 🎉

#2461 fix(imagehotspots): fixes object-fit contain fill and undefined
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormSettings.jsx
  packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/HotspotEditorModal/HotspotEditorModal.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorModal.story.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorModalREADME.mdx
  packages/react/src/components/HotspotEditorModal/landscape.jpg
  packages/react/src/components/ImageCard/ImageCard.jsx
  packages/react/src/components/ImageCard/ImageCard.story.jsx
  packages/react/src/components/ImageCard/ImageHotspots.jsx
  packages/react/src/components/ImageCard/ImageHotspots.story.jsx
  packages/react/src/components/ImageCard/ImageHotspots.test.jsx
  packages/react/src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
  packages/react/src/components/ImageCard/__snapshots__/ImageHotspots.story.storyshot
  packages/react/src/components/ImageCard/landscape.jpg
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2467 fix(datepicker): relative dates while changing the hours minutes throws an exception
  packages/react/src/components/DateTimePicker/DateTimePicker.jsx
Labels: status: ready to merge 🎉

#2475 chore(repo): deprecate testID and add testId - 2
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/__snapshots__/ThresholdsFormItem.story.storyshot
  packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  packages/react/src/components/ColorDropdown/ColorDropdown.jsx
  packages/react/src/components/ColorDropdown/ColorDropdown.test.jsx
  packages/react/src/components/ColorDropdown/__snapshots__/ColorDropdown.story.storyshot
  packages/react/src/components/ComboBox/ComboBox.jsx
  packages/react/src/components/ComboChartCard/ComboChartCard.jsx
  packages/react/src/components/ComboChartCard/ComboChartCard.test.jsx
  packages/react/src/components/ComposedModal/ComposedModal.jsx
  packages/react/src/components/ComposedModal/ComposedModal.test.jsx
  packages/react/src/components/ComposedStructuredList/ComposedStructuredList.jsx
  packages/react/src/components/ComposedStructuredList/ComposedStructuredList.test.jsx
  packages/react/src/components/ComposedStructuredList/__snapshots__/ComposedStructuredList.story.storyshot
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/__snapshots__/HotspotEditorTooltipTab.story.storyshot
  packages/react/src/components/HotspotEditorModal/HotspotTextStyleTab/__snapshots__/HotspotTextStyleTab.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2478 chore(repo): deprecate `testID` and add `testId` - 3
  packages/react/src/components/Dashboard/Dashboard.jsx
  packages/react/src/components/Dashboard/Dashboard.test.jsx
  packages/react/src/components/Dashboard/DashboardHeader.jsx
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardHeader.story.storyshot
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.test.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorHeader/DashboardEditorHeader.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorHeader/DashboardEditorHeader.test.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorHeader/__snapshots__/DashboardEditorHeader.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/IconSwitch/IconSwitch.jsx
  packages/react/src/components/IconSwitch/IconSwitch.test.jsx
  packages/react/src/components/IconSwitch/__snapshots__/IconSwitch.story.storyshot
  packages/react/src/components/ImageGalleryModal/__snapshots__/ImageGalleryModal.story.storyshot
  packages/react/src/components/NavigationBar/__snapshots__/NavigationBar.story.storyshot
  packages/react/src/components/PageTitleBar/PageTitleBar.jsx
  packages/react/src/components/PageTitleBar/PageTitleBar.test.jsx
  packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
  packages/react/src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
  packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/components/WizardInline/__snapshots__/WizardInline.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2495 test(composedmodal): increased coverage and rewrote enzyme tests
  packages/react/jest.config.js
  packages/react/src/components/ComposedModal/ComposedModal.test.jsx
Labels: status: ready to merge 🎉

#2491 fix(header): clicking directly on the icon failed to open overflowmenu
  packages/react/src/components/Header/Header.test.jsx
  packages/react/src/components/Header/HeaderActionGroup.jsx
  packages/react/src/components/Header/_header.scss
Labels: status: ready to merge 🎉

#2473 2472 table improve story for exploring column settings
  packages/react/src/components/Table/Table.mdx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
  packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
Labels: status: merge conflicts :no_entry_sign:

#2480 chore(repo): deprecate testID and add testId - 4
  packages/react/src/components/Dashboard/Dashboard.jsx
  packages/react/src/components/Dashboard/Dashboard.test.jsx
  packages/react/src/components/Dashboard/DashboardGrid.jsx
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/Dropdown/Dropdown.jsx
  packages/react/src/components/Dropdown/Dropdown.test.jsx
  packages/react/src/components/Dropdown/__snapshots__/Dropdown.story.storyshot
  packages/react/src/components/EmptyState/EmptyState.jsx
  packages/react/src/components/EmptyState/EmptyState.test.jsx
  packages/react/src/components/FileDrop/FileDrop.jsx
  packages/react/src/components/FileDrop/FileDrop.test.jsx
  packages/react/src/components/FileDrop/__snapshots__/FileDrop.story.storyshot
  packages/react/src/components/FilterTags/FilterTags.jsx
  packages/react/src/components/FilterTags/FilterTags.test.jsx
  packages/react/src/components/FilterTags/__snapshots__/FilterTags.story.storyshot
  packages/react/src/components/FlyoutMenu/FlyoutMenu.jsx
  packages/react/src/components/FlyoutMenu/__snapshots__/FlyoutMenu.story.storyshot
  packages/react/src/components/GaugeCard/GaugeCard.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/__snapshots__/HotspotEditorTooltipTab.story.storyshot
  packages/react/src/components/PieChartCard/__snapshots__/PieChartCard.story.storyshot
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2497 2496 accordion item defer improve unit test coverage
  packages/react/jest.config.js
  packages/react/src/components/Accordion/AccordionItemDefer.test.jsx
Labels: status: ready to merge 🎉

#2504 2502 breadcrumb improve unit test coverage
  packages/react/jest.config.js
  packages/react/src/components/Breadcrumb/Breadcrumb.test.jsx
Labels: status: ready to merge 🎉

#2521 test(tablebodyrow): improved unit test coverage
  packages/react/jest.config.js
  packages/react/src/components/Table/TableBody/TableBodyRow/TableBodyRow.test.jsx
Labels: status: ready to merge 🎉

#2505 test(rowactionserror): improved unit test coverage
  packages/react/jest.config.js
  packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.test.jsx
  packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsError.jsx
Labels: status: ready to merge 🎉

#2481 chore(repo): deprecate testID and add testId - 5
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/Header/Header.jsx
  packages/react/src/components/Header/Header.test.jsx
  packages/react/src/components/Header/HeaderAction/HeaderAction.jsx
  packages/react/src/components/Header/HeaderActionGroup.jsx
  packages/react/src/components/Header/__snapshots__/Header.story.storyshot
  packages/react/src/components/Header/__snapshots__/Header.test.jsx.snap
  packages/react/src/components/Hero/Hero.jsx
  packages/react/src/components/Hero/Hero.test.jsx
  packages/react/src/components/Hero/__snapshots__/Hero.story.storyshot
  packages/react/src/components/HotspotEditorModal/DynamicHotspotSourcePicker/DynamicHotspotSourcePicker.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/__snapshots__/HotspotEditorDataSourceTab.story.storyshot
  packages/react/src/components/HotspotEditorModal/HotspotEditorModal.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorModal.test.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/HotspotEditorTooltipTab.jsx
  packages/react/src/components/HotspotEditorModal/__snapshots__/HotspotEditorModal.story.storyshot
  packages/react/src/components/IconDropdown/IconDropdown.jsx
  packages/react/src/components/IconDropdown/IconDropdown.test.jsx
  packages/react/src/components/IconDropdown/__snapshots__/IconDropdown.story.storyshot
  packages/react/src/components/ImageCard/ImageCard.jsx
  packages/react/src/components/ImageCard/ImageCard.test.jsx
  packages/react/src/components/ImageCard/ImageUploader.jsx
  packages/react/src/components/ImageCard/ImageUploader.test.jsx
  packages/react/src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
  packages/react/src/components/ImageGalleryModal/ImageGalleryModal.jsx
  packages/react/src/components/ImageGalleryModal/ImageGalleryModal.test.jsx
  packages/react/src/components/ImageGalleryModal/ImageTile.jsx
  packages/react/src/components/ImageGalleryModal/ImageTile.test.jsx
  packages/react/src/components/ImageGalleryModal/__snapshots__/ImageGalleryModal.story.storyshot
  packages/react/src/components/Page/__snapshots__/EditPage.story.storyshot
  packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
  packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2597 2507 row actions cell improve unit test coverage
  packages/react/jest.config.js
  packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
  packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.test.jsx
Labels: status: ready to merge 🎉

#2365 Add angular datetimepicker
  package.json
  packages/angular/package.json
  packages/angular/src/date-time-picker/custom-date-time.component.ts
  packages/angular/src/date-time-picker/date-time-absolute.component.ts
  packages/angular/src/date-time-picker/date-time-picker.component.ts
  packages/angular/src/date-time-picker/date-time-picker.module.ts
  packages/angular/src/date-time-picker/date-time-picker.stories.ts
  packages/angular/src/date-time-picker/date-time-relative.component.ts
  packages/angular/src/date-time-picker/index.ts
  packages/angular/src/date-time-picker/package.json
  packages/angular/src/index.ts
  packages/angular/src/ng-package.json
  packages/angular/src/package.json
  packages/react/src/components/DateTimePicker/DateTimePicker.jsx
  packages/react/src/components/DateTimePicker/__snapshots__/DateTimePicker.story.storyshot
  packages/react/src/components/DateTimePicker/_date-time-picker.scss
  packages/styles/src/components/DateTimePicker/_date-time-picker.scss
  packages/styles/src/components/List/ListItem/_list-item.scss
  packages/styles/src/components/MapCard/storyFiles/drag-panel.scss
  packages/styles/src/components/Table/TableHead/_table-head.scss
  packages/styles/src/components/Table/TableMultiSortModal/_table-multi-sort-modal.scss
  packages/styles/src/components/Table/_table.scss
  packages/styles/src/components/TearSheet/tear-sheet-wrapper.scss
  packages/styles/src/components/TearSheet/tear-sheet.scss
  scripts/sync-styles.sh
  yarn.lock
Labels: package: angular, status: ready to merge 🎉

#2520 chore(suite-header): clean up test noise
  packages/react/src/components/SuiteHeader/IdleLogoutConfirmationModal/IdleLogoutConfirmationModal.test.jsx
  packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
  packages/react/src/components/SuiteHeader/util/IdleTimer.js
Labels: status: ready to merge 🎉

#2514 fix(rule-builder): prevent state update during render
  packages/react/src/components/RuleBuilder/RuleBuilderEditor.jsx
Labels: status: ready to merge 🎉

#2490 chore(repo): deprecate testID and add testId - 6
  packages/react/src/components/CardCodeEditor/CardCodeEditor.jsx
  packages/react/src/components/CardEditor/CardEditor.jsx
  packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  packages/react/src/components/ColorDropdown/ColorDropdown.jsx
  packages/react/src/components/ComposedModal/ComposedModal.jsx
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/Header/HeaderAction/HeaderAction.jsx
  packages/react/src/components/HotspotEditorModal/DynamicHotspotSourcePicker/DynamicHotspotSourcePicker.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/__snapshots__/HotspotEditorDataSourceTab.story.storyshot
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/HotspotEditorTooltipTab.jsx
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/components/List/List.jsx
  packages/react/src/components/List/List.test.jsx
  packages/react/src/components/List/ListHeader/ListHeader.jsx
  packages/react/src/components/List/SimpleList/__snapshots__/SimpleList.story.storyshot
  packages/react/src/components/List/__snapshots__/List.story.storyshot
  packages/react/src/components/ListBuilder/ListBuilder.jsx
  packages/react/src/components/ListBuilder/ListBuilder.test.jsx
  packages/react/src/components/ListBuilder/__snapshots__/ListBuilder.story.storyshot
  packages/react/src/components/ListCard/ListCard.jsx
  packages/react/src/components/ListCard/ListCard.test.jsx
  packages/react/src/components/ListCard/__snapshots__/ListCard.story.storyshot
  packages/react/src/components/MapCard/Legend.jsx
  packages/react/src/components/MapCard/MapCard.jsx
  packages/react/src/components/MapCard/MapCard.test.jsx
  packages/react/src/components/MapCard/MapControls.jsx
  packages/react/src/components/MapCard/ScrollingControls.jsx
  packages/react/src/components/MapCard/ZoomControl.jsx
  packages/react/src/components/MenuButton/MenuButton.jsx
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/SelectUsersModal/__snapshots__/SelectUsersModal.story.storyshot
  packages/react/src/components/StorybookSnapshots.test.js
  packages/react/src/components/Table/TableManageViewsModal/__snapshots__/TableManageViewsModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2600 2586 table improve unit test coverage
  packages/react/jest.config.js
  packages/react/src/components/Table/Table.test.helpers.js
  packages/react/src/components/Table/Table.test.jsx
Labels: status: ready to merge 🎉

#2493 chore(repo): deprecate testID and add testId - 7
  packages/react/src/components/NavigationBar/NavigationBar.jsx
  packages/react/src/components/NavigationBar/NavigationBar.test.jsx
  packages/react/src/components/NavigationBar/__snapshots__/NavigationBar.story.storyshot
  packages/react/src/components/OverflowMenu/OverflowMenu.test.jsx
  packages/react/src/components/OverflowMenu/__snapshots__/OverflowMenu.story.storyshot
  packages/react/src/components/OverflowMenu/index.jsx
  packages/react/src/components/Page/EditPage.jsx
  packages/react/src/components/Page/PageHero.jsx
  packages/react/src/components/Page/PageHero.test.jsx
  packages/react/src/components/Page/PageSwitcher.jsx
  packages/react/src/components/Page/PageTitle.jsx
  packages/react/src/components/Page/PageTitle.test.jsx
  packages/react/src/components/Page/PageWorkArea.jsx
  packages/react/src/components/Page/PageWorkArea.test.jsx
  packages/react/src/components/Page/__snapshots__/EditPage.story.storyshot
  packages/react/src/components/Page/__snapshots__/PageHero.story.storyshot
  packages/react/src/components/PageWizard/PageWizard.jsx
  packages/react/src/components/PageWizard/PageWizard.test.jsx
  packages/react/src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
  packages/react/src/components/ProgressIndicator/ProgressIndicator.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2598 fix(gauge-card): trends were cutoff on bottom of card
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/GaugeCard/GaugeCard.jsx
  packages/react/src/components/GaugeCard/GaugeCard.story.jsx
  packages/react/src/components/GaugeCard/__snapshots__/GaugeCard.story.storyshot
  packages/react/src/components/GaugeCard/_gauge-card.scss
Labels: status: ready to merge 🎉

#2499 chore(repo): deprecate testID and add testId - 8
  packages/react/src/components/PieChartCard/PieChartCard.jsx
  packages/react/src/components/PieChartCard/PieChartCard.test.jsx
  packages/react/src/components/ProgressIndicator/ProgressIndicator.test.jsx
  packages/react/src/components/ResourceList/ResourceList.jsx
  packages/react/src/components/ResourceList/ResourceList.test.jsx
  packages/react/src/components/ResourceList/__snapshots__/ResourceList.story.storyshot
  packages/react/src/components/RuleBuilder/RuleBuilder.jsx
  packages/react/src/components/RuleBuilder/RuleBuilder.test.jsx
  packages/react/src/components/RuleBuilder/RuleBuilderEditor.jsx
  packages/react/src/components/RuleBuilder/RuleBuilderHeader.jsx
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilderEditor.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: one more review 👀

#2464 Add browser based testing -cypress
  .github/workflows/test.yml
  .gitignore
  package.json
  packages/react/.eslintrc
  packages/react/babel.config.js
  packages/react/cypress.json
  packages/react/cypress/plugins/index.js
  packages/react/cypress/support/commands.js
  packages/react/cypress/support/index.js
  packages/react/jest.config.js
  packages/react/package.json
  packages/react/src/components/Button/Button.test.e2e.jsx
  packages/react/src/components/CardCodeEditor/CardCodeEditor.test.e2e.jsx
  yarn.lock
Labels: status: ready to merge 🎉

#2509 chore(repo): deprecate testID and add testId - 11
  packages/react/src/components/DateTimePicker/__snapshots__/DateTimePicker.story.storyshot
  packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
  packages/react/src/components/TileCatalogNew/TileCatalogNew.jsx
  packages/react/src/components/TileCatalogNew/TileCatalogNew.test.jsx
  packages/react/src/components/TileCatalogNew/TilePagination/TilePagination.jsx
  packages/react/src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
  packages/react/src/components/TileGallery/StatefulTileGallery.jsx
  packages/react/src/components/TileGallery/TileGallery.jsx
  packages/react/src/components/TileGallery/TileGallery.test.jsx
  packages/react/src/components/TileGallery/TileGalleryItem.jsx
  packages/react/src/components/TileGallery/TileGallerySearch.jsx
  packages/react/src/components/TileGallery/TileGallerySection.jsx
  packages/react/src/components/TileGallery/TileGalleryViewSwitcher.jsx
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/components/TimePickerSpinner/TimePickerSpinner.jsx
  packages/react/src/components/TimePickerSpinner/TimePickerSpinner.test.jsx
  packages/react/src/components/TimePickerSpinner/__snapshots__/TimePickerSpinner.story.storyshot
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.test.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2511 chore(repo) deprecate `testID` and add `testId` - 12
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/ImageCard/CardIcon.jsx
  packages/react/src/components/ImageCard/__snapshots__/HotspotContent.story.storyshot
  packages/react/src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
  packages/react/src/components/ImageCard/__snapshots__/ImageHotspots.story.storyshot
  packages/react/src/components/Table/TableDetailWizard/__snapshots__/TableDetailWizard.story.storyshot
  packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
  packages/react/src/components/Tooltip/Tooltip.test.jsx
  packages/react/src/components/Tooltip/__snapshots__/Tooltip.story.storyshot
  packages/react/src/components/Tooltip/index.jsx
  packages/react/src/components/ValueCard/Attribute.jsx
  packages/react/src/components/ValueCard/UnitRenderer.jsx
  packages/react/src/components/ValueCard/ValueCard.jsx
  packages/react/src/components/ValueCard/ValueCard.test.jsx
  packages/react/src/components/ValueCard/ValueRenderer.jsx
  packages/react/src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
  packages/react/src/components/WizardInline/WizardContent/WizardContent.jsx
  packages/react/src/components/WizardInline/WizardFooter/WizardFooter.jsx
  packages/react/src/components/WizardInline/WizardHeader/WizardHeader.jsx
  packages/react/src/components/WizardInline/WizardInline.jsx
  packages/react/src/components/WizardInline/WizardInline.test.jsx
  packages/react/src/components/WizardInline/WizardLeftSidebar/WizardSidebar.jsx
  packages/react/src/components/WizardInline/__snapshots__/WizardInline.story.storyshot
  packages/react/src/components/WizardModal/WizardModal.jsx
  packages/react/src/components/WizardModal/WizardModal.test.jsx
  packages/react/src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: one more review 👀

#2594 fix(datetimepicker): pin flatpickr to fix absolute date range
  package.json
  packages/react/src/components/DateTimePicker/DateTimePicker.jsx
  yarn.lock
Labels: status: ready to merge 🎉

#2611 Remove test from publish flow and add checklist to PR template
  .github/PULL_REQUEST_TEMPLATE.MD
  .github/workflows/publish.yml
Labels: status: ready to merge 🎉

#2612 fix(timeseriescard): Passing truncation type 'none' to chart tooltip options so that tooltip labels don’t get truncated.
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
Labels: status: one more review 👀

#2614 fix(timeseriescard): xaxis format incorrect with one datapoint in year interval
  packages/react/src/components/TimeSeriesCard/timeSeriesUtils.js
Labels: status: ready to merge 🎉

#2613 Table card scroll
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/TableCard/TableCard.jsx
  packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
Labels: package: react, status: ready to merge 🎉

#2617 Angular tabs part 2 - The revenge of the tabs
  packages/angular/angular.json
  packages/angular/gulpfile.js
  packages/angular/package.json
  packages/angular/scripts/build.sh
  packages/angular/src/tabs/index.ts
  packages/angular/src/tabs/package.json
  packages/angular/src/tabs/tab-controller.class.ts
  packages/angular/src/tabs/tab-dropdown.component.ts
  packages/angular/src/tabs/tab-header.component.ts
  packages/angular/src/tabs/tab.interface.ts
  packages/angular/src/tabs/tabs.component.ts
  packages/angular/src/tabs/tabs.module.ts
  packages/angular/src/tabs/tabs.stories.ts
  packages/styles/src/components/Header/_header.scss
  packages/styles/src/components/HotspotEditorModal/HotspotTextStyleTab/_hotspot-text-style-tab.scss
  packages/styles/src/components/SuiteHeader/_suite-header.scss
  packages/styles/src/components/Table/TableHead/ColumnHeaderRow/_column-header-row.scss
  packages/styles/src/components/TearSheet/tear-sheet-wrapper.scss
  packages/styles/src/components/TearSheet/tear-sheet.scss
  yarn.lock
Labels: package: angular, status: ready to merge 🎉
