Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2021-04, with the labels that each got.

#2182 chore(color-dropdown): increase testing coverage
  packages/react/jest.config.js
  packages/react/src/components/ColorDropdown/ColorDropdown.test.jsx
Labels: status: ready to merge 🎉

#2177 chore(stateful-table): increase testing coverage
  packages/react/jest.config.js
  packages/react/src/components/Table/StatefulTable.jsx
  packages/react/src/components/Table/StatefulTable.test.jsx
  packages/react/src/components/Table/TableDetailWizard/StatefulTableDetailWizard.jsx
Labels: status: ready to merge 🎉

#2186 style(page-title-bar): fix offsets
  packages/react/src/components/DashboardEditor/DashboardEditorHeader/__snapshots__/DashboardEditorHeader.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/NavigationBar/__snapshots__/NavigationBar.story.storyshot
  packages/react/src/components/PageTitleBar/PageTitleBar.jsx
  packages/react/src/components/PageTitleBar/PageTitleBar.story.jsx
  packages/react/src/components/PageTitleBar/PageTitleBar.test.jsx
  packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
  packages/react/src/components/PageTitleBar/_page-title-bar.scss
  packages/react/src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
  packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/components/WizardInline/__snapshots__/WizardInline.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2166 fix: add script to automatically sync styles from react
  packages/monorepo-utils/index.js
  packages/monorepo-utils/package-tools.js
  packages/monorepo-utils/promise-glob.js
  packages/monorepo-utils/vendor.js
  packages/styles/README.md
  packages/styles/package.json
  packages/styles/scripts/copy-styles-from-react.js
  packages/styles/src/components/Button/_button.scss
  packages/styles/src/components/CardEditor/CardEditForm/_card-edit-form.scss
  packages/styles/src/components/ComboChartCard/_combo-chart-card.scss
  packages/styles/src/components/Dashboard/_dashboard-grid.scss
  packages/styles/src/components/DashboardEditor/_dashboard-editor.scss
  packages/styles/src/components/FileUploader/FileUploader-story.scss
  packages/styles/src/components/FileUploader/_file-uploader.scss
  packages/styles/src/components/FlyoutMenu/_flyout-menu.scss
  packages/styles/src/components/List/ListItem/_list-item.scss
  packages/styles/src/components/ProgressIndicator/_progress-indicator.scss
  packages/styles/src/components/RuleBuilder/_rule-builder.scss
  packages/styles/src/components/RuleBuilder/_rulebuilder.scss
  packages/styles/src/components/SelectUsersModal/_select-users-modal.scss
  packages/styles/src/components/SuiteHeader/_suite-header.scss
  packages/styles/src/components/Table/TableFoot/_table-foot.scss
  packages/styles/src/components/Table/TableHead/FilterHeaderRow/_filter-header-row.scss
  packages/styles/src/components/Table/TableHead/_table-head.scss
  packages/styles/src/components/Table/_table.scss
  packages/styles/src/components/ValueCard/_attribute.scss
  packages/styles/src/styles.scss
Labels: package: angular, status: ready to merge 🎉

#2194 fix(hierarchylist): cloneDeep can blow up and clone the whole tree
  packages/react/src/components/List/HierarchyList/HierarchyList.jsx
Labels: status: ready to merge 🎉

#2195 fix(repo): un-scope monorepo-utils to prevent npm from trying to publish it
  packages/angular/package.json
  packages/angular/scripts/vendor.js
  packages/monorepo-utils/README.md
  packages/monorepo-utils/package.json
  packages/styles/package.json
  packages/styles/scripts/copy-styles-from-react.js
  packages/styles/scripts/vendor.js
Labels: status: ready to merge 🎉

#2126 fix(chartcards): deep merge the default content props
  packages/react/src/components/BarChartCard/BarChartCard.jsx
  packages/react/src/components/BarChartCard/BarChartCard.story.jsx
  packages/react/src/components/Dashboard/CardRenderer.jsx
  packages/react/src/components/PieChartCard/PieChartCard.jsx
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2202 fix(storybook): fix 'show info' button
  package.json
  packages/react/package.json
  yarn.lock
Labels: status: one more review 👀

#2199 chore: remove netlify.toml
  netlify.toml
Labels: status: ready for review 👀

#2209 fix(valuecard): set of related value card fixes
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorHeader/DashboardEditorHeader.jsx
  packages/react/src/components/ValueCard/Attribute.jsx
  packages/react/src/components/ValueCard/_value-renderer.scss
  packages/react/src/constants/LayoutConstants.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2047 fix(repo): swap styled components to scss
  .github/PULL_REQUEST_TEMPLATE.MD
  packages/react/.storybook/story-styles.scss
  packages/react/src/components/ComposedModal/ComposedModal.story.jsx
  packages/react/src/components/ComposedModal/__snapshots__/ComposedModal.story.storyshot
  packages/react/src/components/ComposedStructuredList/ComposedStructuredList.jsx
  packages/react/src/components/ComposedStructuredList/__snapshots__/ComposedStructuredList.story.storyshot
  packages/react/src/components/ComposedStructuredList/_composed-structured-list.scss
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/FileDrop/FileDrop.jsx
  packages/react/src/components/FileDrop/__snapshots__/FileDrop.story.storyshot
  packages/react/src/components/FileDrop/_file-drop.scss
  packages/react/src/components/Header/Header.story.jsx
  packages/react/src/components/Header/__snapshots__/Header.story.storyshot
  packages/react/src/components/ImageCard/ImageCard.jsx
  packages/react/src/components/ImageCard/ImageCard.test.jsx
  packages/react/src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
  packages/react/src/components/ImageCard/_image-card.scss
  packages/react/src/components/Page/PageSwitcher.jsx
  packages/react/src/components/SuiteHeader/SuiteHeader.story.jsx
  packages/react/src/components/Table/TableDetailWizard/__snapshots__/TableDetailWizard.story.storyshot
  packages/react/src/components/WizardInline/WizardHeader/WizardHeader.jsx
  packages/react/src/components/WizardInline/WizardLeftSidebar/WizardSidebar.jsx
  packages/react/src/components/WizardInline/__snapshots__/WizardInline.story.storyshot
  packages/react/src/components/WizardInline/_wizard-inline.scss
  packages/react/src/styles.scss
Labels: status: ready to merge 🎉

#2219 fix(value-card): use auto positioning tooltip
  packages/react/src/components/Card/DataStateRenderer.jsx
  packages/react/src/hooks/usePopoverPositioning.jsx
Labels: status: ready to merge 🎉

#2197 feat(card): add card implementation for Angular
  .prettierignore
  packages/angular/package.json
  packages/angular/src/button/button.directive.spec.ts
  packages/angular/src/button/button.directive.ts
  packages/angular/src/button/button.module.ts
  packages/angular/src/button/button.stories.ts
  packages/angular/src/button/button.types.ts
  packages/angular/src/button/index.ts
  packages/angular/src/card/card-content.component.ts
  packages/angular/src/card/card-date-range.component.ts
  packages/angular/src/card/card-header.component.ts
  packages/angular/src/card/card-title.component.ts
  packages/angular/src/card/card-toolbar-action.directive.ts
  packages/angular/src/card/card-toolbar.component.ts
  packages/angular/src/card/card.component.spec.ts
  packages/angular/src/card/card.component.ts
  packages/angular/src/card/card.module.ts
  packages/angular/src/card/card.service.spec.ts
  packages/angular/src/card/card.service.ts
  packages/angular/src/card/card.stories.ts
  packages/angular/src/card/index.ts
  packages/angular/src/card/package.json
  packages/angular/src/index.stories.ts
  packages/angular/src/index.ts
  packages/angular/src/package.json
  packages/angular/tsconfig.spec.json
  packages/styles/package.json
  yarn.lock
Labels: status: ready to merge 🎉

#2223 chore(angular): ensure publishConfig and version is synced
  packages/angular/package.json
  packages/angular/scripts/sync-version.js
  packages/angular/src/package.json
Labels: status: ready to merge 🎉

#2218 fix(tablecard): do not preformat the timestamp columns only do it on render
  packages/react/src/components/Dashboard/Dashboard.story.jsx
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/TableCard/TableCard.jsx
  packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
  packages/react/src/components/TableCard/tableCardUtils.jsx
  packages/react/src/components/TableCard/tableCardUtils.test.jsx
Labels: status: ready to merge 🎉

#2216 fix(suiteheader): redirect statements that open links in new tabs were not using the correct parameters.
  packages/react/src/components/SuiteHeader/SuiteHeader.jsx
  packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.test.jsx
  yarn.lock
Labels: status: ready to merge 🎉

#2231 fix(table): include search.defaultValue in filtering logic
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/Table.story.jsx
Labels: status: ready to merge 🎉

#2233 fix(file-uploader): fix broken example story
  packages/react/src/components/FileUploader/FileUploader.story.jsx
Labels: status: ready to merge 🎉

#2239 fix(build): change the index source in package.json
  packages/react/package.json
Labels: status: ready to merge 🎉

#2235 fix(timeseries): support 0 values in the line chart
  packages/react/src/components/TimeSeriesCard/timeSeriesUtils.js
Labels: status: ready to merge 🎉

#2234 fix(wizard-modal): do not pass onBack to ComposedModal
  packages/react/src/components/WizardModal/WizardModal.jsx
  packages/react/src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
Labels: status: ready to merge 🎉

#2256 Expose legend position prop on bar and time cards
  packages/react/src/components/BarChartCard/BarChartCard.jsx
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2237 fix(time-series-card): use number instead of min/max for ticks
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
Labels: status: ready to merge 🎉

#2259 fix(dashboard-editor): internationalization fixes
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.test.jsx
  packages/react/src/components/CardEditor/CardEditor.test.jsx
  packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2236 fix(list-item): stop propagation for selectable categories
  packages/react/src/components/List/HierarchyList/HierarchyList.story.jsx
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/components/List/ListItem/ListItem.jsx
Labels: status: ready to merge 🎉

#2255 feat(repo): export settings to consumers
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/src/index.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2254 feat(dashboard-editor): add decimal precision to ImageCards
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
  packages/react/src/components/CardEditor/CardEditForm/_card-edit-form.scss
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.test.jsx
  packages/react/src/components/HotspotEditorModal/hooks/hotspotStateHook.js
Labels: status: ready to merge 🎉

#2241 fix(dashboard-editor): always use dataSourceId in selectedData array
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
Labels: status: ready to merge 🎉

#2240 fix(bar-chart-card): prop error on grouped BarChartCard
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/editorUtils.jsx
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2270 fix(cardrenderer): custom and default cards should be resizable
  packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorCardRenderer.jsx
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
Labels: status: ready to merge 🎉

#2224 chore(table): initial addition of documentation
  packages/react/src/components/Table/README.md
  packages/react/src/components/Table/Table.story.jsx
Labels: status: ready to merge 🎉

#2271 chore(testing): split up react and angular test jobs
  .github/workflows/test.yml
Labels: impact: high :scream:, status: ready to merge 🎉

#2232 fix(list-item): add aria-label and title to expand button
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/components/List/ListItem/ListItem.jsx
  packages/react/src/components/List/ListItem/ListItem.test.jsx
  packages/react/src/components/List/ListItem/__snapshots__/ListItem.story.storyshot
  packages/react/src/components/List/__snapshots__/List.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/SelectUsersModal/__snapshots__/SelectUsersModal.story.storyshot
Labels: status: ready to merge 🎉

#2228 fix(progressindicator): add title attribute for text ellipsis
  packages/react/src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
  packages/react/src/components/ProgressIndicator/ProgressIndicator.jsx
  packages/react/src/components/ProgressIndicator/ProgressIndicator.test.jsx
  packages/react/src/components/ProgressIndicator/__snapshots__/ProgressIndicator.story.storyshot
  packages/react/src/components/Table/TableDetailWizard/__snapshots__/TableDetailWizard.story.storyshot
  packages/react/src/components/WizardInline/__snapshots__/WizardInline.story.storyshot
  packages/react/src/components/WizardModal/WizardModal.test.jsx
  packages/react/src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
Labels: status: ready to merge 🎉

#2208 fix(pagetitlebar): fix some alignment/spacing issues
  packages/react/src/components/DashboardEditor/DashboardEditorHeader/__snapshots__/DashboardEditorHeader.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/NavigationBar/__snapshots__/NavigationBar.story.storyshot
  packages/react/src/components/PageTitleBar/PageTitleBar.jsx
  packages/react/src/components/PageTitleBar/PageTitleBar.story.jsx
  packages/react/src/components/PageTitleBar/PageTitleBar.test.jsx
  packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
  packages/react/src/components/PageTitleBar/_page-title-bar.scss
  packages/react/src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
  packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
  packages/react/src/components/TileCatalogNew/TileCatalogNew.story.jsx
  packages/react/src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/components/WizardInline/__snapshots__/WizardInline.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2276 fix(customcard): rendering of custom card was incorrect
  packages/react/package.json
  packages/react/src/components/Card/Card.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  yarn.lock
Labels: status: ready to merge 🎉

#2217 feat(menu-button): new MenuButton component
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/package.json
  packages/react/src/components/Button/Button.jsx
  packages/react/src/components/MenuButton/MenuButton.jsx
  packages/react/src/components/MenuButton/MenuButton.story.jsx
  packages/react/src/components/MenuButton/MenuButton.test.jsx
  packages/react/src/components/MenuButton/SingleMenuButton.jsx
  packages/react/src/components/MenuButton/SplitMenuButton.jsx
  packages/react/src/components/MenuButton/__snapshots__/MenuButton.story.storyshot
  packages/react/src/components/MenuButton/_menu-button.scss
  packages/react/src/components/MenuButton/utils.js
  packages/react/src/components/StorybookSnapshots.test.js
  packages/react/src/index.js
  packages/react/src/styles.scss
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉
