Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2021-02, with the labels that each got.

#1985 fix(dashboardeditorcardrenderer): tell the custom card to render its buttons
  packages/react/src/components/DashboardEditor/DashboardEditorCardRenderer.jsx
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
Labels: status: ready to merge 🎉

#1995 fix(dashboardeditor): support passing custom icon callback
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorCardRenderer.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorCardRenderer.test.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1993 fix(DashboardEditor): check min and max before applying the number input value
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ValueCardFormItems/ValueCardFormSettings.jsx
  packages/react/src/components/HotspotEditorModal/HotspotTextStyleTab/HotspotTextStyleTab.jsx
  packages/react/src/utils/componentUtilityFunctions.js
Labels: status: ready to merge 🎉

#1971 TableCard editor aggregation support
  packages/react/src/components/CardEditor/CardEditForm/CardEditForm.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditForm.test.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.test.jsx
  packages/react/src/components/DashboardEditor/editorUtils.jsx
  packages/react/src/components/DashboardEditor/editorUtils.test.jsx
Labels: status: ready to merge 🎉

#1981 feat(SuiteHeader): Adding support for different types in some i18n properties in SuiteHeader component
  packages/react/src/components/SuiteHeader/SuiteHeader.jsx
  packages/react/src/components/SuiteHeader/SuiteHeader.story.jsx
  packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderLogoutModal/SuiteHeaderLogoutModal.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderLogoutModal/__snapshots__/SuiteHeaderLogoutModal.story.storyshot
  packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
  packages/react/src/components/SuiteHeader/i18n/index.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2001 Remove search bar on preview mode
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/TableCard/TableCard.jsx
  packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
  packages/react/src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
Labels: status: ready to merge 🎉

#1992 chore: move components out of experimental
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/src/components/ComboBox/ComboBox.jsx
  packages/react/src/components/ComboBox/ComboBox.story.jsx
  packages/react/src/components/ComboBox/__snapshots__/ComboBox.story.storyshot
  packages/react/src/components/DateTimePicker/DateTimePicker.story.jsx
  packages/react/src/components/DateTimePicker/__snapshots__/DateTimePicker.story.storyshot
  packages/react/src/components/List/HierarchyList/HierarchyList.story.jsx
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/components/List/List.story.jsx
  packages/react/src/components/List/ListItem/ListItem.story.jsx
  packages/react/src/components/List/ListItem/__snapshots__/ListItem.story.storyshot
  packages/react/src/components/List/SimpleList/SimpleList.story.jsx
  packages/react/src/components/List/SimpleList/__snapshots__/SimpleList.story.storyshot
  packages/react/src/components/List/__snapshots__/List.story.storyshot
  packages/react/src/components/TileCatalogNew/TileCatalogNew.story.jsx
  packages/react/src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
  packages/react/src/index.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1996 fix(DashboardEditor): add correct labels
  CHANGELOG.md
  lerna.json
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/_card-edit-form.scss
  packages/react/src/components/CardEditor/CardEditor.story.jsx
  packages/react/src/components/ComboBox/ComboBox.jsx
  packages/react/src/components/ComboBox/ComboBox.story.jsx
  packages/react/src/components/ComboBox/__snapshots__/ComboBox.story.storyshot
  packages/react/src/components/DashboardEditor/editorUtils.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.story.jsx
  packages/react/src/components/DateTimePicker/__snapshots__/DateTimePicker.story.storyshot
  packages/react/src/components/List/HierarchyList/HierarchyList.story.jsx
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/components/List/List.story.jsx
  packages/react/src/components/List/ListItem/ListItem.story.jsx
  packages/react/src/components/List/ListItem/__snapshots__/ListItem.story.storyshot
  packages/react/src/components/List/SimpleList/SimpleList.story.jsx
  packages/react/src/components/List/SimpleList/__snapshots__/SimpleList.story.storyshot
  packages/react/src/components/List/__snapshots__/List.story.storyshot
  packages/react/src/components/TileCatalogNew/TileCatalogNew.story.jsx
  packages/react/src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
  packages/react/src/index.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1982 feat(editor): include onCardJsonPreview callback for the consumer
  packages/react/src/components/CardEditor/CardEditForm/CardEditForm.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditForm.test.jsx
  packages/react/src/components/CardEditor/CardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1975 feat(rulebuilder): intial addition of rule builder
  packages/react/src/components/RuleBuilder/GroupLogic.jsx
  packages/react/src/components/RuleBuilder/GroupLogic.test.jsx
  packages/react/src/components/RuleBuilder/Rule.jsx
  packages/react/src/components/RuleBuilder/Rule.test.jsx
  packages/react/src/components/RuleBuilder/RuleBuilderEditor.jsx
  packages/react/src/components/RuleBuilder/RuleBuilderEditor.story.jsx
  packages/react/src/components/RuleBuilder/RuleBuilderEditor.test.jsx
  packages/react/src/components/RuleBuilder/RuleBuilderHeader.jsx
  packages/react/src/components/RuleBuilder/RuleBuilderHeader.test.jsx
  packages/react/src/components/RuleBuilder/RuleBuilderPropTypes.js
  packages/react/src/components/RuleBuilder/RuleValueField.jsx
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilderEditor.story.storyshot
  packages/react/src/components/RuleBuilder/_rulebuilder.scss
  packages/react/src/components/RuleBuilder/utils.js
  packages/react/src/components/RuleBuilder/utils.test.js
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/styles.scss
Labels: status: ready to merge 🎉

#1999 Fix(timeseriescard/barchartcard): support the decimalPrecision prop to control the y-axis and tooltip values
  packages/react/src/components/BarChartCard/BarChartCard.jsx
  packages/react/src/components/BarChartCard/__snapshots__/BarChartCard.story.storyshot
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormSettings.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormSettings.test.jsx
  packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  packages/react/src/components/DashboardEditor/editorUtils.jsx
  packages/react/src/components/RuleBuilder/RuleBuilderEditor.test.jsx
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
  packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  packages/react/src/utils/cardUtilityFunctions.js
Labels: status: one more review 👀, status: ready to merge 🎉

#2007 fix(HierarchyList): add isLargeRow prop
  packages/react/src/components/List/HierarchyList/HierarchyList.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.story.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.test.jsx
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1994 fix(storybook) Add default max-depth parameter storybook/addon-actions config
  packages/react/.storybook/preview.js
Labels: status: ready to merge 🎉

#2012 fix(HierarchyList): scroll only if needed and support secondary nodes
  packages/react/package.json
  packages/react/src/components/List/HierarchyList/HierarchyList.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.story.jsx
  packages/react/src/components/List/List.jsx
  packages/react/src/components/List/ListItem/ListItem.jsx
  packages/react/src/components/List/SimpleList/SimpleList.jsx
  packages/react/src/components/RuleBuilder/RuleBuilderEditor.test.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge 🎉

#2008 feat(suiteheader): Support for loading states and extensibility for Help, Profile and Applications menu items
  packages/react/src/components/SuiteHeader/SuiteHeader.jsx
  packages/react/src/components/SuiteHeader/SuiteHeader.story.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.story.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.test.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/__snapshots__/SuiteHeaderAppSwitcher.story.storyshot
  packages/react/src/components/SuiteHeader/SuiteHeaderLogoutModal/__snapshots__/SuiteHeaderLogoutModal.story.storyshot
  packages/react/src/components/SuiteHeader/SuiteHeaderProfile/SuiteHeaderProfile.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderProfile/SuiteHeaderProfile.story.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderProfile/SuiteHeaderProfile.test.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderProfile/__snapshots__/SuiteHeaderProfile.story.storyshot
  packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
  packages/react/src/components/SuiteHeader/_suite-header.scss
  packages/react/src/components/SuiteHeader/i18n/index.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2015 fix(valuecard): precision is at the attribute level not card level
  packages/react/src/components/ValueCard/Attribute.jsx
  packages/react/src/components/ValueCard/ValueCard.jsx
  packages/react/src/components/ValueCard/ValueCard.test.jsx
  packages/react/src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge 🎉

#2021 fix(dashboard-grid): remove the merge error file in the wrong path
  .vscode/launch.json
  src/components/Dashboard/_dashboard-grid.scss
Labels: status: ready to merge 🎉

#2027 fix(tablecard): in the table card I need to be able to add timestamp type data items
  .vscode/launch.json
  packages/react/src/components/BarChartCard/barChartUtils.js
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.test.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
  packages/react/src/components/DashboardEditor/editorUtils.jsx
  packages/react/src/components/DashboardEditor/editorUtils.test.jsx
Labels: status: one more review 👀, status: ready to merge 🎉

#2023 fix(dataitemmodal): need to hide the grain if no aggregator is selected
  .vscode/launch.json
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.test.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
Labels: status: one more review 👀, status: ready to merge 🎉

#2029 fix(dataseriesformcontent): it should not change existing elements
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.test.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.test.jsx
  packages/react/src/components/CardEditor/CardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/editorUtils.jsx
  packages/react/src/components/DashboardEditor/editorUtils.test.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2038 fix(tablecard): show column label in threshold column
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.test.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
  packages/react/src/components/DashboardEditor/editorUtils.jsx
  packages/react/src/components/DashboardEditor/editorUtils.test.jsx
  packages/react/src/components/TableCard/TableCard.jsx
Labels: status: ready to merge 🎉

#2053 fix(rulebuilder): pad id generator to fix intermittent failing test
  packages/react/src/components/RuleBuilder/RuleBuilderEditor.test.jsx
  packages/react/src/components/RuleBuilder/utils.test.js
Labels: status: ready to merge 🎉

#2044 feat(dashboardeditor): scroll to added cards
  packages/react/src/components/Dashboard/_dashboard-grid.scss
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.test.jsx
  packages/react/src/components/DashboardEditor/_dashboard-editor.scss
  packages/react/src/components/StorybookSnapshots.test.js
  packages/react/src/styles.scss
Labels: status: ready to merge 🎉

#2043 feat(dashboardeditor): improve performance while editing
  packages/react/src/components/BarChartCard/BarChartCard.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditForm.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/BarChartDataSeriesContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/BarChartDataSeriesContent.test.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.test.jsx
  packages/react/src/components/CardEditor/CardEditForm/_card-edit-form.scss
  packages/react/src/components/CardEditor/CardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.test.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorCardRenderer.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorCardRenderer.test.jsx
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/DashboardEditor/editorUtils.jsx
  packages/react/src/components/DashboardEditor/editorUtils.test.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorModal.test.jsx
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  packages/react/src/utils/cardUtilityFunctions.js
Labels: status: ready to merge 🎉

#2050 fix(DashboardEditor): no small size for alert cards
  packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/constants/LayoutConstants.js
Labels: status: ready to merge 🎉

#2056 fix(tablecard): link template
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.test.jsx
  packages/react/src/components/ImageCard/ImageHotspots.jsx
  packages/react/src/components/ImageCard/ImageHotspots.test.jsx
  packages/react/src/components/TableCard/tableCardUtils.jsx
  packages/react/src/components/TableCard/tableCardUtils.test.jsx
Labels: status: ready to merge 🎉

#2018 feat(SelectUsers) Add SelectUsers modal
  packages/react/src/components/SelectUsersModal/SelectUsersModal.jsx
  packages/react/src/components/SelectUsersModal/SelectUsersModal.story.jsx
  packages/react/src/components/SelectUsersModal/SelectUsersModal.test.jsx
  packages/react/src/components/SelectUsersModal/__snapshots__/SelectUsersModal.story.storyshot
  packages/react/src/components/SelectUsersModal/_select-users-modal.scss
  packages/react/src/styles.scss
Labels: status: ready to merge 🎉

#2017 fix(Hierarchylist): style, i18n, selection
  packages/react/src/components/List/HierarchyList/HierarchyList.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.story.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.test.jsx
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/components/List/List.story.jsx
  packages/react/src/components/List/ListItem/_list-item.scss
  packages/react/src/components/List/SimpleList/SimpleList.jsx
  packages/react/src/components/List/__snapshots__/List.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1983 chore: skip running release if the committer is automated
  .github/ISSUE_TEMPLATE/feature-request-or-enhancement.md
  .github/ISSUE_TEMPLATE/new-component-proposal.md
  .github/workflows/publish.yml
  .prettierignore
  .prettierrc.json
  package.json
  scripts/release.sh
Labels: status: ready to merge 🎉

#2054 Format nested ternary operation to normal if else for better readability
  packages/react/src/components/TimeSeriesCard/timeSeriesUtils.js
Labels: status: ready for code owner's review, status: ready to merge 🎉
