Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2021-06, with the labels that each got.

#2356 Add getDefaultCard prop to editor
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorHeader/__snapshots__/DashboardEditorHeader.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/FileDrop/__snapshots__/FileDrop.story.storyshot
  packages/react/src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2355 fix(tablecard): allow row-specific and cardVariables prop
  packages/react/src/components/TableCard/TableCard.jsx
  packages/react/src/components/TableCard/TableCard.story.jsx
  packages/react/src/components/TableCard/TableCard.test.jsx
  packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
  packages/react/src/components/TableCard/tableCardUtils.jsx
  packages/react/src/components/TableCard/tableCardUtils.test.jsx
  packages/react/src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
  packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  packages/react/src/utils/__tests__/cardUtilityFunctions.test.jsx
  packages/react/src/utils/cardUtilityFunctions.js
Labels: status: ready to merge 🎉

#2353 fix(hotspot): use carbon colors and mixins for hotspot styles
  packages/react/src/components/ImageCard/_hotspot.scss
Labels: status: ready to merge 🎉

#2369 feat(dashboardeditor): add edit data item button to the dashboard editor
  packages/react/src/components/CardEditor/CardEditForm/CardEditForm.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/_card-edit-form.scss
  packages/react/src/components/CardEditor/CardEditor.jsx
  packages/react/src/components/CardEditor/CardEditor.test.jsx
  packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  packages/react/src/components/CardEditor/_card-editor.scss
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.test.jsx
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/ListBuilder/ListBuilder.story.jsx
  packages/react/src/components/ListBuilder/__snapshots__/ListBuilder.story.storyshot
  packages/react/src/components/MenuButton/MenuButton.story.jsx
  packages/react/src/components/MenuButton/__snapshots__/MenuButton.story.storyshot
  packages/react/src/components/TearSheet/TearSheet.story.jsx
  packages/react/src/components/TearSheet/__snapshots__/TearSheet.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2266 Add angular tabs
  .editorconfig
  .vscode/settings.json
  packages/angular/angular.json
  packages/angular/package.json
  packages/angular/src/card/card-content.component.ts
  packages/angular/src/tabs/index.ts
  packages/angular/src/tabs/tab-action.directive.ts
  packages/angular/src/tabs/tab-actions.component.ts
  packages/angular/src/tabs/tab-controller.class.ts
  packages/angular/src/tabs/tab-dropdown.component.ts
  packages/angular/src/tabs/tab.component.ts
  packages/angular/src/tabs/tab.interface.ts
  packages/angular/src/tabs/tabs.component.ts
  packages/angular/src/tabs/tabs.module.ts
  packages/angular/src/tabs/tabs.stories.ts
  packages/angular/src/toolkit/sortable-list/sortable-list-model.class.ts
  packages/angular/src/toolkit/table-settings/table-settings-model.class.ts
  packages/angular/src/toolkit/table-settings/table-settings-pane.class.ts
  packages/angular/src/toolkit/table/sterling-table.component.ts
  packages/angular/tsconfig.json
  yarn.lock
Labels: package: angular, status: ready to merge 🎉

#2385 fix(hotspoteditormodal): fixed broken stories
  packages/react/src/components/HotspotEditorModal/DynamicHotspotSourcePicker/DynamicHotspotSourcePicker.story.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.story.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.test.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/__snapshots__/HotspotEditorDataSourceTab.story.storyshot
  packages/react/src/components/HotspotEditorModal/HotspotEditorModal.story.jsx
Labels: status: one more review 👀

#2330 Add angular button menu
  .github/CODEOWNERS
  packages/angular/package.json
  packages/angular/src/button-menu/button-menu.component.ts
  packages/angular/src/button-menu/button-menu.module.ts
  packages/angular/src/button-menu/button-menu.stories.ts
  packages/angular/src/button-menu/index.ts
  packages/angular/src/button-menu/package.json
  packages/angular/src/index.ts
  packages/react/src/components/MenuButton/SingleMenuButton.jsx
  packages/react/src/components/MenuButton/SplitMenuButton.jsx
  packages/react/src/components/MenuButton/__snapshots__/MenuButton.story.storyshot
  packages/react/src/components/MenuButton/_menu-button.scss
  packages/styles/src/components/Accordion/_accordion.scss
  packages/styles/src/components/Card/_card.scss
  packages/styles/src/components/CardEditor/CardEditForm/_card-edit-form.scss
  packages/styles/src/components/CardEditor/_card-editor.scss
  packages/styles/src/components/ImageCard/_hotspot.scss
  packages/styles/src/components/MapCard/_legend.scss
  packages/styles/src/components/MapCard/_map-card.scss
  packages/styles/src/components/MapCard/_scrolling-controls.scss
  packages/styles/src/components/MapCard/_zoom-control.scss
  packages/styles/src/components/MapCard/storyFiles/mapbox-example.scss
  packages/styles/src/components/MapCard/storyFiles/open-layers-example.scss
  packages/styles/src/components/MenuButton/_menu-button.scss
  packages/styles/src/components/Table/TableHead/_table-head.scss
  packages/styles/src/styles.scss
  scripts/storybook.js
  yarn.lock
Labels: package: angular, status: ready to merge 🎉

#2380 2366 MapCard related content panels and react-dnd upgrade
  packages/react/package.json
  packages/react/src/components/MapCard/MapCard.jsx
  packages/react/src/components/MapCard/MapCard.story.jsx
  packages/react/src/components/MapCard/MapCard.test.jsx
  packages/react/src/components/MapCard/README.md
  packages/react/src/components/MapCard/storyFiles/DragPanel.jsx
  packages/react/src/components/MapCard/storyFiles/MapboxDragPanelExample.jsx
  packages/react/src/components/MapCard/storyFiles/MapboxExample.jsx
  packages/react/src/components/MapCard/storyFiles/drag-panel.scss
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/hooks/useDNDProviderElement.jsx
  packages/react/src/utils/DragAndDropUtils.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge 🎉

#2394 fix(dataseriesformitemmodal): allowed isLarge prop
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.test.jsx
Labels: status: ready to merge 🎉

#2412 chore(repo): replace node-sass with sass package
  packages/react/package.json
  yarn.lock
Labels: status: ready to merge 🎉

#2420 feat(walkme): Wrapper component for Walkme content bundle
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/jest.config.js
  packages/react/package.json
  packages/react/src/components/SuiteHeader/SuiteHeader.jsx
  packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
  packages/react/src/components/Walkme/README.md
  packages/react/src/components/Walkme/Walkme.jsx
  packages/react/src/components/Walkme/Walkme.test.jsx
  packages/react/src/index.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge 🎉

#2402 fix(hotspoteditortooltiptab): fix for selected color not showing
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/HotspotEditorTooltipTab.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/HotspotEditorTooltipTab.story.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2425 fix(datetimepicker): listen to locale and initialize dayjs with it
  packages/react/src/components/Card/__snapshots__/Card.story.storyshot
  packages/react/src/components/DateTimePicker/DateTimePicker.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.story.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.test.jsx
  packages/react/src/components/DateTimePicker/__snapshots__/DateTimePicker.story.storyshot
  packages/react/src/components/List/__snapshots__/List.story.storyshot
Labels: status: ready for code owner's review

#2419 chore(build): fix netlify builds for Angular
  scripts/storybook.js
Labels: status: ready to merge 🎉

#2429 fix(repo): verison bump to fix publish failures
  packages/react/package.json
  yarn.lock
Labels: status: ready to merge 🎉

#2428 fix(hotspoteditordatasourcetab): fixed custom labels for multiselect
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.story.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.test.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/__snapshots__/HotspotEditorDataSourceTab.story.storyshot
  packages/react/src/components/HotspotEditorModal/HotspotEditorModal.test.jsx
Labels: status: ready to merge 🎉

#2427 fix(hotspoteditormodal): handle element content in hotspots
  packages/react/src/components/ColorDropdown/ColorDropdown.jsx
  packages/react/src/components/ColorDropdown/ColorDropdown.story.jsx
  packages/react/src/components/ColorDropdown/ColorDropdown.test.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorModal.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorModal.story.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorModal.test.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/HotspotEditorTooltipTab.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/HotspotEditorTooltipTab.test.jsx
  packages/react/src/components/HotspotEditorModal/HotspotTextStyleTab/HotspotTextStyleTab.jsx
  packages/react/src/components/HotspotEditorModal/HotspotTextStyleTab/HotspotTextStyleTab.test.jsx
  packages/react/src/components/HotspotEditorModal/HotspotTextStyleTab/_hotspot-text-style-tab.scss
  packages/react/src/components/HotspotEditorModal/__snapshots__/HotspotEditorModal.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉
