Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2021-12, with the labels that each got.

#3083 fix(table): properly round maxPages to prevent decimals
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/Table.mdx
  packages/react/src/components/Table/Table.test.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3084 style(button): fix rtl issues with ghost, loader, and sets
  packages/react/src/components/Button/_button.scss
Labels: status: ready to merge 🎉

#3081 feat(hierarchy-list): add controlled expandedIds prop
  packages/react/src/components/List/HierarchyList/HierarchyList.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.story.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.test.jsx
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3096 chore(repo): upgrade cypress and related plugins/images
  .github/workflows/codesandbox.yml
  .github/workflows/test.yml
  Dockerfile
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-TableCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-ValueCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-1.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-2.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-3.png
  packages/react/cypress.json
  packages/react/package.json
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.test.e2e.jsx
  yarn.lock
Labels: status: ready to merge 🎉

#3097 fix bug for removing ID from JSON Editor
  packages/react/src/components/CardEditor/CardEditForm/CardEditForm.jsx
Labels: status: ready to merge 🎉

#3093 refactor(table): make preserveColumnWidths:true the default, deprecate false
  packages/react/src/components/Table/StatefulTable.story.jsx
  packages/react/src/components/Table/StatefulTable.test.jsx
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/Table.mdx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/Table.test.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: version: 3, status: ready to merge 🎉

#3023 Update carbon-componts version
  package.json
  packages/angular/.storybook/addons.js
  packages/angular/.storybook/tsconfig.json
  packages/angular/angular.json
  packages/angular/package.json
  packages/angular/src/button-menu/button-menu.component.ts
  packages/angular/src/button-menu/button-menu.stories.ts
  packages/angular/src/side-panel/side-panel.component.ts
  packages/angular/src/table/head/table-head-cell.component.ts
  packages/angular/src/table/head/table-head.component.ts
  packages/angular/src/table/table.component.ts
  packages/angular/src/table/table.scss
  packages/monorepo-utils/package.json
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-TableCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-1.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-2.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-3.png
  packages/react/src/components/SidePanel/_side-panel.scss
  packages/react/src/components/TableMultiline/table-head-cell.scss
  packages/react/src/components/TableMultiline/table-head.scss
  packages/react/src/components/TableMultiline/table.scss
  packages/react/src/styles.scss
  packages/styles/package.json
  packages/styles/src/components/ComboBox/_combo-box.scss
  packages/styles/src/components/DataTable/_data-table.scss
  packages/styles/src/components/DateTimePicker/_date-time-picker.scss
  packages/styles/src/components/DateTimePicker/_date-time-pickerv2.scss
  packages/styles/src/components/EmptyState/_emptystate.scss
  packages/styles/src/components/Header/_header.scss
  packages/styles/src/components/IconSwitch/_icon-switch.scss
  packages/styles/src/components/List/ListItem/_list-item.scss
  packages/styles/src/components/List/_list.scss
  packages/styles/src/components/PageTitleBar/_page-title-bar.scss
  packages/styles/src/components/RuleBuilder/_rule-builder.scss
  packages/styles/src/components/SideNav/_side-nav.scss
  packages/styles/src/components/SidePanel/_side-panel.scss
  packages/styles/src/components/Table/TableBody/TableBodyLoadMoreRow/_table-body-load-more-row.scss
  packages/styles/src/components/Table/TableFoot/_table-foot.scss
  packages/styles/src/components/Table/TableHead/ColumnGrouping/_column-grouping.scss
  packages/styles/src/components/Table/TableHead/FilterHeaderRow/_filter-header-row.scss
  packages/styles/src/components/Table/TableHead/_table-head.scss
  packages/styles/src/components/Table/TableSkeletonWithHeaders/_table-skeleton-with-headers.scss
  packages/styles/src/components/Table/_table.scss
  packages/styles/src/components/TableMultiline/table-head-cell.scss
  packages/styles/src/components/TableMultiline/table-head.scss
  packages/styles/src/components/TableMultiline/table.scss
  packages/styles/src/components/TileCatalogNew/_tile-catalog.scss
  packages/styles/src/components/TimePickerSpinner/_time-picker-spinner.scss
  packages/styles/src/components/ValueCard/_attribute.scss
  packages/styles/src/components/ValueCard/_value-renderer.scss
  packages/styles/src/globals/_mixins.scss
  packages/styles/src/styles.scss
  yarn.lock
Labels: status: ready to merge 🎉

#3076 feat(table): add toolbarActions to add actions to table toolbar or its overflow menu
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/Table.mdx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/Table.test.jsx
  packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
  packages/react/src/components/Table/TablePropTypes.js
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
  packages/react/src/components/Table/TableToolbar/_table-toolbar.scss
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/Table/tableUtilities.jsx
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/hooks/useDynamicOverflowMenuItems.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3103 fix(table): segregate angular styles from react table
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-TableCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-1.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-2.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-3.png
  packages/react/src/components/TableMultiline/table-head-cell.scss
  packages/react/src/components/TableMultiline/table-head.scss
Labels: status: ready to merge 🎉

#3073 2603 column customization
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/jest.config.js
  packages/react/package.json
  packages/react/src/components/List/HierarchyList/HierarchyList.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.test.jsx
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/components/List/List.jsx
  packages/react/src/components/List/List.story.jsx
  packages/react/src/components/List/List.test.jsx
  packages/react/src/components/List/ListContent/ListContent.jsx
  packages/react/src/components/List/ListHeader/ListHeader.jsx
  packages/react/src/components/List/ListItem/_list-item.scss
  packages/react/src/components/List/VirtualListContent/VirtualListContent.jsx
  packages/react/src/components/ListBuilder/ListBuilder.jsx
  packages/react/src/components/ListBuilder/ListBuilder.mdx
  packages/react/src/components/ListBuilder/ListBuilder.story.jsx
  packages/react/src/components/ListBuilder/ListBuilder.test.jsx
  packages/react/src/components/ListBuilder/__snapshots__/ListBuilder.story.storyshot
  packages/react/src/components/ListBuilder/_list-builder.scss
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/SelectUsersModal/SelectUsersModal.jsx
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/Table.mdx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/TableColumnCustomizationModal/AsyncTableColumnCustomizationModal.jsx
  packages/react/src/components/Table/TableColumnCustomizationModal/TableColumnCustomizationModal.jsx
  packages/react/src/components/Table/TableColumnCustomizationModal/TableColumnCustomizationModal.mdx
  packages/react/src/components/Table/TableColumnCustomizationModal/TableColumnCustomizationModal.story.jsx
  packages/react/src/components/Table/TableColumnCustomizationModal/TableColumnCustomizationModal.test.e2e.jsx
  packages/react/src/components/Table/TableColumnCustomizationModal/TableColumnCustomizationModal.test.jsx
  packages/react/src/components/Table/TableColumnCustomizationModal/TableColumnCustomizationModalContent.mdx
  packages/react/src/components/Table/TableColumnCustomizationModal/__snapshots__/TableColumnCustomizationModal.story.storyshot
  packages/react/src/components/Table/TableColumnCustomizationModal/_table-column-customization-modal.scss
  packages/react/src/components/Table/TableColumnCustomizationModal/tableColumnCustomizationTestUtils.js
  packages/react/src/components/Table/TableColumnCustomizationModal/visibilityToggleHook.jsx
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/index.js
  packages/react/src/styles.scss
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3105 3100 list inconsistent checkbox behaviour
  packages/react/src/components/List/List.story.jsx
Labels: status: ready to merge 🎉

#3089 Rule builder
  packages/angular/src/rule-builder-index.ts
  packages/angular/src/rule-builder/package.json
  packages/angular/src/rule-builder/rule-builder-group-logic.component.ts
  packages/angular/src/rule-builder/rule-builder-header.component.ts
  packages/angular/src/rule-builder/rule-builder.component.ts
  packages/angular/src/rule-builder/rule-builder.module.ts
  packages/angular/src/rule-builder/rule-builder.stories.ts
  packages/angular/src/rule-builder/rule.component.ts
  packages/angular/src/rule-builder/utils.ts
Labels: status: ready to merge 🎉, package: angular

#3106 feat(repo): fix tooltip not closing on escape by upgrade carbon to 10.49/7.49.1
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/package.json
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/__snapshots__/ThresholdsFormItem.story.storyshot
  packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/__snapshots__/HotspotEditorTooltipTab.story.storyshot
  packages/react/src/components/ImageCard/__snapshots__/ImageHotspots.story.storyshot
  packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
  packages/react/src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilderEditor.story.storyshot
  packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge 🎉

#3138 fix(rule-builder): export rule-builder so it can be used
  packages/angular/src/index.ts
Labels: status: ready to merge 🎉

#3126 fix(table-view-dropdown): fix [Object object] showing in title
  packages/react/src/components/Table/TableViewDropdown/TableViewDropdown.jsx
Labels: status: ready to merge 🎉

#3135 chore(list-builder): fix story for complex nesting add users/groups
  packages/react/src/components/ListBuilder/ListBuilder.story.jsx
Labels: status: ready to merge 🎉

#3142 next round of `next` into `v3` upgrade to prep for automated PR merge.
  CHANGELOG.md
  lerna.json
  packages/angular/CHANGELOG.md
  packages/angular/package.json
  packages/angular/src/index.ts
  packages/angular/src/rule-builder-index.ts
  packages/angular/src/rule-builder/package.json
  packages/angular/src/rule-builder/rule-builder-group-logic.component.ts
  packages/angular/src/rule-builder/rule-builder-header.component.ts
  packages/angular/src/rule-builder/rule-builder.component.ts
  packages/angular/src/rule-builder/rule-builder.module.ts
  packages/angular/src/rule-builder/rule-builder.stories.ts
  packages/angular/src/rule-builder/rule.component.ts
  packages/angular/src/rule-builder/utils.ts
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/CHANGELOG.md
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-3.png
  packages/react/package.json
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/__snapshots__/ThresholdsFormItem.story.storyshot
  packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  packages/react/src/components/DataTable/_data-table.scss
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/__snapshots__/HotspotEditorTooltipTab.story.storyshot
  packages/react/src/components/ImageCard/__snapshots__/ImageHotspots.story.storyshot
  packages/react/src/components/List/List.story.jsx
  packages/react/src/components/ListBuilder/ListBuilder.story.jsx
  packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
  packages/react/src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilderEditor.story.storyshot
  packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/Table.test.jsx
  packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
  packages/react/src/components/Table/TableBody/TableBody.jsx
  packages/react/src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
  packages/react/src/components/Table/TableViewDropdown/TableViewDropdown.jsx
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: version: 3

#3137 fix(header): add isSideNavExpanded prop to fix aria-label for button
  packages/react/src/components/Header/Header.jsx
  packages/react/src/components/Header/Header.test.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3130 Nested table max-width prop
  packages/react/src/components/Card/__snapshots__/Card.story.storyshot
  packages/react/src/components/ComboChartCard/__snapshots__/ComboChartCard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
  packages/react/src/components/PieChartCard/__snapshots__/PieChartCard.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
  packages/react/src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
  packages/react/src/components/Table/TableBody/TableBodyRow/__snapshots__/TableBodyRow.story.storyshot
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
  packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
Labels: status: waiting for author's response 💬
