Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2021-05, with the labels that each got.

#2283 fix(ListHeader): should not have loading state
  packages/react/src/components/List/List.jsx
  packages/react/src/components/List/ListHeader/ListHeader.jsx
  yarn.lock
Labels: status: ready to merge 🎉

#2281 Dashboard editor custom card side bar
  packages/react/src/components/CardEditor/CardEditForm/CardEditForm.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditForm.test.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormSettings.jsx
  packages/react/src/components/CardEditor/CardGalleryList/CardGalleryList.jsx
  packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorCardRenderer.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorHeader/__snapshots__/DashboardEditorHeader.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/FileDrop/__snapshots__/FileDrop.story.storyshot
  packages/react/src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2309 fix(combo-box): allow item ids to be numbers
  packages/react/src/components/ComboBox/ComboBox.jsx
  packages/react/src/components/ComboBox/ComboBox.story.jsx
  packages/react/src/components/ComboBox/ComboBox.test.jsx
Labels: status: ready to merge 🎉

#2298 fix(list): page position on list of full height in fixed container
  packages/react/src/components/List/List.story.jsx
  packages/react/src/components/List/__snapshots__/List.story.storyshot
  packages/react/src/components/List/_list.scss
Labels: status: ready to merge 🎉

#2293 chore(repo): remove useDeepCompareEffect where possible
  packages/react/src/components/Dashboard/CardRenderer.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorCardRenderer.jsx
  packages/react/src/components/ImageCard/ImageHotspots.jsx
  packages/react/src/components/ImageGalleryModal/ImageGalleryModal.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.jsx
  packages/react/src/components/Table/TableHead/TableHead.jsx
  packages/react/src/components/TileCatalog/StatefulTileCatalog.jsx
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
  packages/react/src/hooks/usePrevious.jsx
Labels: status: ready for code owner's review

#2321 fix(dayjs): dynamic import needs .js
  packages/react/src/utils/dayjs.js
Labels: status: ready to merge 🎉

#2323 Update the release script to fix typo
  scripts/release.sh
Labels: status: ready to merge 🎉

#2279 chore(menu-button): documentation, add testid to wrapper
  packages/react/src/components/MenuButton/MenuButton.jsx
  packages/react/src/components/MenuButton/MenuButton.story.jsx
  packages/react/src/components/MenuButton/MenuButton.test.a11y.jsx
  packages/react/src/components/MenuButton/MenuButton.test.jsx
  packages/react/src/components/MenuButton/README.md
  packages/react/src/components/MenuButton/__snapshots__/MenuButton.story.storyshot
  packages/react/src/components/MenuButton/utils.js
Labels: status: ready to merge 🎉

#2280 fix(time-series-card): handle undefined element in tooltip
  packages/react/src/components/TimeSeriesCard/timeSeriesUtils.test.js
  packages/react/src/utils/cardUtilityFunctions.js
Labels: status: ready to merge 🎉

#2287 fix(dashboard-editor): prevent color collisions on TimeSeriesCards in DashboardEditor
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
  packages/react/src/components/DashboardEditor/editorUtils.jsx
Labels: status: ready to merge 🎉

#2277 feat(header): automatic overflow handling for header actions
  packages/react/src/components/Header/Header.jsx
  packages/react/src/components/Header/Header.story.jsx
  packages/react/src/components/Header/Header.test.jsx
  packages/react/src/components/Header/HeaderAction/HeaderAction.jsx
  packages/react/src/components/Header/HeaderAction/HeaderActionPanel.jsx
  packages/react/src/components/Header/HeaderActionGroup.jsx
  packages/react/src/components/Header/__snapshots__/Header.story.storyshot
  packages/react/src/components/Header/__snapshots__/Header.test.jsx.snap
  packages/react/src/components/Header/_header.scss
  packages/react/src/components/OverflowMenu/index.jsx
  packages/react/src/components/PageTitleBar/_page-title-bar.scss
  packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
  packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2346 fix(overflow-menu): use es import from carbon
  packages/react/src/components/FileUploader/stories/drop-container.jsx
  packages/react/src/components/OverflowMenu/index.jsx
  packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
Labels: status: ready to merge 🎉

#2310 fix(imagecard): set of small fixes to imagecard and the dashboardeditor
  packages/react/src/components/DashboardEditor/editorUtils.jsx
  packages/react/src/components/DashboardEditor/editorUtils.test.jsx
  packages/react/src/components/ImageCard/ImageHotspots.jsx
  packages/react/src/components/ImageCard/ImageHotspots.story.jsx
  packages/react/src/components/ImageCard/__snapshots__/ImageHotspots.story.storyshot
Labels: status: ready to merge 🎉

#2342 feat(timeseriescard): expose the thresholds for x and y axis for time series chart
  packages/react/package.json
  packages/react/src/components/StorybookSnapshots.test.js
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
  packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge 🎉

#2339 feat(dashboardeditor): support editable title widgets natively
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorHeader/DashboardEditorHeader.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorHeader/DashboardEditorHeader.test.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorHeader/__snapshots__/DashboardEditorHeader.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/PageTitleBar/PageTitleBar.jsx
  packages/react/src/components/PageTitleBar/PageTitleBar.story.jsx
  packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
  packages/react/src/components/PageTitleBar/_page-title-bar.scss
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2335 fix(suiteheader): Making the transition of “loading state” to “data ready state” in SuiteHeader seamless
  packages/react/src/components/SuiteHeader/SuiteHeader.jsx
  packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
  packages/react/src/components/SuiteHeader/_suite-header.scss
Labels: status: ready to merge 🎉

#2343 feat(tearsheet): new component
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/src/components/TearSheet/TearSheet.jsx
  packages/react/src/components/TearSheet/TearSheet.story.jsx
  packages/react/src/components/TearSheet/TearSheet.test.jsx
  packages/react/src/components/TearSheet/TearSheetWrapper.jsx
  packages/react/src/components/TearSheet/tear-sheet-wrapper.scss
  packages/react/src/components/TearSheet/tear-sheet.scss
  packages/react/src/hooks/useWindowSize.js
  packages/react/src/index.js
  packages/react/src/styles.scss
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: package: react, status: ready to merge 🎉

#2349 fix(suite-header): fix keyboard keyboard navigation in header panel
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.test.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/__snapshots__/SuiteHeaderAppSwitcher.story.storyshot
  packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
  packages/react/src/components/SuiteHeader/_suite-header.scss
  packages/react/src/utils/componentUtilityFunctions.js
Labels: status: ready to merge 🎉

#2325 feat(suiteheader) Adding a custom hook to wrap the API call that populates SuiteHeader
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/src/components/SuiteHeader/README.md
  packages/react/src/components/SuiteHeader/SuiteHeader.story.jsx
  packages/react/src/components/SuiteHeader/hooks/useSuiteHeaderData.js
  packages/react/src/components/SuiteHeader/hooks/useUiResources.js
  packages/react/src/components/SuiteHeader/util/uiresources.fixture.js
  packages/react/src/components/SuiteHeader/util/uiresources.js
  packages/react/src/index.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2357 fix(timeseries): card with thresholds should generate sample values between the thresholds
  packages/react/src/components/ComboChartCard/comboChartHelpers.js
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
  packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  packages/react/src/components/TimeSeriesCard/timeSeriesUtils.js
  packages/react/src/components/TimeSeriesCard/timeSeriesUtils.test.js
Labels: status: ready to merge 🎉

#2350 chore(list-item): add title attribute to dnd icon
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/components/List/ListItem/ListItem.jsx
  packages/react/src/components/List/SimpleList/__snapshots__/SimpleList.story.storyshot
Labels: status: ready to merge 🎉

#2345 feat(image-hotspots): add minimapBehavior prop for better control
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/ImageCard/ImageControls.jsx
  packages/react/src/components/ImageCard/ImageHotspots.jsx
  packages/react/src/components/ImageCard/ImageHotspots.story.jsx
  packages/react/src/components/ImageCard/ImageHotspots.test.jsx
  packages/react/src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
  packages/react/src/components/ImageCard/__snapshots__/ImageHotspots.story.storyshot
Labels: status: ready to merge 🎉

#2361 fix(dashboardtemplateeditor): fix approach for editing title
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.test.jsx
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/PageTitleBar/PageTitleBar.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2354 fix(side-nav): remove bad props from story and component
  packages/react/src/components/SideNav/SideNav.jsx
  packages/react/src/components/SideNav/SideNav.story.jsx
  packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
  packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉
