Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2021-09, with the labels that each got.

#2761 chore(testing) increase coverage on DateTimePicker
  packages/react/src/components/DateTimePicker/DateTimePicker.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.test.e2e.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.test.jsx
  packages/react/src/components/DateTimePicker/__snapshots__/DateTimePicker.story.storyshot
  packages/react/src/components/DateTimePicker/_date-time-picker.scss
Labels: status: ready to merge 🎉

#2741 chore(testing): increase coverage on TableToolbarAdvancedFilterFlyout
  packages/react/src/components/Table/TableToolbar/TableToolbarAdvancedFilterFlyout.jsx
  packages/react/src/components/Table/TableToolbar/TableToolbarAdvancedFilterFlyout.test.jsx
Labels: status: ready to merge 🎉

#2747 chore(testing): increase coverage on FlyoutMenu
  packages/react/src/components/FlyoutMenu/FlyoutMenu.test.jsx
Labels: status: ready to merge 🎉

#2748 chore(testing): increase coverage on ListItem
  packages/react/src/components/List/ListItem/ListItem.jsx
  packages/react/src/components/List/ListItem/ListItem.test.jsx
Labels: status: ready to merge 🎉

#2749 chore(testing): increase coverage on ListTarget
  packages/react/src/components/List/List.test.e2e.jsx
  packages/react/src/components/List/ListItem/ListTarget.jsx
Labels: status: ready to merge 🎉

#2750 chore(testing): increase coverage on BarChartCardFormSettings
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/BarChartCardFormItems/BarChartCardFormSettings.test.jsx
Labels: status: ready to merge 🎉

#2751 chore(testing): increase testing coverage on CardEditor/CardEditForm items
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormSettings.test.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormContent.test.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.test.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ThresholdsFormItem.test.jsx
Labels: status: ready to merge 🎉

#2762 chore(testing): increase coverage on TableDetailWizard
  packages/react/src/components/Table/TableDetailWizard/TableDetailWizard.test.jsx
Labels: status: ready to merge 🎉

#2763 chore(testing): increase coverage on StatefulTileCatalog
  packages/react/src/components/TileCatalog/StatefulTileCatalog.test.jsx
Labels: status: ready to merge 🎉

#2765 chore(testing): increase coverage on StatefulPageWizard
  packages/react/src/components/PageWizard/StatefulPageWizard.jsx
  packages/react/src/components/PageWizard/StatefulPageWizard.test.jsx
Labels: status: ready to merge 🎉

#2743 chore(testing): increase coverage on IdleTimer
  packages/react/src/components/SuiteHeader/util/IdleTimer.test.js
Labels: status: ready to merge 🎉

#2754 chore(testing) increase coverage on RuleBuilderEditor/GroupLogic
  packages/react/src/components/RuleBuilder/GroupLogic.test.jsx
  packages/react/src/components/RuleBuilder/RuleBuilderEditor.test.jsx
Labels: status: ready to merge 🎉

#2756 chore(testing): increase coverage on PieChartCard
  packages/react/src/components/PieChartCard/PieChartCard.jsx
  packages/react/src/components/PieChartCard/PieChartCard.test.jsx
Labels: status: ready to merge 🎉

#2759 test(imagecardformcontent): improved unit test coverage
  packages/react/jest.config.js
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormContent.test.jsx
Labels: status: ready to merge 🎉

#2760 chore(testing): increase coverage on TableMultiSortModal
  packages/react/src/components/Table/TableMultiSortModal/TableMultiSortModal.test.jsx
Labels: status: ready to merge 🎉

#2770 fix(side-nav): add slight delay on hover open transition
  packages/react/src/components/SideNav/_side-nav.scss
Labels: status: ready to merge 🎉

#2772 fix(table-card): adjust padding on empty state for medium cards
  packages/react/src/components/Table/_table.scss
  packages/react/src/components/TableCard/TableCard.story.jsx
Labels: status: ready to merge 🎉

#2774 fix(sidenav): added stateful example in storybook
  packages/react/src/components/SideNav/SideNav.story.jsx
  packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
Labels: status: ready to merge 🎉

#2758 chore(testing): increase coverage on TearSheet
  packages/react/src/components/TearSheet/TearSheet.test.jsx
Labels: status: ready to merge 🎉

#2777 testing(list/tile-catalog-new): improve quality of tests for these components
  packages/react/src/components/List/List.test.jsx
  packages/react/src/components/TileCatalogNew/TileCatalogNew.jsx
  packages/react/src/components/TileCatalogNew/TileCatalogNew.test.jsx
  packages/react/src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
  packages/react/src/components/TileCatalogNew/_tile-catalog.scss
Labels: status: ready to merge 🎉

#2768 fix(header): Add isActionItemVisible function, account for hidden icons in overflow checking
  packages/react/.eslintrc
  packages/react/cypress.json
  packages/react/package.json
  packages/react/src/components/Header/Header.jsx
  packages/react/src/components/Header/Header.story.jsx
  packages/react/src/components/Header/Header.test.e2e.jsx
  packages/react/src/components/Header/Header.test.jsx
  packages/react/src/components/Header/HeaderAction/HeaderAction.jsx
  packages/react/src/components/Header/HeaderAction/HeaderActionPanel.jsx
  packages/react/src/components/Header/HeaderActionGroup.jsx
  packages/react/src/components/Header/__snapshots__/Header.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/SuiteHeader/SuiteHeader.jsx
  packages/react/src/components/SuiteHeader/SuiteHeader.mdx
  packages/react/src/components/SuiteHeader/SuiteHeader.story.jsx
  packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2780 fix(rule-builder): fix minor css to prevent container overflowing
  packages/react/src/components/RuleBuilder/_rule-builder.scss
Labels: status: ready to merge 🎉

#2781 fix(internal): fix FullWidthWrapper to use correct styles
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/internal/FullWidthWrapper.jsx
Labels: status: ready to merge 🎉

#2785 fix(date-time-picker): date time picker styles and add keyboard navigation/tests
  packages/react/cypress.json
  packages/react/cypress/support/commands.js
  packages/react/package.json
  packages/react/src/components/CardCodeEditor/CardCodeEditor.test.e2e.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.test.e2e.jsx
  packages/react/src/components/DateTimePicker/__snapshots__/DateTimePicker.story.storyshot
  packages/react/src/components/DateTimePicker/_date-time-picker.scss
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.test.e2e.jsx
  yarn.lock
Labels: status: ready to merge 🎉

#2789 fix(simple-list): update state properly when external props change
  packages/react/src/components/List/SimpleList/SimpleList.jsx
  packages/react/src/components/List/SimpleList/SimpleList.story.jsx
  packages/react/src/components/List/SimpleList/SimpleList.test.e2e.jsx
  packages/react/src/components/List/SimpleList/SimpleList.test.jsx
Labels: status: ready to merge 🎉

#2766 test(errortable): improved unit test coverage
  packages/react/jest.config.js
  packages/react/src/components/Table/ErrorTable/__tests__/ErrorTable.test.jsx
Labels: status: ready to merge 🎉

#2752 test(editorutils): improved unit test coverage
  packages/react/jest.config.js
  packages/react/src/components/DashboardEditor/editorUtils.jsx
  packages/react/src/components/DashboardEditor/editorUtils.test.jsx
Labels: status: ready to merge 🎉

#2764 test(scrollingcontrols): improved unit test coverage
  packages/react/jest.config.js
  packages/react/src/components/MapCard/MapCard.test.jsx
Labels: status: ready to merge 🎉

#2796 fix(empty-state): node-sass build errors with `max`
  packages/react/src/components/Table/_table.scss
Labels: status: ready to merge 🎉

#2755 test(thresholdsformitem): improved unit test coverage
  packages/react/jest.config.js
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ThresholdsFormItem.test.jsx
Labels: status: ready to merge 🎉

#2793 test(hierarchy-list-reorder-modal): improve test quality
  packages/react/src/components/List/HierarchyList/HierarchyList.story.jsx
  packages/react/src/components/List/HierarchyList/HierarchyListReorderModal.test.jsx
  packages/react/src/components/List/HierarchyList/HierarchyListReorderModal/HierarchyListReorderModal.jsx
Labels: status: ready to merge 🎉

#2809 test(basetablereducer): improved unit testing coverage
  packages/react/jest.config.js
  packages/react/src/components/Table/tableReducer.test.jsx
Labels: status: one more review 👀

#2790 feat(dashboardeditor): add new render callbacks to allow custom renders of the edit form (and card render) without forcing the Card JSON to change
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/src/components/CardEditor/CardEditor.jsx
  packages/react/src/components/CardEditor/CardEditor.story.jsx
  packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  packages/react/src/components/ComboBox/__snapshots__/ComboBox.story.storyshot
  packages/react/src/components/ComposedModal/__snapshots__/ComposedModal.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorCardRenderer.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorCardRenderer.test.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorDefaultCardRenderer.jsx
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/index.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge 🎉

#2787 feat(value-card): add onAttributeClick callback
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/ValueCard/Attribute.jsx
  packages/react/src/components/ValueCard/ValueCard.jsx
  packages/react/src/components/ValueCard/ValueCard.story.jsx
  packages/react/src/components/ValueCard/ValueCard.test.jsx
  packages/react/src/components/ValueCard/ValueRenderer.jsx
  packages/react/src/components/ValueCard/ValueRenderer.test.jsx
  packages/react/src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
  packages/react/src/components/ValueCard/_value-renderer.scss
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2798 fix(empty-state): minor empty state design updates
  packages/react/src/components/EmptyState/EmptyState.jsx
  packages/react/src/components/EmptyState/__snapshots__/EmptyState.story.storyshot
  packages/react/src/components/EmptyState/_emptystate.scss
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
Labels: status: ready to merge 🎉

#2807 fix(table): removed css that did not and should not work
  packages/react/src/components/Table/TableHead/_table-head.scss
Labels: status: ready to merge 🎉

#2805 feat(table): allow lazy-loading of columns
  packages/react/src/components/Table/StatefulTable.test.jsx
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/Table.test.jsx
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/TableSkeletonWithHeaders/TableSkeletonWithHeaders.jsx
  packages/react/src/components/Table/TableSkeletonWithHeaders/_table-skeleton-with-headers.scss
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/Table/tableReducer.js
  packages/react/src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2810 test(date-time-picker-v2): improve coverage
  packages/react/src/components/DateTimePicker/DateTimePickerV2.jsx
  packages/react/src/components/DateTimePicker/DateTimePickerV2.test.e2e.jsx
  packages/react/src/components/DateTimePicker/DateTimePickerV2.test.jsx
Labels: status: ready to merge 🎉

#2775 fix(repo): use es build instead of lib in browser
  packages/react/package.json
Labels: status: ready to merge 🎉

#2814 test(listitem): added more tests
  packages/react/jest.config.js
  packages/react/src/components/List/ListItem/ListItem.test.jsx
Labels: status: ready to merge 🎉

#2813 2802 table reducer improve test coverage
  packages/react/jest.config.js
  packages/react/package.json
  packages/react/src/components/Table/tableReducer.js
  packages/react/src/components/Table/tableReducer.test.jsx
Labels: status: ready to merge 🎉

#2791 fix(suiteheader): allow keyboard navigation
  packages/react/.eslintrc
  packages/react/src/components/Header/Header.story.jsx
  packages/react/src/components/Header/Header.test.e2e.jsx
  packages/react/src/components/Header/HeaderAction/HeaderAction.jsx
  packages/react/src/components/Header/HeaderAction/HeaderActionMenu.jsx
  packages/react/src/components/Header/HeaderAction/HeaderActionPanel.jsx
  packages/react/src/components/Header/__snapshots__/Header.story.storyshot
  packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
  packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderProfile/SuiteHeaderProfile.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderProfile/__snapshots__/SuiteHeaderProfile.story.storyshot
  packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
Labels: status: ready to merge 🎉

#2784 refactor(table): refactor wrap truncate code
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/Table.test.jsx
  packages/react/src/components/Table/TableBody/TableBody.jsx
  packages/react/src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
  packages/react/src/components/Table/TableBody/TableBodyRow/TableBodyRow.story.jsx
  packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.jsx
  packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.test.jsx
  packages/react/src/components/Table/TableHead/TableHead.jsx
  packages/react/src/components/Table/TablePropTypes.js
Labels: status: ready to merge 🎉

#2815 test(idle-logout-confirmation-dialog): improve test coverage
  packages/react/src/components/SuiteHeader/IdleLogoutConfirmationModal/IdleLogoutConfirmationModal.test.jsx
Labels: status: ready to merge 🎉

#2816 chore(table): add testids to overflow menus in table
  packages/react/src/components/Table/Table.test.jsx
  packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
  packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.test.jsx
  packages/react/src/components/Table/TableHead/TableHead.jsx
  packages/react/src/components/Table/TableHead/TableHead.test.jsx
  packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
Labels: status: ready to merge 🎉

#2817 2804 combo chart helpers improve unit test coverage
  packages/react/jest.config.js
  packages/react/package.json
  packages/react/src/components/ComboChartCard/comboChartHelpers.js
  packages/react/src/components/ComboChartCard/comboChartHelpers.test.js
  packages/react/src/components/TimeSeriesCard/timeSeriesUtils.js
Labels: status: ready to merge 🎉

#2818 feat(table): add support for size prop to effect header/aggregation footer
  packages/react/src/components/DataTable/_data-table.scss
  packages/react/src/components/Table/StatefulTable.story.jsx
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.jsx
  packages/react/src/components/Table/TableFoot/_table-foot.scss
  packages/react/src/components/Table/TableHead/_table-head.scss
  packages/react/src/components/Table/TableManageViewsModal/TableManageViewsList.jsx
  packages/react/src/components/Table/TableMultiSortModal/TableMultiSortModal.jsx
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  packages/react/src/internal/experimental.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2632 fix(datetimepicker): needs to use the correct locale in the card
  packages/react/src/components/BarChartCard/BarChartCard.jsx
  packages/react/src/components/Card/Card.jsx
  packages/react/src/components/Card/Card.story.jsx
  packages/react/src/components/Card/Card.test.jsx
  packages/react/src/components/Card/CardToolbar.jsx
  packages/react/src/components/ComboChartCard/ComboChartCard.jsx
  packages/react/src/components/ImageCard/ImageCard.jsx
  packages/react/src/components/TableCard/TableCard.jsx
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
  packages/react/src/components/ValueCard/ValueCard.jsx
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉, package: react

#2845 fix(suite-header): btn--primary icon colors
  packages/react/src/components/Header/_header.scss
Labels: status: ready to merge 🎉

#2836 fix(datetimepicker): disable apply for invalid values
  packages/react/src/components/DateTimePicker/DateTimePicker.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.test.jsx
Labels: status: ready to merge 🎉

#2826 docs(all): updated docs testid case
  packages/react/docs/guides/testing.md
  packages/react/docs/guides/versioning.md
  packages/react/src/components/BarChartCard/BarChartCard.mdx
  packages/react/src/components/Card/Card.mdx
  packages/react/src/components/ComposedModal/ComposedModal.mdx
  packages/react/src/components/HotspotEditorModal/DynamicHotspotSourcePicker/DynamicHotspotSourcePickerREADME.mdx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTabREADME.mdx
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/HotspotEditorTooltipTabREADME.mdx
  packages/react/src/components/List/List.mdx
  packages/react/src/components/ListBuilder/ListBuilder.mdx
  packages/react/src/components/MapCard/MapCard.mdx
  packages/react/src/components/MenuButton/MenuButton.mdx
  packages/react/src/components/TableCard/TableCard.mdx
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.mdx
  packages/react/src/components/ValueCard/ValueCard.mdx
Labels: status: ready to merge 🎉

#2822 chore(repo): bump test coverage to 90%+
  packages/react/jest.config.js
  packages/react/package.json
Labels: status: ready to merge 🎉

#2797 2620 table components in table cell headers are not readable
  packages/react/src/components/ComboBox/ComboBox.jsx
  packages/react/src/components/ComboBox/ComboBox.story.jsx
  packages/react/src/components/ComboBox/ComboBox.test.jsx
  packages/react/src/components/ComboBox/_combo-box.scss
  packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
  packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.test.jsx
  packages/react/src/components/Table/TableHead/FilterHeaderRow/_filter-header-row.scss
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/globals/_mixins.scss
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2819 feat(icon-switch): design updates
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/HotspotEditorModal/HotspotTextStyleTab/HotspotTextStyleTab.story.jsx
  packages/react/src/components/HotspotEditorModal/HotspotTextStyleTab/__snapshots__/HotspotTextStyleTab.story.storyshot
  packages/react/src/components/IconSwitch/IconSwitch.jsx
  packages/react/src/components/IconSwitch/IconSwitch.story.jsx
  packages/react/src/components/IconSwitch/__snapshots__/IconSwitch.story.storyshot
  packages/react/src/components/IconSwitch/_icon-switch.scss
  packages/react/src/components/ImageGalleryModal/__snapshots__/ImageGalleryModal.story.storyshot
  packages/react/src/components/PageTitleBar/_page-title-bar.scss
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2835 fix(datetimepicker): range separator customization
  packages/angular/src/date-time-picker/custom-date-time.component.ts
  packages/angular/src/date-time-picker/date-time-picker.component.ts
  packages/angular/src/date-time-picker/date-time-picker.stories.ts
Labels: status: ready to merge 🎉, package: angular

#2847 fix(datetimepicker): support blocking dates
  packages/angular/src/date-time-picker/custom-date-time.component.ts
  packages/angular/src/date-time-picker/date-time-absolute.component.ts
  packages/angular/src/date-time-picker/date-time-picker.component.ts
  packages/angular/src/date-time-picker/date-time-picker.stories.ts
Labels: status: ready to merge 🎉, package: angular

#2837 chore(repo): initial visual regression images commit
  .dockerignore
  .github/CONTRIBUTING.MD
  .github/workflows/test.yml
  Dockerfile
  docker-compose.yml
  packages/react/cypress-visual-screenshots/baseline/components/Button/Button.test.e2ex-Button.png
  packages/react/cypress-visual-screenshots/baseline/components/Button/Button.test.e2ex-Ghost_Button.png
  packages/react/cypress-visual-screenshots/baseline/components/CardCodeEditor/CardCodeEditor.test.e2ex-CardCodeEditor.png
  packages/react/cypress/plugins/index.js
  packages/react/package.json
  packages/react/src/components/CardCodeEditor/CardCodeEditor.test.e2e.jsx
Labels: status: ready to merge 🎉

#2834 fix(combo-box): fix scss to not break OptimizeCSSAssets webpack plugin
  packages/react/src/components/ComboBox/_combo-box.scss
  packages/react/src/components/PageTitleBar/_page-title-bar.scss
Labels: status: ready to merge 🎉

#2860 fix(tabletoolbar): provide aria-label to CarbonTableToolbar
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/TablePropTypes.js
  packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2875 fix(suite-header): all cmd+click/ctrl+click to open new window
  packages/react/src/components/SuiteHeader/SuiteHeader.jsx
  packages/react/src/components/SuiteHeader/SuiteHeader.mdx
  packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.jsx
Labels: status: ready to merge 🎉

#2882 fix(suite-header): replace javascript urls
  packages/react/src/components/Card/__snapshots__/Card.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/TablePropTypes.js
  packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2881 fix(date-time-picker): flatpickr 4.6.9 fix
  package.json
  packages/react/cypress/support/commands.js
  packages/react/package.json
  packages/react/src/components/DateTimePicker/DateTimePicker.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.test.e2e.jsx
  packages/react/src/components/DateTimePicker/DateTimePickerV2.jsx
  packages/react/src/components/DateTimePicker/DateTimePickerV2.test.e2e.jsx
  packages/react/src/components/DateTimePicker/DateTimePickerV2.test.jsx
  yarn.lock
Labels: status: ready to merge 🎉

#2878 style(valuecard): trend text should be grey instead of indicator color
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/ValueCard/Attribute.jsx
  packages/react/src/components/ValueCard/Attribute.test.jsx
  packages/react/src/components/ValueCard/ValueCard.test.jsx
  packages/react/src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
  packages/react/src/components/ValueCard/_attribute.scss
Labels: status: ready to merge 🎉

#2626 Table columns move
  packages/angular/src/table/body/table-body.component.ts
  packages/angular/src/table/body/table-row.component.ts
  packages/angular/src/table/index.ts
  packages/angular/src/table/table-model.class.spec.ts
  packages/angular/src/table/table-model.class.ts
  packages/angular/src/table/table.component.ts
  packages/angular/src/table/table.module.ts
Labels: status: ready to merge 🎉, package: angular

#2745 Support load more in Table and List component
  packages/react/src/components/List/List.jsx
  packages/react/src/components/List/List.mdx
  packages/react/src/components/List/List.story.jsx
  packages/react/src/components/List/List.test.jsx
  packages/react/src/components/List/__snapshots__/List.story.storyshot
  packages/react/src/components/List/_list.scss
  packages/react/src/components/Table/StatefulTable.jsx
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/Table.mdx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/Table.test.helpers.js
  packages/react/src/components/Table/Table.test.jsx
  packages/react/src/components/Table/TableBody/TableBody.jsx
  packages/react/src/components/Table/TableBody/TableBodyLoadMoreRow/TableBodyLoadMoreRow.jsx
  packages/react/src/components/Table/TableBody/TableBodyLoadMoreRow/TableBodyLoadMoreRow.test.jsx
  packages/react/src/components/Table/TableBody/TableBodyLoadMoreRow/_table-body-load-more-row.scss
  packages/react/src/components/Table/TablePropTypes.js
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/Table/statefulTableUtilities.js
  packages/react/src/components/Table/statefulTableUtilities.test.js
  packages/react/src/components/Table/tableActionCreators.js
  packages/react/src/components/Table/tableReducer.js
  packages/react/src/components/Table/tableReducer.test.jsx
  packages/react/src/components/Table/tableUtilities.js
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/styles.scss
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉, offering: platform/monitor

#2898 fix(table): aggregation column placement
  packages/react/src/components/Table/StatefulTable.story.jsx
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/TableFoot/TableFoot.jsx
  packages/react/src/components/Table/TableFoot/TableFoot.test.jsx
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
Labels: status: ready to merge 🎉

#2908 fix(page-title-bar): chrome upgrade(?) causes cypress test to fail
  packages/react/src/components/PageTitleBar/PageTItleBar.test.e2e.jsx
Labels: status: ready to merge 🎉

#2900 2839 time picker spinner improved keyboard input and added error state
  packages/react/src/components/DateTimePicker/DateTimePicker.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.test.e2e.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.test.jsx
  packages/react/src/components/DateTimePicker/DateTimePickerV2.jsx
  packages/react/src/components/DateTimePicker/DateTimePickerV2.test.e2e.jsx
  packages/react/src/components/DateTimePicker/DateTimePickerV2.test.jsx
  packages/react/src/components/DateTimePicker/_date-time-picker.scss
  packages/react/src/components/DateTimePicker/_date-time-pickerv2.scss
  packages/react/src/components/TimePickerSpinner/TimePickerSpinner.jsx
  packages/react/src/components/TimePickerSpinner/TimePickerSpinner.story.jsx
  packages/react/src/components/TimePickerSpinner/TimePickerSpinner.test.jsx
  packages/react/src/components/TimePickerSpinner/__snapshots__/TimePickerSpinner.story.storyshot
  packages/react/src/components/TimePickerSpinner/_time-picker-spinner.scss
  packages/react/src/constants/KeyCodeConstants.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2910 2827 table create visual regression test fixes
  .github/CONTRIBUTING.MD
  packages/react/cypress-visual-screenshots/baseline/components/CardCodeEditor/CardCodeEditor.test.e2ex-CardCodeEditor.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-1.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-2.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-3.png
  packages/react/jest.config.js
  packages/react/package.json
  packages/react/src/components/Table/StatefulTable.test.jsx
  packages/react/src/components/Table/StatefulTableMockReducers.test.jsx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/Table.test.e2e.jsx
  packages/react/src/components/Table/Table.test.helpers.js
  packages/react/src/components/Table/Table.test.helpers.jsx
  packages/react/src/components/Table/Table.test.jsx
Labels: status: one more review 👀
