Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2021-01, with the labels that each got.

#1900 fix(tablecardformcontent): dimensions were not populating in the edit…
  src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.test.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormSettings.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormSettings.test.jsx
  src/components/DashboardEditor/editorUtils.jsx
  src/components/DashboardEditor/editorUtils.test.jsx
Labels: status: ready to merge 🎉

#1894 adding data-testid for specific components
  .vscode/launch.json
  src/components/CardEditor/CardEditForm/CardEditForm.jsx
  src/components/CardEditor/CardEditor.jsx
  src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  src/components/DashboardEditor/DashboardEditor.story.jsx
  src/components/DashboardEditor/DashboardEditorHeader/DashboardEditorHeader.jsx
  src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  src/components/Header/HeaderAction/HeaderAction.jsx
  src/components/Header/HeaderActionGroup.jsx
  src/components/Header/__snapshots__/Header.story.storyshot
  src/components/SideNav/__snapshots__/SideNav.story.storyshot
  src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1882 1560/custom card gallery
  package.json
  src/components/CardEditor/CardEditor.jsx
  src/components/CardEditor/CardEditor.story.jsx
  src/components/CardEditor/CardEditor.test.jsx
  src/components/CardEditor/CardGalleryList/CardGalleryList.jsx
  src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  src/components/CardEditor/_card-editor.scss
  src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  src/constants/LayoutConstants.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge 🎉

#1903 fix(timeseriescard): use dataSourceId as column name with dataFilter
  src/components/DashboardEditor/DashboardEditor.story.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
Labels: status: one more review 👀, status: ready for code owner's review

#1905 fix(TableCard): use table loading state rather than card
  src/components/Table/tableReducer.js
  src/components/Table/tableReducer.test.jsx
  src/components/TableCard/TableCard.jsx
  src/components/TableCard/TableCard.story.jsx
  src/components/TableCard/__snapshots__/TableCard.story.storyshot
  src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
Labels: status: ready to merge 🎉

#1910 fix(dateTimePicker and list): i18n strings
  src/components/CardEditor/CardEditor.jsx
  src/components/CardEditor/CardGalleryList/CardGalleryList.jsx
  src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  src/components/DashboardEditor/DashboardEditor.jsx
  src/components/DateTimePicker/DateTimePicker.jsx
  src/components/List/List.jsx
  src/components/List/List.story.jsx
  src/components/List/SimpleList/__snapshots__/SimpleList.story.storyshot
  src/components/List/__snapshots__/List.story.storyshot
  src/components/TimePickerSpinner/TimePickerSpinner.jsx
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1918 fix(dashboardeditor): pass through pii props to the child components
  src/components/CardCodeEditor/CardCodeEditor.jsx
  src/components/CardEditor/CardEditForm/CardEditForm.jsx
  src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/BarChartCardFormItems/BarChartCardFormSettings.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/BarChartDataSeriesContent.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormSettings.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormContent.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormSettings.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormSettings.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/ThresholdsFormItem.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/ValueCardFormItems/ValueCardFormSettings.jsx
  src/components/CardEditor/CardEditForm/CardEditFormSettings.jsx
  src/components/CardEditor/CardEditForm/CardEditFormSettings.test.jsx
  src/components/CardEditor/CardEditForm/CommonCardEditFormFields.jsx
  src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  src/components/ColorDropdown/ColorDropdown.jsx
  src/components/DashboardEditor/DashboardEditor.jsx
  src/components/DashboardEditor/DashboardEditor.story.jsx
  src/components/DashboardEditor/DashboardEditorHeader/DashboardEditorHeader.jsx
  src/components/DashboardEditor/DashboardEditorHeader/__snapshots__/DashboardEditorHeader.story.storyshot
  src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  src/components/FileDrop/__snapshots__/FileDrop.story.storyshot
  src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.jsx
  src/components/HotspotEditorModal/_hotspot-editor-modal.scss
  src/components/IconDropdown/IconDropdown.jsx
  src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
  src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  src/components/SimpleIconDropdown/SimpleIconDropdown.jsx
  src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: one more review 👀

#1923 fix(suiteheader): update app list and external status
  src/components/SuiteHeader/util/suiteHeaderData.js
Labels: status: ready to merge 🎉

#1913 fix(ChartCards): translate group and total tooltip labels
  src/components/BarChartCard/BarChartCard.jsx
  src/components/BarChartCard/BarChartCard.story.jsx
  src/components/BarChartCard/barChartUtils.js
  src/components/TimeSeriesCard/TimeSeriesCard.jsx
  src/components/TimeSeriesCard/TimeSeriesCard.story.jsx
  src/constants/CardPropTypes.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1929 fix(editor): value cards need to set precision at the attribute level
  src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.test.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/ValueCardFormItems/ValueCardFormSettings.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/ValueCardFormItems/ValueCardFormSettings.test.jsx
  src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
Labels: status: ready to merge 🎉

#1928 feat(hotspotmodal): integrate the hotspot modal into the ImageCard Editor
  src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormContent.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormContent.test.jsx
  src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  src/components/DashboardEditor/DashboardEditorCardRenderer.jsx
  src/components/DashboardEditor/DashboardEditorCardRenderer.test.jsx
  src/components/DashboardEditor/editorUtils.jsx
  src/components/HotspotEditorModal/HotspotEditorModal.jsx
  src/components/ImageCard/ImageCard.jsx
  yarn.lock
Labels: status: ready for review 👀

#1933 fix(hotspot): i18n need to pass through all props downstream to components
  src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormContent.jsx
  src/components/DashboardEditor/DashboardEditor.story.jsx
  src/components/HotspotEditorModal/DynamicHotspotSourcePicker/DynamicHotspotSourcePicker.jsx
  src/components/HotspotEditorModal/DynamicHotspotSourcePicker/DynamicHotspotSourcePicker.story.jsx
  src/components/HotspotEditorModal/DynamicHotspotSourcePicker/DynamicHotspotSourcePicker.test.jsx
  src/components/HotspotEditorModal/DynamicHotspotSourcePicker/__snapshots__/DynamicHotspotSourcePicker.story.storyshot
  src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.jsx
  src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.story.jsx
  src/components/HotspotEditorModal/HotspotEditorDataSourceTab/__snapshots__/HotspotEditorDataSourceTab.story.storyshot
  src/components/HotspotEditorModal/HotspotEditorModal.jsx
  src/components/HotspotEditorModal/HotspotEditorModal.story.jsx
  src/components/HotspotEditorModal/HotspotEditorModal.test.jsx
  src/components/HotspotEditorModal/HotspotEditorTooltipTab/HotspotEditorTooltipTab.jsx
  src/components/HotspotEditorModal/HotspotEditorTooltipTab/HotspotEditorTooltipTab.story.jsx
  src/components/HotspotEditorModal/HotspotEditorTooltipTab/HotspotEditorTooltipTab.test.jsx
  src/components/HotspotEditorModal/HotspotEditorTooltipTab/__snapshots__/HotspotEditorTooltipTab.story.storyshot
  src/components/HotspotEditorModal/HotspotTextStyleTab/HotspotTextStyleTab.jsx
  src/components/HotspotEditorModal/HotspotTextStyleTab/HotspotTextStyleTab.story.jsx
  src/components/HotspotEditorModal/HotspotTextStyleTab/HotspotTextStyleTab.test.jsx
  src/components/HotspotEditorModal/HotspotTextStyleTab/__snapshots__/HotspotTextStyleTab.story.storyshot
  src/components/ImageCard/HotspotContent.jsx
  src/components/ImageCard/ImageCard.jsx
  src/components/ImageCard/ImageHotspots.jsx
  src/constants/SharedPropTypes.js
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1934 feat(hotspot): need to expose the onFetchDynamicDemoHotspots method to the DashboardEditor
  src/components/CardEditor/CardEditForm/CardEditForm.jsx
  src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
  src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormContent.jsx
  src/components/CardEditor/CardEditor.jsx
  src/components/DashboardEditor/DashboardEditor.jsx
  src/components/HotspotEditorModal/HotspotEditorModal.jsx
Labels: status: ready to merge 🎉

#1932 fix(BarChartCard): use series for sample data generation
  src/components/BarChartCard/BarChartCard.jsx
  src/components/BarChartCard/barChartUtils.js
  src/components/DashboardEditor/DashboardEditorCardRenderer.jsx
  src/components/DashboardEditor/DashboardEditorCardRenderer.test.jsx
Labels: status: one more review 👀, status: ready for code owner's review

#1936 fix(dashboardeditor): hide value card font size setting
  src/components/CardEditor/CardEditForm/CardEditForm.jsx
  src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
Labels: status: one more review 👀, status: ready for code owner's review

#1940 style(editor): update height to accomodate suite header
  src/components/DashboardEditor/DashboardEditor.story.jsx
  src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  src/components/DashboardEditor/_dashboard-editor.scss
Labels: status: ready to merge 🎉

#1941 feat(draganddrop): update react-dnd, refactor to use new provider
  .storybook/__snapshots__/Welcome.story.storyshot
  docs/draganddrop.md
  package.json
  src/components/List/List.jsx
  src/components/List/ListItem/ListItem.test.jsx
  src/components/Table/TableHead/ColumnHeaderRow/ColumnHeaderRow.jsx
  src/components/Table/TableHead/ColumnHeaderRow/ColumnHeaderRow.test.jsx
  src/components/Table/TableManageViewsModal/table-manage-views-list.scss
  src/hooks/useDNDProviderElement.jsx
  src/index.js
  src/utils/DragAndDropUtils.jsx
  src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge 🎉

#1935 fix(fileuploader): add styles to show error message
  src/components/FileUploader/_file-uploader.scss
Labels: status: ready to merge 🎉

#1937 feat(progressindicator): export default carbon indicator
  src/components/ProgressIndicator/ProgressIndicator.story.jsx
  src/components/ProgressIndicator/__snapshots__/ProgressIndicator.story.storyshot
  src/components/ProgressIndicator/index.js
Labels: status: ready to merge 🎉

#1946 fix(hotspotmodaleditor): stop the image from scrolling
  src/components/HotspotEditorModal/_hotspot-editor-modal.scss
  src/components/ImageCard/ImageHotspots.jsx
  yarn.lock
Labels: status: ready to merge 🎉

#1944 fix(sidebar): add some rules for handling RTL layouts
  src/components/SideNav/_side-nav.scss
Labels: status: ready to merge 🎉

#1960 chore: fix publish test args
  .github/workflows/publish.yml
Labels: status: ready to merge 🎉

#1961 chore: fix coverage location for publish
  .github/workflows/publish.yml
Labels: status: ready to merge 🎉

#1962 chore: fix publish to use github env vars instead of travis vars
  .github/README.MD
  scripts/release.sh
Labels: status: ready to merge 🎉

#1964 chore: set git name/email and try from-git
  scripts/release.sh
Labels: status: ready to merge 🎉

#1967 Fix publish
  .github/workflows/publish.yml
  packages/react/package.json
  scripts/release.sh
Labels: status: ready to merge 🎉

#1947 feat(repo): update to use node v14
  .github/workflows/build.yml
  .github/workflows/format.yml
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .nvmrc
  .vscode/launch.json
  package.json
  packages/react/.prettierignore
  packages/react/package.json
  yarn.lock
Labels: status: ready to merge 🎉

#1956 fix(hotspot): remove uneeded style causing compliation issues
  packages/react/src/components/ImageCard/_hotspot.scss
Labels: status: ready to merge 🎉

#1958 fix(dashboardgrid): don't regenerate layout if one already exists
  packages/react/jest.config.js
  packages/react/src/components/Dashboard/DashboardGrid.jsx
  packages/react/src/components/Dashboard/DashboardGrid.test.jsx
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  src/components/Dashboard/_dashboard-grid.scss
  src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
Labels: status: ready to merge 🎉

#1963 fix(hotspoteditormodal): 3 small ux improvements
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormContent.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditorCardRenderer.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorModal.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1957 (fix:list): Hide checkbox label to avoid duplicate content
  packages/react/src/components/List/List.story.jsx
  packages/react/src/components/List/__snapshots__/List.story.storyshot
Labels: status: ready to merge 🎉

#1942 refactor(ValueCard): new design and precision fixes
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/jest.config.js
  packages/react/src/components/CardEditor/CardEditForm/CardEditForm.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.test.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ValueCardFormItems/ValueCardFormSettings.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ValueCardFormItems/ValueCardFormSettings.test.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormSettings.test.jsx
  packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/TableCard/tableCardUtils.jsx
  packages/react/src/components/ValueCard/Attribute.jsx
  packages/react/src/components/ValueCard/UnitRenderer.jsx
  packages/react/src/components/ValueCard/ValueCard.jsx
  packages/react/src/components/ValueCard/ValueCard.story.jsx
  packages/react/src/components/ValueCard/ValueCard.test.jsx
  packages/react/src/components/ValueCard/ValueRenderer.jsx
  packages/react/src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
  packages/react/src/components/ValueCard/_attribute.scss
  packages/react/src/components/ValueCard/_unit-renderer.scss
  packages/react/src/components/ValueCard/_value-card.scss
  packages/react/src/components/ValueCard/_value-renderer.scss
  packages/react/src/components/ValueCard/valueCardUtils.js
  packages/react/src/components/ValueCard/valueCardUtils.test.js
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/index.js
  packages/react/src/styles.scss
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  packages/react/src/utils/__tests__/cardUtilityFunctions.test.jsx
  packages/react/src/utils/cardUtilityFunctions.js
  src/components/DashboardEditor/DashboardEditor.story.jsx
  src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  src/components/FileUploader/_file-uploader.scss
  src/components/ProgressIndicator/index.js
  src/components/Table/TableHead/ColumnHeaderRow/ColumnHeaderRow.test.jsx
  src/hooks/useDNDProviderElement.jsx
Labels: status: ready to merge 🎉

#1951 fix(hotspoteditormodal): make the user hold CTRL key before adding hotspots
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/HotspotEditorTooltipTab.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/__snapshots__/HotspotEditorTooltipTab.story.storyshot
  packages/react/src/components/HotspotEditorModal/HotspotTextStyleTab/HotspotTextStyleTab.jsx
  packages/react/src/components/HotspotEditorModal/__snapshots__/HotspotEditorModal.story.storyshot
  packages/react/src/components/ImageCard/ImageHotspots.jsx
  packages/react/src/components/ImageCard/ImageHotspots.test.jsx
  packages/react/src/components/ImageCard/__snapshots__/ImageHotspots.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1978 fix(build): update main and module in package.json
  packages/react/package.json
Labels: status: ready to merge 🎉

#1949 feat(imagecard): thresholds should change the icon for a hotspot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DashboardEditor/editorUtils.jsx
  packages/react/src/components/DashboardEditor/editorUtils.test.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorModal.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorModal.story.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorModal.test.jsx
  packages/react/src/components/HotspotEditorModal/__snapshots__/HotspotEditorModal.story.storyshot
  packages/react/src/components/ImageCard/ImageCard.jsx
  packages/react/src/components/ImageCard/ImageCard.story.jsx
  packages/react/src/components/ImageCard/ImageHotspots.jsx
  packages/react/src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#1969 Include uuid with dataSourceIds in dashboard editor for line, bar, image, and value
  packages/react/src/components/CardCodeEditor/CardCodeEditor.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditForm.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditForm.test.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.test.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.test.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/_card-edit-form.scss
  packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/DashboardEditor/editorUtils.jsx
  packages/react/src/components/DashboardEditor/editorUtils.test.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.test.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorModal.test.jsx
  packages/react/src/components/HotspotEditorModal/hooks/hotspotStateHook.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉
