Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2021-11, with the labels that each got.

#2983 feat(side-nav): allow nested levels of children
  packages/react/cypress/integration/codesandbox.spec.js
  packages/react/src/components/SideNav/SideNav.jsx
  packages/react/src/components/SideNav/SideNav.story.jsx
  packages/react/src/components/SideNav/SideNav.test.jsx
  packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
  packages/react/src/components/SideNav/_side-nav-carbon.scss
  packages/react/src/components/SideNav/_side-nav.scss
  packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3015 fix(date-time-picker): allow selecting ranges across months
  packages/react/src/components/DateTimePicker/DateTimePicker.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.test.e2e.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.test.jsx
  packages/react/src/components/DateTimePicker/DateTimePickerV2.jsx
  packages/react/src/components/DateTimePicker/DateTimePickerV2.test.e2e.jsx
Labels: status: one more review 👀

#2988 2987 list enable existing checkboxes for multi selection
  packages/react/src/components/List/List.jsx
  packages/react/src/components/List/List.mdx
  packages/react/src/components/List/List.story.jsx
  packages/react/src/components/List/List.test.jsx
  packages/react/src/components/List/ListContent/ListContent.jsx
  packages/react/src/components/List/ListItem/ListItem.jsx
  packages/react/src/components/List/ListItem/ListItem.test.jsx
  packages/react/src/components/List/ListItem/ListItemWrapper.jsx
  packages/react/src/components/List/ListItem/_list-item.scss
  packages/react/src/components/List/VirtualListContent/VirtualListContent.jsx
  packages/react/src/components/List/__snapshots__/List.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3009 fix(table): remove state management of aggregations from table component
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: version: 3, status: ready to merge 🎉

#3018 fix(stateful-table): update reducer for rowEdit actions
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/tableReducer.js
  packages/react/src/components/Table/tableReducer.test.jsx
Labels: status: ready to merge 🎉

#3019 fix(list-story): fix clearing search in story
  packages/react/src/components/List/List.story.jsx
Labels: status: ready to merge 🎉

#3020 fix(table): fix shouldExpandOnRowClick proptype
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/Table.mdx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3021 chore(table): remove isSortable prop where inappropriate
  packages/react/src/components/Table/StatefulTable.test.jsx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/Table.test.jsx
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
Labels: status: ready to merge 🎉

#3022 fix(stateful-table): handle resetting pagination when necessary
  packages/react/src/components/Table/StatefulTable.story.jsx
  packages/react/src/components/Table/tableReducer.js
  packages/react/src/components/Table/tableReducer.test.jsx
Labels: status: ready to merge 🎉

#3024 fix(list): fix styles to keep secondaryValue aligned when overflowing
  packages/react/src/components/List/HierarchyList/HierarchyList.story.jsx
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/components/List/ListItem/_list-item.scss
Labels: status: waiting for author's response 💬

#2973 chore(repo): initial action for updating `v3` on `next` changes
  .github/workflows/update-v3.yml
Labels: DO NOT MERGE

#2955 fix(table): fix action cell styling
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-1.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-3.png
  packages/react/src/components/Table/TableBody/RowActionsCell/_row-actions-cell.scss
Labels: status: ready to merge 🎉

#3039 3025 list add allowed drop target
  packages/react/src/components/FileUploader/stories/drop-container.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.story.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.test.e2e.jsx
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/components/List/List.jsx
  packages/react/src/components/List/List.mdx
  packages/react/src/components/List/List.story.jsx
  packages/react/src/components/List/List.test.e2e.jsx
  packages/react/src/components/List/ListContent/ListContent.jsx
  packages/react/src/components/List/ListItem/ListItem.jsx
  packages/react/src/components/List/ListItem/ListItem.test.jsx
  packages/react/src/components/List/ListItem/ListItemWrapper.jsx
  packages/react/src/components/List/ListItem/ListTarget.jsx
  packages/react/src/components/List/VirtualListContent/VirtualListContent.jsx
  packages/react/src/components/List/__snapshots__/List.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3029 feat(table): focus on first filterable column when filter row opened
  packages/react/src/components/ComboBox/ComboBox.jsx
  packages/react/src/components/Table/StatefulTable.story.jsx
  packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
  packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.test.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3038 fix(hierarchy-list): reset pagination and search when data changes
  packages/react/src/components/List/HierarchyList/HierarchyList.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.story.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.test.jsx
Labels: status: ready to merge 🎉

#3035 fix(card-code-editor): export from package
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/src/index.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3027 fix(table): don't display native title when using tooltip in header
  packages/react/src/components/Table/StatefulTable.story.jsx
  packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.jsx
  packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.test.jsx
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
Labels: status: ready to merge 🎉

#3017 3016 list add pinned items
  packages/react/src/components/List/HierarchyList/HierarchyList.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.story.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.test.jsx
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/components/List/List.jsx
  packages/react/src/components/List/List.mdx
  packages/react/src/components/List/List.story.jsx
  packages/react/src/components/List/List.test.jsx
  packages/react/src/components/List/ListContent/ListContent.jsx
  packages/react/src/components/List/ListItem/ListItem.jsx
  packages/react/src/components/List/ListItem/_list-item.scss
  packages/react/src/components/List/VirtualListContent/VirtualListContent.jsx
  packages/react/src/components/List/__snapshots__/List.story.storyshot
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3030 fix(table): fix background gradient artifacting on rowActions open
  packages/react/src/components/Table/TableBody/RowActionsCell/_row-actions-cell.scss
Labels: status: ready to merge 🎉

#3028 chore(combo-box): update stories with missing props
  packages/react/src/components/ComboBox/ComboBox.story.jsx
Labels: status: ready to merge 🎉

#3031 fix(overflow-menu): increase width of the spacer to match button width
  packages/react/src/components/OverflowMenu/_overflow-menu.scss
  packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
  packages/react/src/hooks/usePopoverPositioning.jsx
Labels: status: ready to merge 🎉

#3034 fix(table): preserve whitespace in cells with multiple spaces
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/Table.mdx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/TableBody/TableBody.jsx
  packages/react/src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
  packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.jsx
  packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.test.jsx
  packages/react/src/components/Table/TableCellRenderer/_table-cell-renderer.scss
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3026 fix(table): hide multisort options in rowEdit to match current sort
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-1.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-3.png
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/TableHead/TableHead.jsx
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
Labels: status: ready to merge 🎉

#3048 feat(table): add `hasFastSearch` prop to toggle onChange
  .github/workflows/codesandbox.yml
  packages/react/cypress/plugins/index.js
  packages/react/src/components/Table/StatefulTable.story.jsx
  packages/react/src/components/Table/StatefulTable.test.e2e.jsx
  packages/react/src/components/Table/StatefulTable.test.jsx
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/Table.mdx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/Table.test.jsx
  packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2986 2879 dashboard grid visual regression tests
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-BarChartCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-Card.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-GaugeCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-ListCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-PieChartCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-TableCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-TimeSeriesCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-ValueCard.png
  packages/react/src/components/Dashboard/DashboardGrid.test.e2e.jsx
Labels: status: ready to merge 🎉

#3056 feat(list): load more from top level
  packages/react/src/components/CardCodeEditor/CardCodeEditor.test.e2e.jsx
  packages/react/src/components/List/List.story.jsx
  packages/react/src/components/List/List.test.jsx
  packages/react/src/components/List/ListContent/ListContent.jsx
  packages/react/src/components/List/VirtualListContent/VirtualListContent.jsx
  packages/react/src/components/List/__snapshots__/List.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
Labels: status: ready to merge 🎉

#3060 fix(card-edit-form): fix threshold dropdown width
  packages/react/src/components/CardEditor/CardEditForm/_card-edit-form.scss
Labels: status: ready to merge 🎉

#3061 fix(simple-list): adjust secondary value css to prevent cut-off
  packages/react/src/components/List/ListItem/_list-item.scss
Labels: status: ready to merge 🎉

#3064 fix(hierarchy-list): uncheck children when parent unchecked
  packages/react/src/components/List/HierarchyList/HierarchyList.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.test.jsx
  packages/react/src/components/List/ListContent/ListContent.jsx
  packages/react/src/utils/DragAndDropUtils.jsx
Labels: status: ready to merge 🎉

#3066 feat(hierarchy-list): indeterminate checkbox handling to items in MultipleNesting mode.
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-TableCard.png
  packages/react/src/components/CardCodeEditor/CardCodeEditor.test.e2e.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.test.jsx
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/utils/DragAndDropUtils.jsx
Labels: status: ready to merge 🎉

#3070 Carbon upgrade 10.48
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/package.json
  packages/react/src/components/BarChartCard/__snapshots__/BarChartCard.story.storyshot
  packages/react/src/components/Card/__snapshots__/Card.story.storyshot
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/__snapshots__/ThresholdsFormItem.story.storyshot
  packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  packages/react/src/components/ComboChartCard/__snapshots__/ComboChartCard.story.storyshot
  packages/react/src/components/ComposedModal/__snapshots__/ComposedModal.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/EmptyState/__snapshots__/EmptyState.story.storyshot
  packages/react/src/components/FlyoutMenu/_flyout-menu.scss
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.test.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/__snapshots__/HotspotEditorDataSourceTab.story.storyshot
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/__snapshots__/HotspotEditorTooltipTab.story.storyshot
  packages/react/src/components/HotspotEditorModal/__snapshots__/HotspotEditorModal.story.storyshot
  packages/react/src/components/ImageCard/__snapshots__/ImageHotspots.story.storyshot
  packages/react/src/components/List/ListItem/__snapshots__/ListItem.story.storyshot
  packages/react/src/components/List/SimpleList/__snapshots__/SimpleList.story.storyshot
  packages/react/src/components/List/__snapshots__/List.story.storyshot
  packages/react/src/components/NavigationBar/__snapshots__/NavigationBar.story.storyshot
  packages/react/src/components/OverflowMenu/__snapshots__/OverflowMenu.story.storyshot
  packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
  packages/react/src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
  packages/react/src/components/PieChartCard/__snapshots__/PieChartCard.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilderEditor.story.storyshot
  packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
  packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
  packages/react/src/components/Table/TableBody/TableBodyRow/__snapshots__/TableBodyRow.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/TableToolbar/_table-toolbar.scss
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge 🎉

#3080 feat(page-title-bar): design audit and add new stackBreadcrumbsWithTabs feature
  packages/react/jest.config.js
  packages/react/src/components/DashboardEditor/DashboardEditorHeader/__snapshots__/DashboardEditorHeader.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/NavigationBar/__snapshots__/NavigationBar.story.storyshot
  packages/react/src/components/PageTitleBar/PageTItleBar.test.e2e.jsx
  packages/react/src/components/PageTitleBar/PageTitleBar.jsx
  packages/react/src/components/PageTitleBar/PageTitleBar.mdx
  packages/react/src/components/PageTitleBar/PageTitleBar.story.jsx
  packages/react/src/components/PageTitleBar/PageTitleBar.test.e2e.jsx
  packages/react/src/components/PageTitleBar/PageTitleBar.test.jsx
  packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
  packages/react/src/components/PageTitleBar/_page-title-bar.scss
  packages/react/src/components/PageWizard/__snapshots__/PageWizard.story.storyshot
  packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/components/WizardInline/__snapshots__/WizardInline.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3082 style(card-editor): fix rtl issues on threshold form items
  packages/react/src/components/CardEditor/CardEditForm/_card-edit-form.scss
Labels: status: ready to merge 🎉

#3085 fix(table): fix a11y issues on column selection button and toolbar tooltip
  packages/react/src/components/CardCodeEditor/CardCodeEditor.test.e2e.jsx
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/TableHead/ColumnHeaderSelect/ColumnHeaderSelect.jsx
  packages/react/src/components/Table/TableHead/TableHead.test.jsx
  packages/react/src/components/Table/TablePropTypes.js
  packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3086 style(composed-modal): fix close button RTL issues
  packages/react/src/components/ComposedModal/_composed-modal.scss
Labels: status: ready to merge 🎉

#3095 fix(pagetitlebar): child content component might be null
  packages/react/src/components/PageTitleBar/PageTitleBar.jsx
Labels: status: ready to merge 🎉
