Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2021-03, with the labels that each got.

#2065 feat(suiteheader): Adding support for custom side nav panel logic.
  packages/react/src/components/SuiteHeader/SuiteHeader.jsx
  packages/react/src/components/SuiteHeader/SuiteHeader.story.jsx
  packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderLogoutModal/__snapshots__/SuiteHeaderLogoutModal.story.storyshot
  packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: one more review 👀, status: ready to merge 🎉

#2069 fix(cardeditform): label truncation error for cvtg
  packages/react/src/components/Card/Card.story.jsx
  packages/react/src/components/Card/Card.test.jsx
  packages/react/src/components/Card/CardToolbar.jsx
  packages/react/src/components/Card/__snapshots__/Card.story.storyshot
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/BarChartDataSeriesContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormSettings.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/__snapshots__/ThresholdsFormItem.story.storyshot
  packages/react/src/components/CardEditor/CardEditForm/CommonCardEditFormFields.jsx
  packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  packages/react/src/components/ColorDropdown/ColorDropdown.jsx
  packages/react/src/components/ColorDropdown/__snapshots__/ColorDropdown.story.storyshot
  packages/react/src/components/DashboardEditor/DashboardEditor.test.jsx
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/__snapshots__/HotspotEditorTooltipTab.story.storyshot
  packages/react/src/components/HotspotEditorModal/HotspotTextStyleTab/__snapshots__/HotspotTextStyleTab.story.storyshot
  packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
Labels: status: ready to merge 🎉

#2083 fix(dashboardeditor): groupby should not be removed when data item is selected
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.test.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
Labels: status: ready to merge 🎉

#2082 fix(dashboardeditor): data filter was not showing
  packages/react/src/components/BarChartCard/barChartUtils.js
  packages/react/src/components/BarChartCard/barChartUtils.test.js
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
  packages/react/src/components/CardEditor/CardEditForm/_card-edit-form.scss
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.story.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2086 fix(datetimepicker): cant use multiple datetimepicker on same page #2085
  packages/react/src/components/DateTimePicker/DateTimePicker.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.story.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.test.jsx
  packages/react/src/components/DateTimePicker/__snapshots__/DateTimePicker.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2079 fix(table): resize inserted column in situations where it's too large
  packages/react/src/components/Table/TableHead/columnWidthUtilityFunctions.js
Labels: status: ready to merge 🎉

#2087 fix(valuecard): fix positioning of icons and color of trending secondary values
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/RuleBuilder/RuleBuilder.story.jsx
  packages/react/src/components/RuleBuilder/RuleBuilderEditor.story.jsx
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilderEditor.story.storyshot
  packages/react/src/components/ValueCard/Attribute.jsx
  packages/react/src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
  packages/react/src/components/ValueCard/_attribute.scss
Labels: status: ready to merge 🎉

#2084 chore(table): increase testing on TableToolbar and remove jest exception
  packages/react/jest.config.js
  packages/react/src/components/Table/Table.test.jsx
Labels: status: ready to merge 🎉

#2104 fix(dashboardgrid): workaround to trigger resize event
  packages/react/package.json
  packages/react/src/components/Dashboard/DashboardGrid.jsx
  packages/react/src/components/Dashboard/DashboardGrid.story.jsx
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
Labels: status: ready to merge 🎉

#2095 chore(timeseriescard): raise testing coverage
  packages/react/jest.config.js
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.test.jsx
  packages/react/src/components/TimeSeriesCard/timeSeriesUtils.js
  yarn.lock
Labels: status: ready to merge 🎉

#2100 chore(imagecard): increase testing coverage for ImageCard/ImageUploader
  packages/react/jest.config.js
  packages/react/src/components/ImageCard/ImageCard.test.jsx
  packages/react/src/components/ImageCard/ImageUploader.test.jsx
Labels: status: ready to merge 🎉

#2113 fix(dataseriesformitemmodal): grain selector is showing incorrectly for certain card types
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.test.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
Labels: status: ready to merge 🎉

#2099 fix(chart-cards): enable truncation options
  packages/react/jest.config.js
  packages/react/src/components/BarChartCard/BarChartCard.jsx
  packages/react/src/components/PieChartCard/PieChartCard.jsx
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.jsx
  packages/react/src/components/TimeSeriesCard/TimeSeriesCard.test.jsx
  packages/react/src/components/TimeSeriesCard/timeSeriesUtils.js
  packages/react/src/components/TimeSeriesCard/timeSeriesUtils.test.js
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2103 fix: tvt issues with progress indicator, card editor forms and dashboard editor modals
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ContentFormItemTitle.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ThresholdsFormItem.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ValueCardFormItems/ValueCardFormSettings.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/__snapshots__/ThresholdsFormItem.story.storyshot
  packages/react/src/components/CardEditor/CardEditForm/_card-edit-form.scss
  packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  packages/react/src/components/ProgressIndicator/ProgressIndicator.story.jsx
  packages/react/src/components/ProgressIndicator/__snapshots__/ProgressIndicator.story.storyshot
  packages/react/src/components/ProgressIndicator/_progress-indicator.scss
Labels: status: ready to merge 🎉

#2107 fix(timeseriesUtils): month should show one tick
  packages/react/src/components/TimeSeriesCard/timeSeriesUtils.js
Labels: status: ready to merge 🎉

#2119 fix(dashboardgrid): should not set state if component unmounts
  packages/react/src/components/Dashboard/DashboardGrid.jsx
Labels: status: ready to merge 🎉

#2120 fix(button): update spacing in loading state
  packages/react/src/components/Button/_button.scss
Labels: status: ready to merge 🎉

#2122 feat(valuecard): add new SMALLFULL size
  packages/react/src/components/Card/__snapshots__/Card.story.storyshot
  packages/react/src/components/CardEditor/CardEditForm/CardEditForm.jsx
  packages/react/src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
  packages/react/src/components/ValueCard/valueCardUtils.js
  packages/react/src/components/ValueCard/valueCardUtils.test.js
  packages/react/src/constants/LayoutConstants.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2124 fix(imageTile): Improve ImageTile regex
  packages/react/src/components/ImageGalleryModal/ImageTile.jsx
Labels: status: ready to merge 🎉

#2125 chore(storybook): add support story
  packages/react/.storybook/Welcome.story.jsx
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/src/components/Page/PageTitle.test.jsx
Labels: status: ready to merge 🎉

#2136 fix: use test:ci in the publish workflow
  .github/workflows/publish.yml
Labels: status: ready to merge 🎉

#2153 fix(table): add missing isSortable prop for aggregations
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/TableFoot/TableFoot.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2137 chore(file-drop): increase testing coverage
  packages/react/jest.config.js
  packages/react/src/components/FileDrop/FileDrop.jsx
  packages/react/src/components/FileDrop/FileDrop.test.jsx
Labels: status: ready to merge 🎉

#2139 chore(edit-page): ignore from test coverage
  packages/react/jest.config.js
Labels: status: ready to merge 🎉

#2132 chore(column-header-select): increase test coverage
  packages/react/jest.config.js
  packages/react/src/components/Table/TableHead/ColumnHeaderSelect/ColumnHeaderSelect.jsx
  packages/react/src/components/Table/TableHead/ColumnHeaderSelect/ColumnHeaderSelect.test.jsx
Labels: status: ready to merge 🎉

#2134 chore(page-title): raise test coverage
  packages/react/jest.config.js
  packages/react/src/components/Page/PageTitle.test.jsx
Labels: status: ready to merge 🎉

#2142 chore(image-hotspots): raise test coverage, remove exception
  packages/react/jest.config.js
  packages/react/package.json
  packages/react/src/components/ImageCard/ImageHotspots.test.jsx
Labels: status: ready to merge 🎉

#2163 chore(dashboard): ignore Dashboard/CardRenderer coverage
  packages/react/jest.config.js
Labels: status: ready to merge 🎉

#2165 chore(catalog-content): raise test coverage
  packages/react/jest.config.js
  packages/react/src/components/TileCatalog/TileCatalog.test.jsx
Labels: status: ready to merge 🎉

#2159 chore(thresholds-helper-functions): remove unused file
  packages/react/src/components/HotspotEditorModal/thresholdsHelperFunctions.js
Labels: status: ready to merge 🎉

#2158 feat(PageTitleBar): add scroll states
  packages/react/src/components/PageTitleBar/PageTitleBar.jsx
  packages/react/src/components/PageTitleBar/PageTitleBar.story.jsx
  packages/react/src/components/PageTitleBar/PageTitleBar.test.jsx
  packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
  packages/react/src/components/PageTitleBar/_page-title-bar.scss
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#2154 chore(value-card-utils): increase testing coverage
  packages/react/src/components/ValueCard/valueCardUtils.test.js
Labels: status: ready to merge 🎉

#2169 chore(page-hero): ignore page hero from test coverage
  packages/react/jest.config.js
Labels: status: ready to merge 🎉

#2184 fix(build): skip publishing if the local and remote heads are out of sync
  scripts/release.sh
Labels: status: ready to merge 🎉

#2171 chore(table-header): raise test coverage
  packages/react/jest.config.js
  packages/react/src/components/Table/TableHead/TableHeader.js
  packages/react/src/components/Table/TableHead/TableHeader.test.jsx
Labels: status: ready to merge 🎉

#2173 chore(column-resize): increase test coverage
  packages/react/jest.config.js
  packages/react/src/components/Table/TableHead/ColumnResize.jsx
  packages/react/src/components/Table/TableHead/ColumnResize.test.jsx
Labels: status: ready to merge 🎉

#2185 fix(value-card): fix error/warning icons not visible on card
  packages/react/src/components/Card/_data-state-renderer.scss
Labels: status: one more review 👀

#2175 chore(row-actions-error): increase testing coverage
  packages/react/jest.config.js
  packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.test.jsx
Labels: status: ready to merge 🎉

#2180 chore(dashboard-grid): increase testing coverage
  packages/react/jest.config.js
  packages/react/src/components/Dashboard/DashboardGrid.jsx
  packages/react/src/components/Dashboard/DashboardGrid.test.jsx
Labels: status: ready to merge 🎉
