Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2022-03, with the labels that each got.

#3201 refactor(date-time-picker): sync V1 and V2, refactor a lot of common code, sync tests
  packages/react/cypress-visual-screenshots/baseline/components/DateTimePicker/DateTimePickerV2.test.e2ex-v2-icon-only-rtl.png
  packages/react/cypress-visual-screenshots/baseline/components/DateTimePicker/DateTimePickerV2.test.e2ex-v2-rtl.png
  packages/react/jest.config.js
  packages/react/package.json
  packages/react/src/components/Card/__snapshots__/Card.story.storyshot
  packages/react/src/components/DateTimePicker/DateTimePicker.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.test.e2e.jsx
  packages/react/src/components/DateTimePicker/DateTimePickerV2.jsx
  packages/react/src/components/DateTimePicker/DateTimePickerV2.test.e2e.jsx
  packages/react/src/components/DateTimePicker/DateTimePickerV2.test.jsx
  packages/react/src/components/DateTimePicker/__snapshots__/DateTimePicker.story.storyshot
  packages/react/src/components/DateTimePicker/__snapshots__/DateTimePickerV2.story.storyshot
  packages/react/src/components/DateTimePicker/_date-time-picker.scss
  packages/react/src/components/DateTimePicker/_date-time-pickerv2.scss
  packages/react/src/components/DateTimePicker/dateTimePickerUtils.js
  packages/react/src/components/TimePickerSpinner/_time-picker-spinner.scss
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge 🎉

#3285 feat(tabs): add support for custom templates
  packages/angular/src/tabs/tab-dropdown.component.ts
  packages/angular/src/tabs/tab.interface.ts
  packages/angular/src/tabs/tabs.component.ts
  packages/angular/src/tabs/tabs.stories.ts
Labels: status: ready to merge 🎉, package: angular

#3088 feat(table): account for rowSpans in moveColumn
  packages/angular/src/table/table-model.class.spec.ts
  packages/angular/src/table/table-model.class.ts
  packages/angular/src/table/table.stories.ts
Labels: status: ready to merge 🎉, package: angular

#3347 feat(progress-bar): add inline variant
  packages/react/src/components/ProgressBar/ProgressBar.jsx
  packages/react/src/components/ProgressBar/ProgressBar.mdx
  packages/react/src/components/ProgressBar/ProgressBar.story.jsx
  packages/react/src/components/ProgressBar/ProgressBar.test.jsx
  packages/react/src/components/ProgressBar/__snapshots__/ProgressBar.story.storyshot
  packages/react/src/components/ProgressBar/_progress-bar.scss
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3366 docs(table): add story and mdx for toolbar
  packages/react/src/components/Table/Table.main.story.jsx
  packages/react/src/components/Table/Table.story.helpers.jsx
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.main.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/Table/__snapshots__/TableColumnCustomization.story.storyshot
  packages/react/src/components/Table/mdx/Table.mdx
  packages/react/src/components/Table/mdx/Toolbar.mdx
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
Labels: status: ready to merge 🎉

#3355 fix(table): add onapplytoolbaraction to statefultable
  packages/react/src/components/Table/StatefulTable.jsx
  packages/react/src/components/Table/StatefulTable.test.jsx
Labels: status: ready to merge 🎉

#3367 chore(ci): add concurrency option to CI workflows
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/format.yml
  .github/workflows/lint.yml
  .github/workflows/test-app.yml
  .github/workflows/test.yml
Labels: status: ready to merge 🎉

#3349 fix(table): add align to tooltips
  lerna.json
  packages/react/src/components/Table/TableCellRenderer/TableCellRenderer.jsx
  packages/react/src/components/Table/TableHead/TableHead.jsx
  packages/react/src/components/Table/TableHead/TableHead.test.jsx
  packages/react/src/components/Table/__snapshots__/Table.main.story.storyshot
Labels: status: ready to merge 🎉

#3378 fix: minor style update in PageTitleBar storybook
  packages/react/src/components/PageTitleBar/PageTitleBar.story.jsx
  packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
Labels: status: ready to merge 🎉

#3379 fix(table): allow searching by "false" boolean values
  packages/react/src/components/Table/tableReducer.js
  packages/react/src/components/Table/tableReducer.test.jsx
Labels: status: ready to merge 🎉

#3381 fix(card): style audit
  .github/workflows/codesandbox.md
  .github/workflows/test.yml
  Dockerfile
  packages/react/cypress-visual-screenshots/baseline/components/CardCodeEditor/CardCodeEditor.test.e2ex-CardCodeEditor.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-BarChartCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-Card.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-GaugeCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-ListCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-PieChartCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-TimeSeriesCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-ValueCard.png
  packages/react/cypress-visual-screenshots/baseline/components/DateTimePicker/DateTimePickerV2.test.e2ex-v2-icon-only-rtl.png
  packages/react/cypress-visual-screenshots/baseline/components/DateTimePicker/DateTimePickerV2.test.e2ex-v2-rtl.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-1.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-2.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-3.png
  packages/react/package.json
  packages/react/src/components/Card/Card.jsx
  packages/react/src/components/Card/Card.mdx
  packages/react/src/components/Card/Card.story.jsx
  packages/react/src/components/Card/Card.test.jsx
  packages/react/src/components/Card/__snapshots__/Card.story.storyshot
  packages/react/src/components/Card/_card.scss
  packages/react/src/components/ComboChartCard/__snapshots__/ComboChartCard.story.storyshot
  packages/react/src/components/Dashboard/DashboardGrid.test.e2e.jsx
  packages/react/src/components/ImageCard/__snapshots__/ImageCard.story.storyshot
  packages/react/src/components/ListCard/__snapshots__/ListCard.story.storyshot
  packages/react/src/components/PieChartCard/__snapshots__/PieChartCard.story.storyshot
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge 🎉

#3372 fix(resourcelist): convert style component to scss
  packages/react/src/components/ResourceList/ResourceList.jsx
  packages/react/src/components/ResourceList/ResourceList.test.jsx
  packages/react/src/components/ResourceList/__snapshots__/ResourceList.story.storyshot
  packages/react/src/components/ResourceList/_resourcelist.scss
  packages/react/src/styles.scss
Labels: status: ready to merge 🎉

#3374 3352 side nav implement search functionality of links
  packages/react/src/components/SideNav/FilterableSideNavMenu.jsx
  packages/react/src/components/SideNav/SideNav.jsx
  packages/react/src/components/SideNav/SideNav.story.jsx
  packages/react/src/components/SideNav/SideNav.test.jsx
  packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
  packages/react/src/components/SideNav/_side-nav.scss
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3382 feat(readonlyvalue): new component readonlyvalue
  packages/react/src/components/ReadOnlyValue/ReadOnlyValue.jsx
  packages/react/src/components/ReadOnlyValue/ReadOnlyValue.mdx
  packages/react/src/components/ReadOnlyValue/ReadOnlyValue.story.jsx
  packages/react/src/components/ReadOnlyValue/ReadOnlyValue.test.jsx
  packages/react/src/components/ReadOnlyValue/__snapshots__/ReadOnlyValue.story.storyshot
  packages/react/src/components/ReadOnlyValue/_read-only-value.scss
  packages/react/src/styles.scss
Labels: status: ready to merge 🎉

#3350 docs(table): add story and mdx for aggregations
  packages/react/src/components/Table/Table.main.story.jsx
  packages/react/src/components/Table/Table.story.helpers.jsx
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.main.story.storyshot
  packages/react/src/components/Table/__snapshots__/TableColumnCustomization.story.storyshot
  packages/react/src/components/Table/mdx/Aggregations.mdx
  packages/react/src/components/Table/mdx/Table.mdx
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
Labels: status: merge conflicts :no_entry_sign:

#3392 3043 card design audit
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-BarChartCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-Card.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-GaugeCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-ListCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-PieChartCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-TimeSeriesCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-ValueCard.png
  packages/react/src/components/Card/Card.story.jsx
  packages/react/src/components/Card/__snapshots__/Card.story.storyshot
  packages/react/src/components/Card/_card.scss
Labels: status: one more review 👀

#3388 [Value Card] Enhancements
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/src/components/Card/DataStateRenderer.jsx
  packages/react/src/components/CardCodeEditor/__snapshots__/CardCodeEditor.story.storyshot
  packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  packages/react/src/components/FilterTags/__snapshots__/FilterTags.story.storyshot
  packages/react/src/components/SuiteHeader/IdleLogoutConfirmationModal/__snapshots__/IdleLogoutConfirmationModal.story.storyshot
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/__snapshots__/SuiteHeaderAppSwitcher.story.storyshot
  packages/react/src/components/SuiteHeader/SuiteHeaderLogoutModal/__snapshots__/SuiteHeaderLogoutModal.story.storyshot
  packages/react/src/components/SuiteHeader/SuiteHeaderProfile/__snapshots__/SuiteHeaderProfile.story.storyshot
  packages/react/src/components/ValueCard/Attribute.jsx
  packages/react/src/components/ValueCard/Attribute.test.jsx
  packages/react/src/components/ValueCard/ValueCard.jsx
  packages/react/src/components/ValueCard/ValueCard.mdx
  packages/react/src/components/ValueCard/ValueCard.story.jsx
  packages/react/src/components/ValueCard/ValueContent.jsx
  packages/react/src/components/ValueCard/ValueRenderer.jsx
  packages/react/src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
  packages/react/src/components/ValueCard/_attribute.scss
  packages/react/src/components/ValueCard/_value-renderer.scss
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/index.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3401 Export readonlyvalue
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/src/index.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3405 fix(statefultable): include rowedit buttons in tableregister
  packages/react/src/components/Table/tableReducer.js
  packages/react/src/components/Table/tableReducer.test.jsx
Labels: status: ready to merge 🎉

#3397 3331 table story and docs for data editing
  packages/react/src/components/Table/Table.main.story.jsx
  packages/react/src/components/Table/Table.story.helpers.jsx
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.main.story.storyshot
  packages/react/src/components/Table/__snapshots__/TableColumnCustomization.story.storyshot
  packages/react/src/components/Table/mdx/EditData.mdx
  packages/react/src/components/Table/mdx/Table.mdx
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/internal/storyState.js
Labels: status: ready to merge 🎉

#3399 chore(use-lang-direction):update package
  packages/react/package.json
  yarn.lock
Labels: status: ready to merge 🎉

#3402 feat(card): enable clickable tooltips with external content to title
  packages/react/src/components/Card/Card.jsx
  packages/react/src/components/Card/Card.mdx
  packages/react/src/components/Card/Card.story.jsx
  packages/react/src/components/Card/Card.test.jsx
  packages/react/src/components/Card/CardTitle.jsx
  packages/react/src/components/Card/_card-title.scss
  packages/react/src/components/Card/_card.scss
  packages/react/src/components/Dashboard/DashboardGrid.story.jsx
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3412 fix: sidenav state example with pinned fix open/close on hover
  packages/react/src/components/SideNav/SideNav.jsx
  packages/react/src/components/SideNav/SideNav.story.jsx
  packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
  packages/react/src/components/SuiteHeader/SuiteHeader.story.jsx
Labels: status: ready to merge 🎉

#3380 Carbon upgrade 10.56.0
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-TableCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-1.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-3.png
  packages/react/package.json
  packages/react/src/components/ComposedModal/__snapshots__/ComposedModal.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/FileDrop/__snapshots__/FileDrop.story.storyshot
  packages/react/src/components/OverflowMenu/OverflowMenu.test.jsx
  packages/react/src/components/ProgressBar/__snapshots__/ProgressBar.story.storyshot
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.main.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge 🎉

#3228 fix(composed-modal): adjust height based on content and available area
  packages/react/src/components/CardCodeEditor/__snapshots__/CardCodeEditor.story.storyshot
  packages/react/src/components/ComposedModal/ComposedModal.jsx
  packages/react/src/components/ComposedModal/ComposedModal.test.jsx
  packages/react/src/components/ComposedModal/__snapshots__/ComposedModal.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/HotspotEditorModal/__snapshots__/HotspotEditorModal.story.storyshot
  packages/react/src/components/ImageGalleryModal/__snapshots__/ImageGalleryModal.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/SelectUsersModal/__snapshots__/SelectUsersModal.story.storyshot
  packages/react/src/components/Table/TableColumnCustomizationModal/__snapshots__/TableColumnCustomizationModal.story.storyshot
  packages/react/src/components/Table/TableManageViewsModal/__snapshots__/TableManageViewsModal.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/Table/__snapshots__/TableColumnCustomization.story.storyshot
  packages/react/src/components/Table/__snapshots__/TableUserViewManagement.story.storyshot
  packages/react/src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
Labels: status: ready to merge 🎉

#3411 feat: adjust padding when using filters in table
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-TableCard.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-1.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-2.png
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-3.png
  packages/react/cypress-visual-screenshots/baseline/components/TableCard/TableCard.test.e2ex-TableCard_Expanded.png
  packages/react/src/components/DataTable/_data-table.scss
  packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
  packages/react/src/components/SideNav/__snapshots__/SideNav.story.storyshot
  packages/react/src/components/Table/TableHead/ColumnGrouping/_column-grouping.scss
  packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
  packages/react/src/components/Table/TableHead/FilterHeaderRow/_filter-header-row.scss
  packages/react/src/components/Table/TableHead/_table-head.scss
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.main.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/Table/__snapshots__/TableUserViewManagement.story.storyshot
  packages/styles/src/components/Table/TableHead/_table-head.scss
Labels: status: ready to merge 🎉
