Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2022-02, with the labels that each got.

#3247 fix(table): fix proptype on TableToolbar, too
  packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3251 docs(table): add sorting story and create improved mdx
  packages/react/src/components/Table/StatefulTable.story.jsx
  packages/react/src/components/Table/Table.main.story.jsx
  packages/react/src/components/Table/Table.story.helpers.jsx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/TableBody/TableBodyRow/__snapshots__/TableBodyRow.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.main.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/Table/__snapshots__/TableColumnCustomization.story.storyshot
  packages/react/src/components/Table/mdx/Sorting.mdx
  packages/react/src/components/Table/mdx/Table.mdx
  packages/react/src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
Labels: status: ready to merge 🎉

#3239 fix(table): make table rows load more in skeleton state
  packages/react/src/components/Table/TableBody/SkeletonRow.jsx
  packages/react/src/components/Table/TableBody/SkeletonRow.test.jsx
  packages/react/src/components/Table/TableBody/TableBodyLoadMoreRow/TableBodyLoadMoreRow.jsx
  packages/react/src/components/Table/TableBody/TableBodyLoadMoreRow/TableBodyLoadMoreRow.test.jsx
  packages/react/src/components/Table/TableBody/TableBodyRowRenderer.jsx
Labels: status: ready to merge 🎉

#2993 fix(dateTimePicker): support 'relativeTo' customization
  packages/angular/src/date-time-picker/custom-date-time.component.ts
  packages/angular/src/date-time-picker/date-time-absolute.component.ts
  packages/angular/src/date-time-picker/date-time-picker.component.ts
  packages/angular/src/date-time-picker/date-time-relative.component.ts
Labels: status: ready to merge 🎉, package: angular

#3262 3252 table create story for row expansion
  packages/react/src/components/Table/Table.main.story.jsx
  packages/react/src/components/Table/Table.story.helpers.jsx
  packages/react/src/components/Table/TableBody/TableBodyRow/__snapshots__/TableBodyRow.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.main.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/Table/__snapshots__/TableColumnCustomization.story.storyshot
  packages/react/src/components/Table/mdx/RowExpansion.mdx
  packages/react/src/components/Table/mdx/Table.mdx
  packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
  packages/react/src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
  packages/react/src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
Labels: status: ready to merge 🎉

#3246 3234 table create manage views story
  packages/react/src/components/HotspotEditorModal/HotspotEditorTooltipTab/HotspotEditorTooltipTabREADME.mdx
  packages/react/src/components/Table/TableColumnCustomizationModal/TableColumnCustomizationModal.mdx
  packages/react/src/components/Table/TableManageViewsModal/TableManageViewsModal.mdx
  packages/react/src/components/Table/TableManageViewsModal/TableManageViewsModal.story.jsx
  packages/react/src/components/Table/TableManageViewsModal/TableManageViewsModalContent.mdx
  packages/react/src/components/Table/TableManageViewsModal/__snapshots__/TableManageViewsModal.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/TableSaveViewModal.mdx
  packages/react/src/components/Table/TableSaveViewModal/TableSaveViewModal.story.jsx
  packages/react/src/components/Table/TableSaveViewModal/TableSaveViewModalContent.mdx
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/TableUserViewManagement.story.jsx
  packages/react/src/components/Table/TableViewDropdown/TableViewDropdown.mdx
  packages/react/src/components/Table/TableViewDropdown/TableViewDropdown.story.jsx
  packages/react/src/components/Table/TableViewDropdown/TableViewDropdownContent.mdx
  packages/react/src/components/Table/TableViewDropdown/__snapshots__/TableViewDropdown.story.storyshot
  packages/react/src/components/Table/__snapshots__/TableUserViewManagement.story.storyshot
  packages/react/src/components/Table/mdx/Table.mdx
  packages/react/src/components/Table/mdx/TableColumnCustomization.mdx
  packages/react/src/components/Table/mdx/TableUserViewManagement.mdx
  packages/react/src/components/Table/mdx/TableUserViewManagementContent.mdx
  packages/react/src/components/Table/mdx/TableUserViewManagementTOC.mdx
  packages/react/src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
Labels: status: ready to merge 🎉

#3286 feat(progress-bar): add light prop
  packages/react/src/components/ProgressBar/ProgressBar.jsx
  packages/react/src/components/ProgressBar/ProgressBar.mdx
  packages/react/src/components/ProgressBar/ProgressBar.story.jsx
  packages/react/src/components/ProgressBar/__snapshots__/ProgressBar.story.storyshot
  packages/react/src/components/ProgressBar/_progress-bar.scss
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3259 fix(repo): change uuid imports to use uuid/v4
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ThresholdsFormItem.jsx
  packages/react/src/components/DashboardEditor/editorUtils.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.jsx
  packages/react/src/components/DateTimePicker/DateTimePickerV2.jsx
  packages/react/src/components/Table/TableColumnCustomization.story.jsx
  packages/react/src/hooks/useUniqueId.jsx
Labels: status: ready to merge 🎉

#2997 fix(dateTimePicker): modify custom range issue
  packages/angular/src/date-time-picker/custom-date-time.component.ts
  packages/angular/src/date-time-picker/date-time-absolute.component.ts
  packages/angular/src/date-time-picker/date-time-picker.component.ts
Labels: status: ready to merge 🎉, package: angular

#3275 3253 table create story for row nesting
  packages/react/src/components/Table/Table.main.story.jsx
  packages/react/src/components/Table/Table.story.helpers.jsx
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.main.story.storyshot
  packages/react/src/components/Table/__snapshots__/TableColumnCustomization.story.storyshot
  packages/react/src/components/Table/mdx/RowNesting.mdx
  packages/react/src/components/Table/mdx/Table.mdx
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
Labels: status: ready to merge 🎉

#3282 Some changes and fixes to the idle user detection logic
  packages/react/src/components/SuiteHeader/IdleLogoutConfirmationModal/IdleLogoutConfirmationModal.jsx
  packages/react/src/components/SuiteHeader/IdleLogoutConfirmationModal/IdleLogoutConfirmationModal.test.jsx
  packages/react/src/components/SuiteHeader/util/IdleTimer.js
  packages/react/src/components/SuiteHeader/util/IdleTimer.test.js
Labels: status: ready to merge 🎉

#3287 adjust size of loading spinner in row
  packages/react/src/components/Table/TableBody/RowActionsCell/_row-actions-cell.scss
Labels: status: ready to merge 🎉

#3257 docs(repo): initial onboarding documentation
  packages/react/docs/guides/onboarding.md
Labels: status: one more review 👀

#3294 feat(status-bar): add className prop
  packages/react/src/components/ProgressBar/ProgressBar.jsx
  packages/react/src/components/ProgressBar/ProgressBar.mdx
  packages/react/src/components/ProgressBar/ProgressBar.test.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3264 fix width of drag preview on large rows
  packages/react/src/components/List/ListItem/_list-item.scss
Labels: status: ready to merge 🎉

#3273 docs(dashboard-grid): add initial docs to cover DashboardGrid
  packages/react/src/components/Dashboard/DashboardGrid.mdx
  packages/react/src/components/Dashboard/DashboardGrid.story.jsx
Labels: status: ready to merge 🎉

#3281 feat(hierarchy-list): call onExpandedChange after rows are expanded
  packages/react/src/components/List/HierarchyList/HierarchyList.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.story.jsx
  packages/react/src/components/List/HierarchyList/HierarchyList.test.jsx
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/components/List/List.jsx
  packages/react/src/components/List/ListContent/ListContent.jsx
  packages/react/src/components/List/ListItem/ListItem.jsx
  packages/react/src/components/ProgressBar/__snapshots__/ProgressBar.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3297 docs(table): add story and docs for filters
  packages/react/src/components/Table/Table.main.story.jsx
  packages/react/src/components/Table/Table.story.helpers.jsx
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.main.story.storyshot
  packages/react/src/components/Table/__snapshots__/TableColumnCustomization.story.storyshot
  packages/react/src/components/Table/mdx/Filtering.mdx
  packages/react/src/components/Table/mdx/Table.mdx
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
Labels: status: merge conflicts :no_entry_sign:

#3268 fix(stateful-table): fix multi-sort and advanced filters cooperatively
  packages/react/src/components/Table/StatefulTable.test.e2e.jsx
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/Table.main.story.jsx
  packages/react/src/components/Table/tableReducer.js
Labels: status: ready to merge 🎉

#3296 3295 card padding prop
  packages/react/src/components/Card/Card.jsx
  packages/react/src/components/Card/Card.mdx
  packages/react/src/components/Card/Card.story.jsx
  packages/react/src/components/Card/Card.test.jsx
  packages/react/src/components/Card/__snapshots__/Card.story.storyshot
  packages/react/src/components/Card/_card.scss
  packages/react/src/constants/CardPropTypes.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3301 feat(tableviewdropdown): add prop isHidingStandardActions
  packages/react/src/components/Table/TableViewDropdown/TableViewDropdown.jsx
  packages/react/src/components/Table/TableViewDropdown/TableViewDropdown.story.jsx
  packages/react/src/components/Table/TableViewDropdown/TableViewDropdown.test.jsx
  packages/react/src/components/Table/TableViewDropdown/TableViewDropdownContent.mdx
  packages/react/src/components/Table/TableViewDropdown/__snapshots__/TableViewDropdown.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3324 docs(table): remove react wrapper for table stories
  packages/react/src/components/Table/Table.main.story.jsx
  packages/react/src/components/Table/Table.story.helpers.jsx
  packages/react/src/internal/storyState.js
Labels: status: ready to merge 🎉

#3322 fix(table): advanced filter crash fix
  packages/react/src/components/Table/TableToolbar/TableToolbarAdvancedFilterFlyout.jsx
  packages/react/src/components/Table/TableToolbar/TableToolbarAdvancedFilterFlyout.test.jsx
Labels: status: ready to merge 🎉

#3343 chore(repo): try esbuild storybook plugin to speed up builds
  packages/react/.storybook/main.js
  packages/react/package.json
  yarn.lock
Labels: status: ready to merge 🎉

#3274 feat(table): add prop to allow search to always be open
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-2.png
  packages/react/src/components/Table/StatefulTable.test.e2e.jsx
  packages/react/src/components/Table/Table.main.story.jsx
  packages/react/src/components/Table/Table.story.helpers.jsx
  packages/react/src/components/Table/Table.test.jsx
  packages/react/src/components/Table/TablePropTypes.js
  packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
  packages/react/src/components/Table/TableToolbar/_table-toolbar.scss
  packages/react/src/components/Table/baseTableReducer.js
  packages/react/src/components/Table/mdx/Table.mdx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3290 fix(IdleTimer): Adding the 'Secure;' property to the IdleTimer cookie and fixing the strategy to update the countdown in the logout confirmation dialog
  packages/react/src/components/SuiteHeader/IdleLogoutConfirmationModal/IdleLogoutConfirmationModal.test.jsx
  packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
  packages/react/src/components/SuiteHeader/util/IdleTimer.js
  packages/react/src/components/SuiteHeader/util/IdleTimer.test.js
Labels: status: ready to merge 🎉

#3263 fix(tile-gallery): fix styles, sizing on TileGalleryItem list
  packages/react/src/components/TileGallery/TileGallery.story.jsx
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/components/TileGallery/_tile-gallery.scss
Labels: status: ready to merge 🎉

#3327 fix(SuiteHeader): Adding support for basic browser workflows in Suiteheader actions.
  packages/react/src/components/Header/Header.story.jsx
  packages/react/src/components/Header/HeaderAction/HeaderAction.jsx
  packages/react/src/components/Header/HeaderAction/HeaderAction.test.jsx
  packages/react/src/components/Header/__snapshots__/Header.story.storyshot
  packages/react/src/components/ProgressBar/__snapshots__/ProgressBar.story.storyshot
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/SuiteHeader/SuiteHeader.jsx
  packages/react/src/components/SuiteHeader/SuiteHeader.story.jsx
  packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.test.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/__snapshots__/SuiteHeaderAppSwitcher.story.storyshot
  packages/react/src/components/SuiteHeader/SuiteHeaderLogoutModal/__snapshots__/SuiteHeaderLogoutModal.story.storyshot
  packages/react/src/components/SuiteHeader/SuiteHeaderProfile/SuiteHeaderProfile.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderProfile/__snapshots__/SuiteHeaderProfile.story.storyshot
  packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
  packages/react/src/components/SuiteHeader/_suite-header.scss
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3335 refactor(wizard-footer): remove styled components
  packages/react/src/components/Table/TableDetailWizard/__snapshots__/TableDetailWizard.story.storyshot
  packages/react/src/components/WizardInline/WizardFooter/WizardFooter.jsx
  packages/react/src/components/WizardInline/__snapshots__/WizardInline.story.storyshot
  packages/react/src/components/WizardInline/_wizard-inline.scss
  packages/react/src/components/WizardModal/__snapshots__/WizardModal.story.storyshot
Labels: status: ready to merge 🎉

#3326 fix(table): show correct number of columns in tableskeleton
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/TableSkeletonWithHeaders/TableSkeletonWithHeader.test.jsx
  packages/react/src/components/Table/TableSkeletonWithHeaders/TableSkeletonWithHeaders.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: waiting for author's response 💬

#3325 refactor(table-card): remove styled components
  packages/react/cypress-visual-screenshots/baseline/components/Dashboard/DashboardGrid.test.e2ex-DashboardGrid-lg-TableCard.png
  packages/react/cypress-visual-screenshots/baseline/components/TableCard/TableCard.test.e2ex-TableCard_Expanded.png
  packages/react/src/components/Dashboard/DashboardGrid.test.e2e.jsx
  packages/react/src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
  packages/react/src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot
  packages/react/src/components/DashboardEditor/__snapshots__/DashboardEditor.story.storyshot
  packages/react/src/components/TableCard/TableCard.jsx
  packages/react/src/components/TableCard/TableCard.story.jsx
  packages/react/src/components/TableCard/TableCard.test.e2e.jsx
  packages/react/src/components/TableCard/TableCard.test.jsx
  packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
  packages/react/src/components/TableCard/_table-card.scss
Labels: status: ready to merge 🎉

#3345 docs(table): add search story and mdx
  packages/react/src/components/Table/Table.main.story.jsx
  packages/react/src/components/Table/Table.story.helpers.jsx
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.main.story.storyshot
  packages/react/src/components/Table/__snapshots__/TableColumnCustomization.story.storyshot
  packages/react/src/components/Table/mdx/Filtering.mdx
  packages/react/src/components/Table/mdx/Searching.mdx
  packages/react/src/components/Table/mdx/Table.mdx
  packages/react/src/components/TileCatalogNew/__snapshots__/TileCatalogNew.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
Labels: status: merge conflicts :no_entry_sign:
