Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2022-01, with the labels that each got.

#3157 test(statefultable): add test for page size change
  packages/react/src/components/Table/tableReducer.test.jsx
Labels: status: ready to merge 🎉

#3170 feat: upgrade @carbon/charts
  packages/react/package.json
  packages/react/src/components/PieChartCard/PieChartCard.jsx
  yarn.lock
Labels: status: ready to merge 🎉

#3159 3150 list missing props in prop types definition
  packages/react/src/components/List/List.mdx
  packages/react/src/components/List/ListPropTypes.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3160 fix(list): indeterminate selection in story
  packages/react/src/components/List/List.story.jsx
Labels: status: ready to merge 🎉

#3163 docs:(inlineloading): remove old storybook code
  packages/react/src/components/InlineLoading/InlineLoading.story.jsx
Labels: status: ready to merge 🎉

#3164 docs:(textinput): remove old storybook code
  packages/react/src/components/TextInput/TextInput.story.jsx
Labels: status: ready to merge 🎉

#3166 fix(table): fix select all checkbox focus
  packages/react/src/components/Table/TableHead/_table-head.scss
Labels: status: ready to merge 🎉

#3112 [DateTimePicker]: Added validation for start/end time
  packages/react/src/components/DateTimePicker/DateTimePicker.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.test.e2e.jsx
  packages/react/src/components/DateTimePicker/DateTimePicker.test.jsx
Labels: status: ready to merge 🎉

#3116 feat(cardeditor): add maximumDataPoints to data series cards
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormSettings.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormSettings.test.jsx
  packages/react/src/components/CardEditor/__snapshots__/CardEditor.story.storyshot
  packages/react/src/components/DashboardEditor/DashboardEditor.jsx
  packages/react/src/components/DashboardEditor/DashboardEditor.test.jsx
  packages/react/src/index.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3181 List secondary value
  packages/react/src/components/List/HierarchyList/__snapshots__/HierarchyList.story.storyshot
  packages/react/src/components/List/List.mdx
  packages/react/src/components/List/ListItem/ListItem.jsx
  packages/react/src/components/List/ListItem/ListItem.story.jsx
  packages/react/src/components/List/ListItem/ListItem.test.jsx
  packages/react/src/components/List/ListItem/__snapshots__/ListItem.story.storyshot
  packages/react/src/components/List/ListPropTypes.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3047 chore(repo): v3 pr action fixes
  .github/workflows/update-v3.yml
Labels: status: ready for review 👀

#3185 3044 menu button style audit button variations
  packages/react/src/components/Button/_button.scss
  packages/react/src/components/MenuButton/MenuButton.jsx
  packages/react/src/components/MenuButton/MenuButton.story.jsx
  packages/react/src/components/MenuButton/MenuButton.test.jsx
  packages/react/src/components/MenuButton/SingleMenuButton.jsx
  packages/react/src/components/MenuButton/SplitMenuButton.jsx
  packages/react/src/components/MenuButton/_menu-button-shadow-blocker.scss
  packages/react/src/components/MenuButton/_menu-button.scss
  packages/react/src/components/MenuButton/utils.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: needs more info :woman_shrugging:

#3178 fix(table): margin between trash icon and delete on toolbar
  packages/react/src/components/Table/TableToolbar/_table-toolbar.scss
Labels: status: ready to merge 🎉

#3197 3194 storybook knobs are leaking into all stories
  packages/react/src/components/Dashboard/Dashboard.story.jsx
  packages/react/src/components/GaugeCard/GaugeCard.story.jsx
  packages/react/src/components/ImageCard/HotspotContent.story.jsx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/TileGallery/TileGallery.story.jsx
Labels: status: ready to merge 🎉

#3205 docs(table): add column customization section
  packages/react/src/components/Table/StatefulTable.story.jsx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/TableColumnCustomization.story.jsx
  packages/react/src/components/Table/TableColumnCustomizationModal/TableColumnCustomizationModal.story.jsx
  packages/react/src/components/Table/TableColumnCustomizationModal/__snapshots__/TableColumnCustomizationModal.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/Table/__snapshots__/TableColumnCustomization.story.storyshot
  packages/react/src/components/Table/mdx/Table.mdx
  packages/react/src/components/Table/mdx/TableColumnCustomization.mdx
  packages/react/src/components/Table/mdx/TableColumnCustomizationContent.mdx
  packages/react/src/components/Table/mdx/TableColumnCustomizationTOC.mdx
  packages/react/src/components/TableCard/__snapshots__/TableCard.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/components/TimeSeriesCard/__snapshots__/TimeSeriesCard.story.storyshot
Labels: status: merge conflicts :no_entry_sign:

#3203 fix(table): table toolbar action overflow truncation
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-3.png
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/Table.test.jsx
  packages/react/src/components/Table/TableToolbar/TableToolbar.jsx
  packages/react/src/components/Table/TableToolbar/_table-toolbar.scss
  packages/react/src/components/Table/tableUtilities.jsx
  packages/react/src/hooks/useDynamicOverflowMenuItems.jsx
Labels: status: ready to merge 🎉

#3214 fix(side-nav): sidenav menu not collapsing
  packages/react/src/components/SideNav/SideNav.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3207 fix(page-title-bar): fix accessibility error for `span` in `ol`
  packages/react/src/components/PageTitleBar/PageTitleBar.jsx
  packages/react/src/components/PageTitleBar/PageTitleBar.test.jsx
  packages/react/src/components/PageTitleBar/__snapshots__/PageTitleBar.story.storyshot
  packages/react/src/components/PageTitleBar/_page-title-bar.scss
Labels: status: ready to merge 🎉

#3219 fix(suite-header): do not allow tabbing to closed app switcher panel
  packages/react/src/components/Header/Header.story.jsx
  packages/react/src/components/Header/HeaderAction/HeaderActionPanel.jsx
  packages/react/src/components/Header/HeaderActionGroup.jsx
  packages/react/src/components/SuiteHeader/SuiteHeader.jsx
  packages/react/src/components/SuiteHeader/SuiteHeader.test.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.jsx
  packages/react/src/components/SuiteHeader/SuiteHeaderAppSwitcher/__snapshots__/SuiteHeaderAppSwitcher.story.storyshot
  packages/react/src/components/SuiteHeader/__snapshots__/SuiteHeader.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3224 fix(table): add skeleton column for nesting rows when lazy loading
  packages/react/src/components/Table/Table.test.e2e.jsx
  packages/react/src/components/Table/TableBody/TableBodyRowRenderer.jsx
Labels: status: ready to merge 🎉

#3232 feat(progress-bar): initial addition of new progress bar component
  packages/react/.storybook/__snapshots__/Welcome.story.storyshot
  packages/react/src/components/ProgressBar/ProgressBar.jsx
  packages/react/src/components/ProgressBar/ProgressBar.mdx
  packages/react/src/components/ProgressBar/ProgressBar.story.jsx
  packages/react/src/components/ProgressBar/ProgressBar.test.a11y.jsx
  packages/react/src/components/ProgressBar/ProgressBar.test.jsx
  packages/react/src/components/ProgressBar/__snapshots__/ProgressBar.story.storyshot
  packages/react/src/components/ProgressBar/_progress-bar.scss
  packages/react/src/components/ProgressBar/thresholdPropTypes.js
  packages/react/src/components/RuleBuilder/__snapshots__/RuleBuilder.story.storyshot
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/components/ValueCard/Attribute.jsx
  packages/react/src/hooks/useMatchingThreshold.js
  packages/react/src/hooks/useMerged.js
  packages/react/src/hooks/useMerged.test.js
  packages/react/src/index.js
  packages/react/src/styles.scss
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3226 fix(table): filter tag has wrong color on hover
  packages/react/cypress-visual-screenshots/baseline/components/Table/Table.test.e2ex-snapshot-3.png
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/__snapshots__/StatefulTable.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/Table/_table.scss
Labels: status: ready for review 👀

#3222 fix(table): fix incorrect data proptype
  packages/react/src/components/Table/Table.jsx
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3230 3206 table create main playground story
  packages/react/jest.config.js
  packages/react/package.json
  packages/react/src/components/CardCodeEditor/CardCodeEditor.test.e2e.jsx
  packages/react/src/components/Table/StatefulTable.story.jsx
  packages/react/src/components/Table/StatefulTable.test.e2e.jsx
  packages/react/src/components/Table/Table.main.story.jsx
  packages/react/src/components/Table/Table.story.helpers.jsx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/TableColumnCustomization.story.jsx
  packages/react/src/components/Table/TableFoot/TableFoot.test.jsx
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.main.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/Table/__snapshots__/TableColumnCustomization.story.storyshot
  packages/react/src/components/Table/tableReducer.test.jsx
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
Labels: status: ready to merge 🎉

#3235 fix(table): add rownesting in total columns calc
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
  packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.test.jsx
Labels: status: ready to merge 🎉

#3238 fix(table): add hidden prop to row action
  packages/react/src/components/Table/StatefulTable.story.jsx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx
  packages/react/src/components/Table/TableBody/RowActionsCell/RowActionsCell.test.jsx
  packages/react/src/components/Table/TablePropTypes.js
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
Labels: status: ready to merge 🎉

#3241 V3 upgrade
  CHANGELOG.md
  lerna.json
  packages/react/CHANGELOG.md
  packages/react/jest.config.js
  packages/react/package.json
  packages/react/src/components/CardCodeEditor/CardCodeEditor.test.e2e.jsx
  packages/react/src/components/List/List.jsx
  packages/react/src/components/List/List.mdx
  packages/react/src/components/List/List.story.jsx
  packages/react/src/components/List/List.test.jsx
  packages/react/src/components/List/ListHeader/ListHeader.jsx
  packages/react/src/components/List/__snapshots__/List.story.storyshot
  packages/react/src/components/Table/StatefulTable.story.jsx
  packages/react/src/components/Table/StatefulTable.test.e2e.jsx
  packages/react/src/components/Table/Table.jsx
  packages/react/src/components/Table/Table.main.story.jsx
  packages/react/src/components/Table/Table.story.helpers.jsx
  packages/react/src/components/Table/Table.story.jsx
  packages/react/src/components/Table/TableColumnCustomization.story.jsx
  packages/react/src/components/Table/TableFoot/TableFoot.test.jsx
  packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.jsx
  packages/react/src/components/Table/TableHead/FilterHeaderRow/FilterHeaderRow.test.jsx
  packages/react/src/components/Table/TableSaveViewModal/__snapshots__/TableSaveViewModal.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.main.story.storyshot
  packages/react/src/components/Table/__snapshots__/Table.story.storyshot
  packages/react/src/components/Table/__snapshots__/TableColumnCustomization.story.storyshot
  packages/react/src/components/Table/tableReducer.test.jsx
  packages/react/src/components/TileGallery/__snapshots__/TileGallery.story.storyshot
  packages/react/src/utils/__tests__/__snapshots__/publicAPI.test.js.snap
  yarn.lock
Labels: status: ready to merge 🎉
