Repository carbon-design-system/carbon-addons-iot-react, pull requests merged in 2024-06, with the labels that each got.

#3870 feat: deploy storybook to github page
  .github/README.MD
  .github/workflows/deploy.yml
  package.json
  packages/react/README.MD
  packages/react/package.json
Labels: status: ready for review 👀

#3871 feat: add tooltip to the tablecard column and value card label
  .github/CODEOWNERS
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.test.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormContent.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx
  packages/react/src/components/HotspotEditorModal/HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.jsx
  packages/react/src/components/ValueCard/Attribute.jsx
  packages/react/src/components/ValueCard/ValueCard.story.jsx
  packages/react/src/components/ValueCard/__snapshots__/ValueCard.story.storyshot
Labels: status: ready to merge 🎉, offering: platform/monitor

#3872 fix: thresold item
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ThresholdsFormItem.jsx
  packages/react/src/components/CardEditor/CardEditForm/CardEditFormItems/ThresholdsFormItem.test.jsx
  packages/react/src/components/CardEditor/CardEditForm/_card-edit-form.scss
Labels: status: ready to merge 🎉
